### ISSUE TITLE
re4tweaks glitches certain cutscenes

### ISSUE THREAD

**Issue by 1337Walrus** [nipkownix/re4_tweaks#10]
Not sure how to word it, but installing re4_tweaks (latest stable version, 1.5) seems to glitch out multiple cutscenes. The audio still plays, but the screen displays as pure black until it ends.

Attached: The bug affecting the first Ada's Report (it's only a few seconds before I skip it with ESC because of gamebar recording's abysmal compression), but I've also seen it happen to:
Separate Ways Prologue
Separate Ways Chapter 1 End

https://user-images.githubusercontent.com/93822595/140608008-b56eb382-2c43-48ec-8d7d-bd09e9805296.mp4

For reference, Ada's Report 1 is supposed to play out [like this.](https://www.youtube.com/watch?v=gVRLSsNaSW4)

**Comment by nipkownix** [comment]
Ah, this is caused by my hacky implementation of DisableFilmGrain.
I've found a much better solution that shouldn't cause any problems, but I had no time to make a new release yet.
Can you confirm this test build works for you?

[winmm.zip](https://github.com/nipkownix/re4_tweaks/files/7490451/winmm.zip)

**Comment by 1337Walrus** [comment]
> Ah, this is caused by my hacky implementation of DisableFilmGrain. I've found a much better solution that shouldn't cause any problems, but I had no time to make a new release yet. Can you confirm this test build works for you?
> 
> [winmm.zip](https://github.com/nipkownix/re4_tweaks/files/7490451/winmm.zip)

Can confirm this test build works properly in regards to cutscenes. Thanks! As an asides, is there an ETA for the next stable release?

**Comment by nipkownix** [comment]
Nice! A stable release should happen pretty soon. I just need to take some time to properly test the recent changes.

**Comment by nipkownix** [comment]
The latest release should have this fixed.
