### ISSUE TITLE
Allow selling silencer to merchant

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#100]
RE4HD added the hidden silencer back to the game, but as albert pointed out on re4hd.com:

>you can’t sell it, just discard it. The sell option of this item is not in the game’s code unfortunately

I did notice a bunch of tables related to item prices in the code though, so might be possible to edit those and add silencer to the list - `MerchantRoomInit` points to most of the lists, seems to be different lists depending on room, those might just be items you can purchase though, but maybe selling is somewhere around there too.

Think I saw some guides on residentevilmodding forum about editing merchant tables in the EXE too - @Mister-Curious have you heard of anyone doing something like this before?

g_item_price_tbl (C16E90 in 1.1.0) seems to be the main price table, probably used for selling items too - not sure what the structure of it is yet though, if anyone has experience with it please let us know!

**Comment by nipkownix** [comment]
Ah, Mister-Curious probably has more info on that, yeah.
Would be nice to add this feature.

**Comment by Mister-Curious** [comment]
Yes, there are many guides on how to edit the binary to change which items are allowed to be bought/sold and their prices, along with other guides on how to modify available weapon uprades etc. While I always welcome the mention, this is not my field of expertise, but I can ask around on the Discord and see who steps up, as there are several users there who might have some more info. 

Other than that..... 
If I asked someone to write raw HEX code to enable this feature could you guys reverse engineer that to actual code for the DLL? My engineer makes all of our binary changes with CheatEngine, which he exports as raw hex instructions that we paste in the  binary (there are swaths of unused blocks available in the binary to write to.. just look up CC CC CC CC and you will see). He is quite talented and can pretty much make any changes.

**Comment by nipkownix** [comment]
>If I asked someone to write raw HEX code to enable this feature could you guys reverse engineer that to actual code for the DLL? 

Yeah, definitely. Thanks for looking into it.
That is pretty interesting. I didn't know modding the merchant item list was a common/known thing.

**Comment by Mister-Curious** [comment]
ok so the community stepped up and answered the question about how to do this (2 experienced modders gave the same anwer). Basically they are saying you have to swap the Silencer ID with another sellable ID for the Silencer to become sellable. For that through, you have to chose an item that is not in use. Fortunately there seems to be only one item which is on this table, but not used in the game: **A9 - treasure map (village)**

See [this guide](https://residentevilmodding.boards.net/thread/13838/price-items-exe?page=1&scrollTo=130190) for a more complete list of items in the table of sellable items. 

I think it's as easy and looking for this value in the binary **A9 00 2C 01 01 00** and replacing it with **3F 00 2C 01 01 00**
A9 = Treasure Map
34 = Silencer for Handgun

The tutorial in that link says about pricing:

_**The prices of the items are in Uint16, 2 bytes, being that to obtain the exact value you have to always reduce the last number
ex: spinel 57 00 c8 00 01
57 00 = spinel
c8 00 = price, converting to full value is 200, but in the game it is 2000**_

So it seems this value has a multiplier somewhere. 

Those values are just part of a table, so you might be able to write code that increases the table size, but I think just swapping those out will do the trick. I am not 100% on that one map not being sellable, but that is what I have been told.

**Comment by emoose** [comment]
Oh nice, thanks for getting in touch with them.

So looks like that table is the `g_item_price_tbl` I'd mentioned (didn't know any of the structure though, but thanks to that post now we do)

Most of the `Merchant::XXX` funcs seem to iterate through the table by checking for 0xFFFF as end-of-records marker - and looks like last entry in that table is 0xFFFF, with just enough free space after it to maybe hold 1 extra entry:
![image](https://user-images.githubusercontent.com/1755499/153509517-20bdf8e9-4373-4050-9c58-5459b268e79a.png)

So hopefully should be possible to add silencer to end of the list there instead of needing to replace another item, might need to update the `g_item_price_tbl_num` value at C17478 too.

BTW is **34** definitely value for the silencer, or is it **3F**? both are mentioned in your post.

Also if anyone has a savegame with the silencer on it could you upload it here? I don't really know how to add it with CE or anything like that.

**Comment by nipkownix** [comment]
Fiy, there's a very good open-source ~ahem~ trainer here that has inventory editing and supports both 1.0.6 and 1.1.0
https://github.com/machinematrix/Resident-Evil-4-Trainer

(I think RE4_tweaks has some incompatibility with it though that I haven't looked at yet)

**Comment by laymonage** [comment]
If you still need it, you can use this save file [savegame00.zip](https://github.com/nipkownix/re4_tweaks/files/8045196/savegame00.zip)

The 19th save file (2-3 Chapter End) is just outside the castle, there's a merchant nearby and the chapter doesn't begin with a cutscene.

**Comment by emoose** [comment]
@laymonage many thanks!

So confirmed that editing C1719C with CE to `3F 00 2C 01 01 00 FF FF` & updating list counter at C17478 from 131 to 132 allows silencer to be shown in sell list:
![20220211010751_1](https://user-images.githubusercontent.com/1755499/153522827-23c56e16-8d5f-4ff9-9d3b-8a2eaa254616.jpg)

Still need to look at the other builds to make sure they have enough free space, but hopefully should be pretty easy to make a pattern & update this in the DLL.

I guess we should probably have an INI setting for this so people can disable it if they like, since some modders might edit the EXE list themselves (and could probably break our pattern scan), if so then they can just disable the patch.

**Comment by nipkownix** [comment]
@emoose, not exactly related to this, but: Have you stumbled upon where the game stores info about the items the merchant sells? I wanted to make some changes to the Chicago Typewriter. The one the merchant sells is a fully-upgraded one, which includes infinite ammo. Originally, the devs intended to make that gun upgradeable, and even implemented actual ammo for it: https://youtu.be/dnrazxx7Yew?t=73

It just goes unused. Would be a cool addition. This is one of the few guns I've never used in this game because it is just too OP, having infinite ammo and insane damage.

Memory editing its upgrade value to 1 already gets rid of the infinite ammo, but I'm not sure _where_ that value is coming from.

**Comment by emoose** [comment]
Merchant data seems to get loaded in with the `levelDataAdd` & `stockDataAdd` funcs, if you look at xrefs to it the 2nd param seems to be the data to load in. I think levelData is data about the upgrades while stockData is items being sold.
Not sure what the format of that data is though, it might just be a list of item IDs...

`itemInfo` also seems to take in an item ID and updates some info based on it, maybe that's what sets up typewriter to fully upgraded.
