### ISSUE TITLE
106Inventory Bug

### ISSUE THREAD

**Issue by KsaNL** [nipkownix/re4_tweaks#103]
I found 38G in v106v has a bug in inventory ,110 not found.[https://ibb.co/RYjy6jn]
I manage to cmp code but it seem like v110 cant load game without the dll. 
How to fix it?
void GetLimitPointers()

**Comment by Mister-Curious** [comment]
`I found 38G `
What is 38G?

**Comment by Mister-Curious** [comment]
> I found 38G

What is 38G?

**Comment by KsaNL** [comment]
No use, just bug in v106.
