### ISSUE TITLE
Suggestion: auto detect movie resolution

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#11]
Might be nice if the movie-resolution patch could be automated based on the movie resolution, instead of needing to be specified in the winmm.ini, seeing as using 1080p in the winmm.ini also makes the original 512x336 movies play in a tiny screen, and also looks like the default 512x336 can cause a crash if the movie is in 1080p :/

At 0x6CD16D (1.1.0) there's a call to cSofdec::SetupResolution with the movie resolution passed over to it AFAIK (with movie resolution read by mwPlyGetHdrInf), maybe hooking that SetupResolution func & patching game based on it could work. 
Maybe this is only ran after the part you patch for the resolution though, haven't really looked into it that much yet.

**Comment by nipkownix** [comment]
Wait, the game actually reads the resolution from the file? I thought it didn't. Heh.

I'll look into it soon.

**Comment by nipkownix** [comment]
Implemented as of f79b4d6cc26ef7. Let me know if it works for you.
<details>
  <summary>Bonus cursed test screen:</summary>
  
![image](https://user-images.githubusercontent.com/33870163/140846752-1e17c9f5-f97a-4840-b259-0a377cfd8185.png)
  
</details>

**Comment by emoose** [comment]
Looks to be working fine for me with the 1080p SFD you posted before, good work!
