### ISSUE TITLE
Bugfix request: make retry/load menu actually keep the selected option

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#12]
On the retry/load menu you have a few options, `retry from checkpoint`, `load save`, or `exit to main menu`.
After selecting one the game asks if you're sure, and you have to choose yes/no - except during the yes/no selection your mouse cursor can actually change what option you selected, so you might choose `retry from checkpoint`, then accidentally hover over `exit to main menu` before choosing yes to continue, making the game actually exit back to main menu, even though `retry from checkpoint` was what you selected >.>

This bug bit me a couple times during my main RE4 playthrough, would be nice if option could be "locked-in" once you pick it instead.
Using mouse cursor to pick yes/no is kinda buggy as it is, moving over the text doesn't choose it, you have to put it somewhere just nearby instead - maybe would be better to just disable mouse cursor on this screen after an option is picked.

Those menus seem coded pretty differently to GC build so don't have much named for it in my IDB, `OptionScreen::move` calls into `retry_load_menu`, but that func is way different to GC version - maybe should take a look at PS2 one instead...

**Comment by nipkownix** [comment]
Ah, this has been on my list for a while, but I never got around to trying to fix it.
I'll take a look at it soon.

**Comment by nipkownix** [comment]
Got something implemented in 63e02a3beaa. Let me know if that's good.

**Comment by emoose** [comment]
Nice, looks like it's fixed now, thanks for looking into it!
