### ISSUE TITLE
Visual Glitches with Ashley's Sp. Costume During Cutscenes

### ISSUE THREAD

**Issue by bedsoft** [nipkownix/re4_tweaks#125]
![20220217194704_1](https://user-images.githubusercontent.com/99671412/154622369-673380d8-6a72-4de0-a2cb-8133f92f5468.jpg)

This was during the cutscene at the end of 2-2, didn't look like this in cutscenes previously but it looks like the game is still trying to force the standard costume model with the special costume textures if I had to guess. Looks fine in gameplay.

**Comment by Mister-Curious** [comment]
May I ask, even with just the vanilla game how does one get Ashely to have a special costume in game play? If you are using the trainer to accomplish this I will explain how things work.

**Comment by bedsoft** [comment]
I think you just get it for beating the game once, not 100% sure because i would have unlocked it a few years ago when i first played the game, but I already had it available when i started a save with the HD mod

**Comment by RiasatSalminSami** [comment]
> May I ask, even with just the vanilla game how does one get Ashely to have a special costume in cutscenes? If you are using the trainer to accomplish this I will explain how things work.

Only costume that didn't show up in cutscenes were the set that includes Leon's Mafia suit.

The set containing RPD and this Ashley's white outfit always showed in the vanilla game cutscenes.

**Comment by bedsoft** [comment]
@nipkownix ah, my bad! i didn't realize there had been a patch
