### ISSUE TITLE
Everytime crash for armored Ashley

### ISSUE THREAD

**Issue by M1sh2** [nipkownix/re4_tweaks#127]
The game freezes with an error when this fix is enabled when playing for armored Ashley. I haven't looked at the rest of the costumes, maybe the problem is only with him.
Also, If this fix is enabled, it freezes immediately when Ashley goes inside. (after as Leon helps)
[bio4.exe.20220219163532.log](https://github.com/nipkownix/re4_tweaks/files/8101935/bio4.exe.20220219163532.log)
![Безымянный](https://user-images.githubusercontent.com/59886778/154797113-e63a2b3c-2159-42a1-b03b-cf8467c9a892.png)

**Comment by emoose** [comment]
Oh I didn't try that fix with armored Ashley, not really sure why that'd break it, will have to give it a try myself.

Could you create a `CrashDumps` folder next to your bio4.exe, try triggering the crash, then ZIP the `CrashDumps` contents and upload them here?

**Comment by M1sh2** [comment]
https://disk.yandex.ru/d/52ynE8V1u-ouqQ
I can't put here zip archive, i send my dumps on yandex disk

**Comment by emoose** [comment]
Hm, seems the `ptrpG` variable isn't being set for you some reason... ah damn, looks like we're only setting that if EnableDebugMenu is true - I'm sure there was a pG pointer somewhere that we set besides debug stuff though.

Anyway could you confirm whether enabling `EnableDebugMenu` & restarting game gets rid of the crashing?

Thanks for the other dumps, will try taking a look over them some time.

**Comment by nipkownix** [comment]
> Hm, seems the ptrpG variable isn't being set for you some reason...

Oh uh, might be worth it to add a new include that has all of the game vars we need (such as pG, mouse delta, etc) so we can sig scan it once and make things easier for us?

**Comment by M1sh2** [comment]
> > Hm, seems the ptrpG variable isn't being set for you some reason...
> 
> Oh uh, might be worth it to add a new include that has all of the game vars we need (such as pG, mouse delta, etc) so we can sig scan it once and make things easier for us?
![1](https://user-images.githubusercontent.com/59886778/154799795-2741b514-7d5f-45ea-8c5e-fa3afb245f84.png)
![2](https://user-images.githubusercontent.com/59886778/154799800-2cd9cfd9-bd65-40d9-afb3-c6d21bb24d60.png)
I also tried to connect the fix, and restart the game (I'm using the latest version from action, release version). Nothing has changed

**Comment by emoose** [comment]
>I also tried to connect the fix, and restart the game (I'm using the latest version from action, release version). Nothing has changed.

Could you try with this build? Seems to stop it crashing for me: 
[dinput8-pGpointerFix.zip](https://github.com/nipkownix/re4_tweaks/files/8102097/dinput8-pGpointerFix.zip)

> Oh uh, might be worth it to add a new include that has all of the game vars we need (such as pG, mouse delta, etc) so we can sig scan it once and make things easier for us?

Yeah that'd probably be better, not sure what things we might need to make common like that though, but pG seems to get used a lot at least, for now I've just added it to dllmain and let things access it with `extern uint8_t** ptrpG;` but it's kinda ugly...

**Comment by M1sh2** [comment]
Yes, it works now
![изображение](https://user-images.githubusercontent.com/59886778/154800250-0297f19c-90d6-40f2-af6a-44b9b550c9c8.png)
