### ISSUE TITLE
SilenceArmoredAshley crash after part where you shoot metal bindings

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#131]
Game seems to consistently crash with SilenceArmoredAshley active, luckily debug `SAVE GAME` option makes a save right before the crash happens:
[savegame00.zip](https://github.com/nipkownix/re4_tweaks/files/8103062/savegame00.zip)

Load from 4th save slot, skip the cutscene, and after she looks around for a bit she'll run to the side, which crashes for me every time, only fix is disabling `SilenceArmoredAshley`.

Crash dump: [bio4.exe.20220219215421.zip](https://github.com/nipkownix/re4_tweaks/files/8103066/bio4.exe.20220219215421.zip) (1.1.0)

Seems to be something to do with pointer used by EmMgr getting corrupted or something, weird.

E: hm, looks like it's patching somewhere different in 1.1.0 compared to 1.0.6 - same function though, but looks like different part of it.

E2: adding some of the bytes from the insn before it seems to fix it, I just added "00 02" to the start of the pattern & changed offset to 2 - all vers seem to use the same `cmp     byte ptr [edx+4FCBh], 2` insn before it so should be fine, could probably add the whole opcode really.

(I thought `pattern.count(1)` would have caught issues like that where more than 1 instance of same thing is found though? Guess it's only making sure there's at least **_n_** matches found, and doesn't care if there's more than **_n_**, would probably slow things down a lot if it had to scan the whole EXE space I suppose.)

**Comment by nipkownix** [comment]
Hmm? This is the first time `pattern.count(x)` didn't save me from an issue like this. And I even tested all exe versions for a bit .-.

Feel free to PR the fix if you feel like doing it.

Thanks for catching this one. I'd probably not have noticed otherwise.
