### ISSUE TITLE
Error when opening bio4.exe

### ISSUE THREAD

**Issue by BlackBoiEvsen** [nipkownix/re4_tweaks#134]
Assertion failed!

Program: C:\Games\Resident Evil 4 Ultimate HD\Resident Evil 4 Ultimate HD\Bin32\DINPUT8.dll
File: D:\Porgrams\git_repos\re4_tweaks\external\...\Patterns.h
Line:22

**Comment by nipkownix** [comment]
Your game is outdated. See #60.

**Comment by BlackBoiEvsen** [comment]
that was fast as hell
