### ISSUE TITLE
NewInputBug

### ISSUE THREAD

**Issue by KsaNL** [nipkownix/re4_tweaks#138]
Insert a controller while in gaming.
Then no input signal act to game.

**Comment by Mister-Curious** [comment]
You might want to provide some more information if you are going to submit a bug report. Also, providing info about the steps you took to troubleshoot can make things easier for others to help.  So tell me a few things:
- what kind of controller is it? 
- does it work with other games on your computer?
-  have you configured the controller properly in Steam Controller settings?
- go to RUN in windows and type `joy.cpl `- Does your controller register in this window?

**Comment by KsaNL** [comment]
> You might want to provide some more information if you are going to submit a bug report

1.Build the latest re4tweaks version 
2.Go into game and load a savefile
3.Insert a xbox360 controller to usb
4.Wait for steam load 
5.No signal after load
6.Latest version bug, not before

**Comment by nipkownix** [comment]
Hmm, I'm using a controller right now and it works fine.
Does it work if you plug in your controller before starting the game?

**Comment by KsaNL** [comment]
> Hmm, I'm using a controller right now and it works fine. Does it work if you plug in your controller before starting the game?

Did you let Leon to take a walk?
I think it is quite very emergency.

**Comment by KsaNL** [comment]
Waiting for input.hpp fixed

**Comment by nipkownix** [comment]
Input.hpp is related to keyboard and mouse only, it has nothing to do with controllers.

I can't reproduce your issue. The controller works fine here. I'd appreciate some more info about how I can reproduce the issue.

**Comment by KsaNL** [comment]
> Input.hpp is related to keyboard and mouse only, it has nothing to do with controllers.
> 
> I can't reproduce your issue. The controller works fine here. I'd appreciate some more info about how I can reproduce the issue.

Yes 
Old release version without input.hpp i think every things are fine
Lastest build i notices that you add the input.hpp and a logger. 
Maybe the fault is not caused by them.
Its quite very emergency to let you reproduce this. All test bugs are found in v106 (i'm not sure it will be found in v110 too)
And latest version will let other input no signal too. That's why i'm so care about this. My be it hook the global input?

In game the controller input not same as the interface and new version broke it.

You'll see player can't move and press button b will take the knife.

**Comment by nipkownix** [comment]
Hmm, I wonder if the problem here is caused by the xinput_*.dll wrapper we added recently?

Do you use any xinput_* mods? Maybe a controller emulator or something? x360ce? I'm trying to find what could possibly be causing this.

**Comment by KsaNL** [comment]
Checked, both not
