### ISSUE TITLE
Request: Option to disable QTEs in cutscenes

### ISSUE THREAD

**Issue by cnrm** [nipkownix/re4_tweaks#139]
Resident Evil 4 features numerous quick time events for its real-time cutscenes.

However, when these same cutscenes are seen from the Movie Browser, all QTEs are automatically bypassed and succeeded, with no user input required. Knowing that the game has something in place to skip cutscene QTEs like this, could the same also be applied during gameplay?

NB: The "Movie Browser" versions of most cutscenes have a quick fade to black in place of QTEs. Presentation-wise, this could be considered less desirable while playing.

**Comment by nipkownix** [comment]
@cnrm could you try the test build in #107?

**Comment by cnrm** [comment]
Impressions suggest this method works pretty well. 

But, oddly, with "Skip QTEs" enabled, during gameplay the "Shake off" actions (rapidly shaking the left stick/mouse left and right) were _not_ skipped while everything else seemingly is.

Although less of a pressing issue, the appearance of button prompts when "Skip QTEs" is enabled is peculiar. Inevitably, they often appear and go away in the blink of an eye.

That would be okay, but this looks to be less consistent in cutscenes: while viewing the same scenes multiple times, occasionally one would slip through, while other times none would appear at all—the most ideal (and arguably less distracting) outcome, in my opinion, at least for the cinematics.

Besides that, while both skipping QTEs or holding instead of mashing them are very welcome features for preference and accessibility, admittedly the thought I had was more of a middle ground: QTEs for gameplay, but none for cutscenes.
But I understand if that makes everything more complicated than it's worth, and appreciate the effort for these existing settings all the same; besides the "Shake off" QTEs being ignored, what's here looks functional.

**Comment by nipkownix** [comment]
Thanks for the feedback.

I actually forgot the "shake off" qtes are a thing. I haven't added support for those yet. Thanks for the heads up.

Hiding the prompt is still very inconsistent, noticed it here too. If automatic qtes and skipping qtes proves to be reliable, I'll update the hiding to make it more seamless.

And yeah, making it only affect cutscenes would be complicated.. but after the feature is stable, maybe I can find a way, who knows.
