### ISSUE TITLE
Add option to set a custom refresh rate

### ISSUE THREAD

**Issue by Keith94** [nipkownix/re4_tweaks#15]
The game defaults to 60 Hz even if you're running a modern display with 120 Hz or higher refresh rates. Any idea if you can add a refresh rate Hz option. Thanks

**Comment by nipkownix** [comment]
Ah yeah.. this is an issue..
People also report that the game shows only a black screen when they try to run it on computers that dont't have a 60 Hz monitor attached. Makes no sense.

I've wanted to tackle this issue for a while, but I only have a 60 Hz monitor :/

Maybe @emoose has a 75 Hz monitor?

**Comment by emoose** [comment]
Nah mine is 60Hz too sadly, can overclock it to ~100Hz in NVidia control panel but it still usually still gets seen by things as a 60Hz monitor, I'll try seeing what happens with using it on RE4 soon.

The config.ini does mention the refresh rate on same line as resolution, eg. `resolution 2560 1440 60`, maybe that needs to be changed if your monitor doesn't support 60Hz.

**Comment by cmd777** [comment]
> The config.ini does mention the refresh rate on same line as resolution, eg. resolution 2560 1440 60, maybe that needs to be changed if your monitor doesn't support 60Hz.

I don't believe changing that does anything, always seems to default back to 60 from any number i set it to, for me at least.

[DXVK](https://github.com/doitsujin/dxvk/releases) should fix the screen refresh rate (for me, it fixed crashes in random areas) but, the only downside i found is that the inventory screen slows down.. quite a lot.

Or, there's a framework ([special k](https://special-k.info)) which allows to set higher refresh rates.

**Comment by Keith94** [comment]
If it helps at all, I own 2x144hz so if you want me to test any builds or something, I'm down.

Special K is usually the way to go but the plugin would be an easier way.

**Comment by emoose** [comment]
One way that seems to allow higher framerates is:
- edit winmm.ini, change `IgnoreFPSWarning` to `true`
- edit `Documents\My Games\Capcom\RE4\config.ini`, change `60` in the first line to your refresh rate
- change `variableframerate` to your refresh rate
- change `vsync` to `0`
- save INIs, launch game
- open Cheat Engine, attach to bio4.exe
- `Add Address Manually`, for Address enter `bio4.exe+71D180`, set type as `Double`
- once its added, double click the 0.016666667... value
- open calculator, work out 1 / your refresh rate
- enter the calculator result as the value

Now game should run at your framerate, hopefully without any speed issues - if you dip under the framerate you entered the game will slow down though.
I'm pretty sure there's a way to fix that with some hooks/patches, but haven't been able to get anything fully working yet.

This is for 1.1.0 btw, I'll get the addr for 1.0.6 in a sec.

**Comment by emoose** [comment]
Made a new branch that should have support for higher refresh rates, there's a build linked here: https://github.com/nipkownix/re4_tweaks/pull/25

Please give it a try and let me know how it goes!

**Comment by Keith94** [comment]
Thanks for your work on re4_tweaks. :)

I have tried the new build along with `resolution 1920 1080 144`; however, game is still running at 60 Hz (in fullscreen). Can't really get Special K to work either for some reason...

**Comment by Keith94** [comment]
Fixed
