### ISSUE TITLE
[Feature request] German low-violence version support (& decensor?)

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#153]
### Describe the feature you'd like to see added

Another suggestion from re4hd.com comments: https://www.re4hd.com/?page_id=104#comment-198725

Somehow I totally missed that there was a seperate German version of the game, SteamDB also lists it under the game depots, seems to have its own EXE & data files, no idea what's actually different though since it seems my Steam sub doesn't have access to that depot ;_;

Hopefully the data files match 1.0.6 & it's just some small EXE difference, my guess is the EXE is probably based on 1.0.6 since it was updated same time as main 1.0.6 depot, no telling how close it matches with the normal 1.0.6 EXE though.

In worst case, if the EXE is a lot different to normal 1.0.6 I wonder if we could include something like a delta-patch to overwrite it with the 1.0.6 version in-memory, I guess things like relocations would probably make that a little harder though... but maybe we could patch the on-disk EXE like the 4GB patch trick - assuming it is just the EXE that's different and the data files are the same anyway.

**If any owners of the German version could upload the EXE** & mail me a link it'd be appreciated, my email is on github profile page: https://github.com/emoose

**Comment by emoose** [comment]
Also I've heard JP version also has similar low-violence changes, a JP user also let me know that they seem to have crashes when using re4_tweaks (they aren't using re4hd though, not sure if that makes a difference)

>> > I tried using re4_tweaks, but it crashes every 5 minutes or so when
>> > checking objects.
>> > (X button on controller or E key on keyboard)

Although they later told me about https://otsushiki.hatenablog.com/entry/2016/11/28/200122 which details how to remove LV on JP savegames, and apparently with that mod the crashes went away, pretty interesting, haven't seen that kind of save mod before.

Unfortunately I forgot to ask about crashdump before they managed to fix their issue with that savegame mod, will try seeing if they can recreate the crash for us though.

**Comment by nipkownix** [comment]
Awesome research!

I'll close this since it is implemented in #155. Thanks again!
