### ISSUE TITLE
Message-related crash in JP version

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#156]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Sadly the JP user that reported a crash had it happen again even with the LV change applied to savegame, dump is available here:
[bio4.exe.2472.dmp.7z.zip](https://github.com/nipkownix/re4_tweaks/files/8352836/bio4.exe.2472.dmp.7z.zip)

Like mentioned in the other issue, they aren't using RE4HD, just re4_tweaks 1.7.4.
 
No log unfortunately, but seems to be a divide by zero exception at bio4.exe+316782 (JP 1.0.6) - searched for the code there in our IDB and seems to be inside `messageTrans_draw`, at 0x717722 in the IDB. 

I don't recall any of our patches changing that function, not sure what would cause that really...

E: ahh I forgot 1.7.4 was before the subscreen alloc size changes, I guess that's probably the reason then, will ask them to use the build from #155 instead.

Maybe it's worth making a new release here soon, since AFAIK only RE4HD 1.0.1 includes a build with those changes, people not using RE4HD only have the old 1.7.4...

E: received word that using newer build did get rid of the crashing issues 😅 , there's still the issue of current latest release being stuck with that bug though, maybe worth keeping this issue open until a new release is pushed, in case others also run into the same problem with the current release.

**Comment by emoose** [comment]
Went through the commits since 1.7.4 and made a changelog of them, feel free to make use of it (or add anything I might have forgotten...)
```
- fix for game trying to use display modes under 59Hz, and setting display mode on wrong monitor
- fix key icons not appearing properly for players that don't have the English language pack installed on Windows
- removed SteamID checks on savegames, making saves easier to share (also removed a check that prevented saves being moved between censored/uncensored game)
- added key-combination to temporarily disable mouse turning, allowing quick camera turns (left ALT by default)
- make 4GB patch also update the EXE checksum, making the patch more correct
- adjusted some textboxes for 32:9 resolution users
- fixed issues with invisible inventory items & crashing in CN/JP game versions
- update merchant table to add silencer, allowing it to be sold to merchant
- add patch that allows game to display Leon's mafia outfit in cutscenes
- add patch that can silence the armored Ashley outfit
- add patch that allows cloth physics to act on the tactical vest outfit
- add patch that fixes speed difference of Ashley bust physics
- fixes water not being rendered correctly in ultrawide setups
- improved code for providing input to Dear Imgui
- add RawInput support for mouse aiming
- add option to make sprint act as a toggle instead of needing to hold sprint button down
- allow controller deadzones to be adjusted, and use a more sane default deadzone
- fix backwards-turn speed difference between 30/60FPS
- add options to disable either all QTEs or just mashing QTEs
- make crashdump include game save & automatically create ZIP file
- allow level-of-violence to be changed (allowing censored game to become uncensored, or vice-versa)
- ```

**Comment by nipkownix** [comment]
@emoose sorry for my absence, I got caught up in class. I'll take a look at your email.

Thanks for the changelog, btw! I'll push a new release soon. I was waiting to hear from Albert first, but it looks like he is also a bit caught up in his classes.

**Comment by nipkownix** [comment]
New release is up. 
Also, with the upcoming release of the 1.1 HD Project, hopefuly no one else will run into this issue.
