### ISSUE TITLE
Game window stretches to second monitor in borderless

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#157]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

I'm using [re4_tweaks-violenceLevelOverride.zip](https://github.com/nipkownix/re4_tweaks/files/8330405/re4_tweaks-violenceLevelOverride.zip) that was sent in a [bug report](https://github.com/nipkownix/re4_tweaks/issues/154) and it seems that this version makes it so that game's windowed mode stretches a few pixels onto my second monitor. This doesn't happen when using the public version of 1.7.4 so I can only assume it's unintentional. 

You can see a very thin line to the right of the game's main window. I play in 1920x1080.
![](https://i.imgur.com/ozelvvK.png)

**Comment by linkthehylian** [comment]
I just downloaded the latest release and this issue is still present. Bumping this so that you guys are aware.

Here's a better screenshot as well. You can see where the HUD on the bottom right is cut off a bit because of it.
![img](https://i.imgur.com/AoBAOjC.png)

**Comment by emoose** [comment]
Is this fixed now with the 3e7dd1b07d40ded6036a52ec71eb4ddfc3513db3 changes? (a build with that should be available in artifacts section of https://github.com/nipkownix/re4_tweaks/actions/runs/2182340153)

**Comment by linkthehylian** [comment]
> Is this fixed now with the [3e7dd1b](https://github.com/nipkownix/re4_tweaks/commit/3e7dd1b07d40ded6036a52ec71eb4ddfc3513db3) changes? (a build with that should be available in artifacts section of https://github.com/nipkownix/re4_tweaks/actions/runs/2182340153)

Just tested it and I can confirm that it is! @emoose
