### ISSUE TITLE
Cutscene separate ways no is HD Project

### ISSUE THREAD

**Issue by crowleysbr** [nipkownix/re4_tweaks#164]
Hello. I have a problem with separate ways. All cutscenes is on HD Original. i installed mod 2x, but the problem continue.  Link url: https://i.imgur.com/HnMFkUe.png All files (18 parts) downloaded without any problems.

NVIDIA GTX 1050, i5 3470, 16GB RAM and SSD 1TB.

**Comment by nipkownix** [comment]
It does look like the new cutscenes are being used. There's nothing pixelated and barely any jagged lines.

Bear in mind that those cutscenes will never look perfect, as even though we still have the camera motion data, we don't have the character animations to re-record their movements in high resolution.
