### ISSUE TITLE
Borderless Full Screen is cutting the bottom screen on this new version

### ISSUE THREAD

**Issue by FutonGama** [nipkownix/re4_tweaks#166]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Borderless Full Screen is cutting the bottom screen on this new version

**Comment by linkthehylian** [comment]
Same here, I already made an identical bug report [here](https://github.com/nipkownix/re4_tweaks/issues/157) as well as providing screenshots.

I'm not sure how this is happening since upon opening the log that it generates my resolution is set natively to 1920x1080. I wonder if the picture is being stretched unintentionally somehow?

**Comment by LethalPlacebo** [comment]
I'm also having this issue as of the new version and I don't know if this is related, but I'd like to add: when using the borderless window setting, the Steam overlay and FPS counter are tiny, as though they aren't being scaled properly (I'm playing at 4K). This did not happen on Version 1.7.4

**Comment by emoose** [comment]
Hmm, do any of you use any DPI scaling above 100%? If so maybe disabling scaling on the bio4.exe might help.

- right click bio4.exe -> properties
- choose compatibility tab
- (win11) click `change high DPI settings` button
- tick `override scaling behavior` checkbox, make sure the dropdown is set to Application
- apply & ok everything, then try running the game

**Comment by linkthehylian** [comment]
@emoose I tried what you suggested and nothing changed. 

It's weird too because this didn't happen in 1.7.4 as @LethalPlacebo already stated and I even downgraded to that version for a bit just to make sure.

**Comment by LethalPlacebo** [comment]
@emoose I'm on win10 and override scaling behavior was already ticked. Just to check, I unticked it instead and hilariously the game spanned both my monitors (though it still seemed to be running at 4K?). Switching to fullscreen and then back to windowed fixed it, but the overscan and tiny overlay issues were still present. I have re-enabled override scaling behavior and am just using Fullscreen for now.

**Comment by laymonage** [comment]
Possibly related to https://github.com/nipkownix/re4_tweaks/commit/f8b57ddc6bdff2625c4c69a33ff53683b8057eae?

**Comment by emoose** [comment]
>Possibly related to https://github.com/nipkownix/re4_tweaks/commit/f8b57ddc6bdff2625c4c69a33ff53683b8057eae?

Oh nice find, could have something to do with it. Here's a build with just that commit undone:
[re4_tweaks-1.7.5-noMoveWindowHook.zip](https://github.com/nipkownix/re4_tweaks/files/8487040/re4_tweaks-1.7.5-noMoveWindowHook.zip)

**Comment by linkthehylian** [comment]
@emoose Can confirm that fixed the issue!

**Comment by emoose** [comment]
> @emoose Can confirm that fixed the issue!

Aha glad to hear it!

Well it looks like that commit actually changed two things, hooks MoveWindow and also changes how the SetWindowPos hook is set too, in that build I reverted both of those but guess it might just be one of them that causes it.

Could you check if this build also fixes it too? This still has the MoveWindow hook but keeps the old SetWindowPos stuff instead:
[re4_tweaks-1.7.5-noMoveWindowHook-v2.zip](https://github.com/nipkownix/re4_tweaks/files/8487121/re4_tweaks-1.7.5-noMoveWindowHook-v2.zip)

**Comment by linkthehylian** [comment]
Just tested both. **v2** reproduces the issue. **v2alt** fixes it.

**Comment by emoose** [comment]
Thanks, hmm, so it's definitely the MoveWindow hook responsible then, was kinda hoping it'd be the opposite since I'm not really sure what we needed that hook for though...

I'll try having a closer look at it later on, maybe there's a way we can hook something else for it instead, till then it should be fine to use that **v2alt** build instead though, hopefully it'll help with @LethalPlacebo & @FutonGama as well.

**Comment by laymonage** [comment]
> I'm not really sure what we needed that hook for though...

@emoose It was there to fix the small cropping issue, fix was found here: https://github.com/nipkownix/re4_tweaks/pull/120#issuecomment-1059981678

**Comment by emoose** [comment]
I wonder if it could be some kind of feedback-loop sort of thing, eg. the MoveWindow hook tries setting position to INI `WindowPositionX`, maybe when MoveWindow is called it ends up sending `WM_EXITSIZEMOVE` to the window, making us update INI with a new position, maybe that ends up being inaccurate and shifts things over instead.

Or maybe it's just something silly like MoveWindow needs border sizes removed from positions when in borderless mode, or something like that.

**Comment by nipkownix** [comment]
3e7dd1b07d40ded60 should fix it.

Test build:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8489984/dinput8.zip)


Turns out that MoveWindow call should be used to set up the window size _only_ when we have borders.

**Comment by LethalPlacebo** [comment]
> [3e7dd1b](https://github.com/nipkownix/re4_tweaks/commit/3e7dd1b07d40ded6036a52ec71eb4ddfc3513db3) should fix it.
> 
> Test build: [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8489984/dinput8.zip)
> 
> Turns out that MoveWindow call should be used to set up the window size _only_ when we have borders.

Hey, I haven't had time to play or test anything since the last time I played, but I can confirm that this test build fixes the overscan issue as well as the Steam overlay being tiny. Thank you all!

**Comment by NintendoFan** [comment]
Is this in the live version yet? I had the same issue and used the test build to fix it but now the console output is showing there and I would have it hidden in normal gameplay.
