### ISSUE TITLE
[Feature request] Ashley Suplex glitch restoration

### ISSUE THREAD

**Issue by Zaphero1** [nipkownix/re4_tweaks#173]
### Describe the feature you'd like to see added

There is a glitch that's exclusive to the NTSC Gamecube release where if Ashley hits an enemy with a door she can suplex them; it'd be funny to see that restored in the HD version.
https://www.youtube.com/watch?v=v7IiGY0arV0

**Comment by emoose** [comment]
https://github.com/nipkownix/re4_tweaks/commit/12209b2454855a4fe2b3ce11fd4dc7261d94e7ce

It should be added in the next release :)

You can grab a build of that commit if you want to try it early though, download the file from artifact section of https://github.com/nipkownix/re4_tweaks/actions/runs/2182340153

**Comment by Zaphero1** [comment]
YOOOOOOO, cool! Thank you very much!
