### ISSUE TITLE
effects of treading water

### ISSUE THREAD

**Issue by qingsheng8848** [nipkownix/re4_tweaks#177]
### Describe the feature you'd like to see added

In room r229, we climbed the stairs and stepped on the water, there was no water splash effect under our feet, but in the 2007 version we had the water splash effect, is there a way to fix it?In fact, not only this room, there is no water splash effect when Lyon walks through a puddle, such as r21D or r107

**Comment by qingsheng8848** [comment]
In version 1.0.6, the Bio4.exe + 28199B address is the effect of the R107 stepped on the water, but in R229, this code is not triggered.

**Comment by emoose** [comment]
Seems that 28199B function is `PlWaterProc`, `cPlayer::move` calls it but only if `GetWaterHeight` returns true & cPlayer position is higher than `GetWaterHeight` return value, since you said R229 doesn't trigger that code I guess `GetWaterHeight` has an issue somewhere.

Do you know if GC release has the water effect on R229/R21D/R107?

**Comment by qingsheng8848** [comment]
When you step on the water in the R229 room, there is a watercorn effect? And I didn't, maybe my game file is wrong.

**Comment by emoose** [comment]
I get this effect at least:
![image](https://user-images.githubusercontent.com/1755499/166104983-bad9016e-1fd5-4b73-91b2-f92be9fb8c2b.png)

It's strange though, I use area jump to get to R229, seems lighting changes there depending on where I area jump from

eg. if I load save in village and area jump to R229, the lighting is much different, and I can hardly see the splash at all:
![image](https://user-images.githubusercontent.com/1755499/166105113-e6f8ccb6-d303-480c-aa60-438c3ef4f8e3.png)

**Comment by qingsheng8848** [comment]
![asd](https://user-images.githubusercontent.com/98869895/166109493-60438648-34c5-4aaf-a15e-98b1b360c45b.png)
I found the reason, this is the code I increase the footsteps. When I have been modified, the water will disappear. But in addition, I really don't know how to increase the footsteps of Lyon.

**Comment by emoose** [comment]
Hmm, tried copying those changes but it didn't break the water effect for me, still same as the pic I posted, is there anything else footstep related you changed?

**Comment by qingsheng8848** [comment]
When you copy my modification， have you found that the footsteps increased significantly? I am talking about the waterway above the stairs of the R229, rather than the puddle next to the businessman, I don't have water there, but remove these modifications, the water flows again.

**Comment by emoose** [comment]
Ah yeah you're right, on the waterway above it does break, strange, wonder what causes that.

Yeah the volume of footsteps does increase with that change too.
