### ISSUE TITLE
RE4 Crashing on Launch

### ISSUE THREAD

**Issue by 0x07xxs** [nipkownix/re4_tweaks#181]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

I've been having this issue for a while now I downloaded the tweak files and apparently, it doesn't work even without the files it's the same issue for some reason I've been trying to find someone to help me out, and still no luck. I checked for the game file's integrity Steam says they're fine I'm not sure what the problem is it just opens and doesn't display anything at all it's just a white screen that doesn't even show up the Capcom logo nothing at all it just opens for 2 seconds and it closes. I opened it through my Steam library and it gives me the same issue if anyone can help me I would gladly appreciate it. 

Here's my the file that was in my CrashDumps folder
[bio4.exe.20220505161417.zip](https://github.com/nipkownix/re4_tweaks/files/8636632/bio4.exe.20220505161417.zip)

**Comment by emoose** [comment]
Hmm, could you post your PC specs? The crash seems to be something caused by Intel graphics drivers, do you have any dedicated graphics card in your machine?

**Comment by 0x07xxs** [comment]
> Hmm, could you post your PC specs? The crash seems to be something caused by Intel graphics drivers, do you have any dedicated graphics card in your machine?

CPU - Intel i7 1165G7 2.80ghz 
GPU - Intel(R) Iris(R) Xe Graphics  Driver version: 30.0.101.1338
RAM - 16gb memory brand is unknown

I'm only running intel graphics I don't have another GPU like NVIDIA or AMD GPU not sure what might be the issue or if I need to update any drivers. Hope this helps let me know if you need anything else.

**Comment by 0x07xxs** [comment]
> 

Never mind all I had to do was update my intel GPU drivers it works now thank you
