### ISSUE TITLE
[Feature request] Maintain aspect ratio of pre rendered cutscenes and videos on ultrawide and beyond

### ISSUE THREAD

**Issue by RiasatSalminSami** [nipkownix/re4_tweaks#186]
### Describe the feature you'd like to see added

As the title suggests, there should be an **option** to disable the stretching of pre rendered cutscenes and other videos in ultrawide and wider resolutions. I think the game already letterbox the videos on 16:10 and 4:3 aspect ratios, so it looks fine there.

On the other hand, that is not the case with 21:9, 48:9 [or basically anything wider than 16:9] resolutions. Having proper pillarboxed videos in this case would be nice.

**However**, I emphasize the word "option" because stretching can still be of use. If someone manages to somehow make ultrawide prerendered cutscenes and videos, then this current stretching of the videos will be required. Thus, having option to disable the stretch and maintain aspect ratio should be optional.

**Comment by nipkownix** [comment]
Added the option as part of a complete rework I'm doing on Ultrawide support:

![image](https://user-images.githubusercontent.com/33870163/178786519-70764149-8cf3-4b36-b558-6be7b4c7a01b.png)

Stretching video is now disabled by default, which is the better option IMO.

The "background" color is being set by the game, btw, which is why it isn't black. Doesn't seem like a big deal to me, but if I stumble across what is changing it, I'll change it to black.

**Comment by guifisilva** [comment]
Well I noticed there seems to an issue with this feature when I started playing Separate Ways. Something may have been broken recently, pre-rendered videos are still a bit stretched here. At least they don't have such wide black bars as the above example.

Here's how it looks at 2560x1080 with UltraWideAspectSupport enabled and WITHOUT enabling StretchVideos:
![re4_uw](https://user-images.githubusercontent.com/90845458/182281012-8f355e19-f3bb-4987-ace7-37f5431bd032.jpg)

And here's how it looks at 1920x1080:
![re4_regular](https://user-images.githubusercontent.com/90845458/182281015-a9062cc1-6f7d-4628-80bb-037d441a136f.jpg)

**Comment by nipkownix** [comment]
Hmm, that's with the HD project, correct? I'm thinking Albert may have changed the video's aspect ratio. I tested this feature with the vanilla game and it seemed to work correctly.
I don't have a copy of the HD project at the moment, so this may have to wait a bit.

**Comment by guifisilva** [comment]
Yep, I'm running the HD mod, sorry. Should have clarified.

Take your time, this isn't anything close to game-breaking, really. :)

**Comment by guifisilva** [comment]
And, actually, you may be right. Taking a look at some unused video files, vanilla seems to use a (very low) resolution of 512x336 _and_ a weird pixel aspect ratio of 39:28 (which renders it at 468x336).

Albert remastered his videos to 1920x1080 with a 1:1 aspect ratio.
