### ISSUE TITLE
Audio music & fx volume sliders (Sliders added!)

### ISSUE THREAD

**Issue by mrtree3** [nipkownix/re4_tweaks#199]
### Describe the feature you'd like to see added

Is there any chance of extra audio options please?

Like a volume slider for music & fx that could be added to tweaks?

Love this work, many thanks.

**Comment by linkthehylian** [comment]
Yes, please! This is such a good request and would negate having to adjust its volume manually via volume mixer.

**Comment by emoose** [comment]
Hmm, will try looking into this soon, got some ideas for how to try adding it in.

Unfortunately the whole audio system the game uses is pretty undocumented, I tried finding as much from the GC/PS2 releases as I could, but they did also add a lot of custom stuff for the X360/Windows ver that uses XAudio2 which I'm not really sure about.

One very useful thing I just found out though, seems Viewtiful Joe mostly uses the same audio system, and we have some [pretty detailed symbols](https://github.com/emoose/re4-research/issues/3#issuecomment-1061447972) for that, one of those being this struct:

```
typedef struct %anon154 { /* size 16 */
  sint16 mas_bgm; /* bitsize 16, bitpos 0 */
  sint16 mas_se; /* bitsize 16, bitpos 16 */
  sint16 iss_bgm; /* bitsize 16, bitpos 32 */
  sint16 iss_se; /* bitsize 16, bitpos 48 */
  sint16 str_bgm; /* bitsize 16, bitpos 64 */
  sint16 str_se; /* bitsize 16, bitpos 80 */
  sint16 ssq_bgm; /* bitsize 16, bitpos 96 */
  sint16 ssq_se; /* bitsize 16, bitpos 112 */
} SND_SYS_VOL;
```

From what I can tell, RE4 seems to be using the same thing :)

**Comment by mrtree3** [comment]
Thank you a lot for trying!

I'll have a go with the zip

**Comment by Scoovy** [comment]
> Seem to have something working, if anyone wants to help test here's a build: [dinput8_volumeAdjustment.zip](https://github.com/nipkownix/re4_tweaks/files/8854964/dinput8_volumeAdjustment.zip)
> 
> BGM/SE volume can be adjusted in the re4_tweaks Misc menu, seems to mostly work fine, not totally sure if all sounds will be affected by it though - would be interested if anyone finds something that doesn't work with it.
> 
> (like post above shows there's also 3 different values for both BGM/SE as well, not completely sure I'm changing all the correct ones, so if you notice some sound effect changing when you adjust BGM, or vice-versa, let me know)
> 
> Looks like changing SE volume normally takes effect instantly, but BGMs usually require reload first, maybe can figure out a way to change the BGM volume directly somewhere...

the inventory sounds seem way lower than sounds for example enemies when using the effect slider, i have the slider on max and the inventory is very hard to hear

https://user-images.githubusercontent.com/103059961/172465069-e3940ca0-2c92-4da2-9511-581bbe09dc81.mp4

**Comment by emoose** [comment]
Here's another build which tracks bgm/se seperately, hopefully should work better now: [dinput8_volumeAdjustment-v2.zip](https://github.com/nipkownix/re4_tweaks/files/8856079/dinput8_volumeAdjustment-v2.zip)

**Comment by linkthehylian** [comment]
That new build works perfectly, but I noticed that the changes don't seem to apply during cutscenes. I'm wondering if it could be applied for those as well.

**Comment by linkthehylian** [comment]
Awesome! Thank you.

Another question, are the sound effects also tied to character speech? I was gonna suggest another possible slider for that as well so that we have full customization over everything in-game that has sound.

**Comment by emoose** [comment]
Looks like speech might be handled by the `str_se` value, at least during cutscenes in movie viewer, unfortunately it looks like cutscene BGM is also being handled by `str_se` >.>

Not totally sure whether the BGM/SE values I'm changing are actually for BGM/SE or not, looks like BGM slider does affect the menu BGMs at least, don't really know what levels actually have background music playing though.

**Comment by linkthehylian** [comment]
Ah, so it looks like they are tied together. I kinda expected that given how old the game is. 😄 

> don't really know what levels actually have background music playing to check those though

I did the village raid as a test since that part of the game always has music and it seems to work just fine!

**Comment by mrtree3** [comment]
Hello, will version 3 be put into re4 tweaks officially or is there more adjustments to make?

I run ver 3 & in the top right corner is an extra re4tweaks menu activated by F2, How do i hide it? Pressing F2 doesn't hide it in my game?

**Comment by emoose** [comment]
Should be merged soon hopefully, there's a PR for it at https://github.com/nipkownix/re4_tweaks/pull/200 with some more fixes included too (eg. letting BGM volume be changed as it plays)

The build artifact from https://github.com/nipkownix/re4_tweaks/actions/runs/2464507044 should have that menu disabled AFAIK. (use DLL from the Release folder)
