### ISSUE TITLE
Saving from cfgMenu causes lag/desync

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#209]
Odd thing I just noticed, when you press save on the cfgMenu it seems to hang/stall for a second or so, if you press the Save button a couple times during a cutscene it seems to cause things to desync too :/

Not sure if it's always done this or if something we added recently started causing it, I guess it's probably something to do with the way DX9 is hooked for Imgui to render, maybe there's some way to write the config file from a different thread instead.

E: hm, seems lag goes away by updating `Settings::WriteSettings()` and making all the `iniReader.WriteFloat` etc have `useparser` as true, guess lag was probably caused by the `WritePrivateProfileStringA` func that it uses when `useparser` isn't set.

Unfortunately looks like that removes all comments from the INI though...

**Comment by nipkownix** [comment]
Using `CreateThreadAutoClose` would probably solve this issue, I imagine? Can't really test right now tho.

**Comment by emoose** [comment]
Ah nice that seems to fix it, will make a PR for it shortly
