### ISSUE TITLE
[Feature Request] Rifle Feedback

### ISSUE THREAD

**Issue by juuuulian-s** [nipkownix/re4_tweaks#219]
### Describe the feature you'd like to see added

would it be possible to add some kind of feedback on scoped rifle shots? there is absolutely zero recoil or screenshake or even scope shake on shots with either of the two rifles, and this makes them feel rather odd when contrasted to the rest of the game's arsenal. nothing too fancy, some mild screen and overlay shake would do the trick i feel

**Comment by Mister-Curious** [comment]
I have a theory that could make this work. We could write something that triggers the screen shake effect each time the trigger is pulled. I have this effect saved (I use it in a custom ETM when it explodes). The effect would need to be loaded from somewhere though, but its small enough in bytes to include in the DLL. 

We might be able to save the effect in the weapon itself, and maybe even trigger it without code, but only if there are other effects that happen when the trigger is pulled.

**Comment by Mister-Curious** [comment]
I have an example of what this could look like:

https://youtu.be/DNlYDxwHJJQ

The effect you see is the screen slightly shaking when I shoot the green tank (ignore the rest of the effects that happen). It's a slight 'screen shake' effect that can be edited to be more intense if needed. The effect here is actually inside the ETM EFF file for the green tank, and is only activated once it breaks (I took this effect from the exploding red barrels). 

So my idea was to somehow put this effect in the riffle EFF, but it seems the effects in the wep09_04.EFF file are not activated for some reason, and even if they were, I am still not sure they would happen just when we pull the trigger. I was a little sad to see these effects not working in game. 

So this brings me to my conclusion. This effect can be used, but it will need to be stored somewhere (like in the DLL or extrernal file), and will need a script to be triggered. Im happy to do testing with anyone that wants to try this out.

**Comment by juuuulian-s** [comment]
this sounds promising! looking forward to seeing what can be done with it

**Comment by pas-de-2** [comment]
Oh I really like this idea. I just added a call to QuakeExec in wep09_r3_fire00:
[2022-12-06 15-06-19.webm](https://user-images.githubusercontent.com/116680301/206012586-3fbd7211-b67e-4839-98f8-46a2296f08c9.webm)

Here's a test build with a slider for configuring the strength of the recoil (Misc tab). I like 40 for now, but let me know what you think feels best.
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10170184/dinput8.zip)
