### ISSUE TITLE
Costume Override for Ada Requires Restart from Checkpoint

### ISSUE THREAD

**Issue by LethalPlacebo** [nipkownix/re4_tweaks#225]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Costume Override for Ada does work (I have it set to "Spy," Leon to "Jacket," Ashley to "Normal") but requires you to Restart from Checkpoint for it to actually activate, even if you have previously saved that setting. So far I know that the "Restart from Checkpoint" method works for Separate Ways, but I'm not sure if it works in the main campaign yet. If you use the Movie Browser in the game for the main campaign, Ada's outfit is still wrong.

[dinput8.log](https://github.com/nipkownix/re4_tweaks/files/8945147/dinput8.log)

**Comment by nipkownix** [comment]
Oh, interesting. I've only tested using Restart to checkpoint, so I didn't notice that.

I'll take a look. Thanks.

**Comment by nipkownix** [comment]
Should be fixed now.

Test build should be here soon:
https://github.com/nipkownix/re4_tweaks/actions/runs/2590839383

**Comment by LethalPlacebo** [comment]
Tested it out, can confirm that the costume now changes properly in Assignment Ada, Separate Ways, and Mercenaries! There are only 2 spots I found where it doesn't change: the intro cutscene to Assignment Ada and all of the cutscenes in Leon's campaign, but I assume these cannot be changed. Great work!
