### ISSUE TITLE
[Feature request] Cursor lock

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#227]
Resident Evil 4's cursor has a horrible tendency to go onto my second monitor whenever I Alt+Tab. It also prevents the game's cursor from showing. If I wanted modify settings in the re4_tweaks GUI, I wouldn't be able to because the cursor isn't there.

The only way to "fix" this issue currently is to just restart the game. But even when doing that, it happens again.

**Comment by emoose** [comment]
Would also be nice if we can toggle the cursor hiding code too (without breaking the games mouse code), when debugging game in windowed mode alt-tabbing doesn't always make the cursor show up again - usually have to force it by using `CTRL+ALT+DEL` twice (useful Windows hotkey for forcing cursor to reappear)

Maybe wouldn't be too useful for players, but a toggle for devs (or `IsDebuggerAttached()` check) would probably make things a lot easier for code modders.

**Comment by laymonage** [comment]
I haven't got time to test it, but here's the link to the build with that commit for easier access if anyone wants to test it:

https://github.com/nipkownix/re4_tweaks/suites/7127864152/artifacts/282913147

**Comment by LethalPlacebo** [comment]
> I haven't got time to test it, but here's the link to the build with that commit for easier access if anyone wants to test it:
> 
> https://github.com/nipkownix/re4_tweaks/suites/7127864152/artifacts/282913147

Can confirm this fixes the issue for me as well. I can Alt + Tab out of the game as many times as I want and my mouse cursor appears and is usable both when using a different program and when navigating the game. No more need to right-click to get it to appear again.

**Comment by nipkownix** [comment]
Nice!

@emoose, this should fix the stuff you mentioned as well.
