### ISSUE TITLE
RGB effect for Laser color

### ISSUE THREAD

**Issue by Scoovy** [nipkownix/re4_tweaks#229]
### Describe the feature you'd like to see added

with the new Laser color swap in the tweaks version i think a fun neat option would be a Rainbow/RGB toggle that goes through all colors while playing, this isnt needed as a fix but would be a fun option

**Comment by nipkownix** [comment]
Implemented in c87823788558d5f:

https://user-images.githubusercontent.com/33870163/176194951-da536285-feaa-4e2f-b949-6263e1e1659e.mp4

I had the same idea when I was implementing the color override option, actually :p
Let me know if that works for you.

**Comment by RiasatSalminSami** [comment]
Gamer moment

**Comment by LethalPlacebo** [comment]
Can confirm that this looks great! Only issue I noticed is that there are these teeny tiny breaks in the laser, I think maybe 2 or 3, but they're pretty hard to notice.

**Comment by nipkownix** [comment]
> Only issue I noticed is that there are these teeny tiny breaks in the laser

That's an issue with the vanilla game, sadly. I'm just reusing QLOC's original RGB laser implementation, which has its flaws :/

**Comment by LethalPlacebo** [comment]
> > Only issue I noticed is that there are these teeny tiny breaks in the laser
> 
> That's an issue with the vanilla game, sadly. I'm just reusing QLOC's original RGB laser implementation, which has its flaws :/
> 
> Edit: To elaborate a bit more, there are three functions related to drawing the laser line: `EspDrawLaserLine`, which has hardcoded colors + alpha, `EspDrawLaserLine2` which accepts Red, Blue, Green and Alpha (although the Alpha one doesn't seem to work at all), and `EspDrawLaserLine3` which seems to be unused/not working(?).
> 
> The game normally uses `EspDrawLaserLine` for the laser sights. When you set a custom RGB value, either by using re4_tweaks or the game's vanilla config.ini, the game instead uses `EspDrawLaserLine2`. The problems is in this `EspDrawLaserLine2` function. I'm not sure if QLOC actually coded this one from scratch or reused it from somewhere else, but not only it looks different from the original `EspDrawLaserLine`, it is also slightly broken due to the alpha value being ignored. Would be nice if we could make `EspDrawLaserLine` use custom RGBA values instead, but I haven't had any luck with that. Maybe @emoose could figure something out? Meh.

Thanks for the insight! I did learn a bit of this when trying to tweak the laser using the ini file before RE4 Tweaks. I just wanted to mention something: you said you're resuing QLOC's original RGB laser implementation. Did they rewrite it or something? If I fallback to using the original laser or if I edit the ini myself and don't use the RE4 Tweaks option, I don't see the breaks in the laser.

**Comment by nipkownix** [comment]
Hmm, could you share your custom config.ini laser values that don't have seams in the laser? They seem to happen here regardless of what I use.

**Comment by LethalPlacebo** [comment]
> Hmm, could you share your custom config.ini laser values that don't have seams in the laser? They seem to happen here regardless of what I use.

laserR 175
laserG 0
laserB 255
laserA 255

These are the settings I use, and I play at 4K with no anti-aliasing enabled. But I have something more wild to report: the issue is fixed when playing in Fullscreen or RE4Tweak's Borderless Window mode. For some reason the breaks in the laser _only_ appear when using standard window mode. For me it's not a big deal because I always play in Borderless, but I thought it was weird nonetheless.

**Comment by nipkownix** [comment]
We're talking about this type of thing, right?

![image](https://user-images.githubusercontent.com/33870163/176821222-bc285d47-0cdb-455d-9751-f77290281bdb.png)

This image is from the vanilla game + the settings you posted.  Seems to happen here regardless of my settings.

**Comment by LethalPlacebo** [comment]
Yup, that's exactly what I'm talking about. This is really weird because I even tested it in multiple locations too, doesn't break for me unless in regular window mode. I'll try and get back to you if I think of anything else.
