### ISSUE TITLE
Ashley & Enemy Pathfinding Slightly Broken

### ISSUE THREAD

**Issue by LethalPlacebo** [nipkownix/re4_tweaks#230]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

There are some areas of the game where, after telling Ashley to wait or hide in a dumpster, she will get stuck on geometry when called from certain locations. I've found 2 locations where this happens, though there may be more: immediately after finishing the cabin section and at the beginning of choosing the "right path" after the cabin. 

After finishing the cabin section, if you tell Ashley to wait inside then stand outside some of the window sills, then call her, she will get stuck running against the window sill indefinitely, never climbing over it until you tell her to stop or go inside the cabin yourself.

In the "right path" after the cabin section, telling her to wait in the dumpster and then climbing up to the big walkway (or even jumping down into the arena in the middle of the walkway) and then calling Ashley will result in her getting stuck against the wall.

Later in this same section, one of the enemies waiting on the right side balcony near the end of the area has a tendency to get stuck walking into the railing indefinitely until you shoot him. Some images:

https://imgur.com/a/gSh82Ec

I've done dozens of playthroughs of RE4 on Steam before RE4 Tweaks and stuff like this never happened.

**Comment by emoose** [comment]
Ah, probably something up with `EnableFastMath` again... could you try disabling that in the re4_tweaks menu & restart game, and then see if things have improved at all?

Maybe will have to scale that fix back and make it only affect the cloth functions that it was meant for.

**Comment by mrtree3** [comment]
I've seen this consistently happen at the start of the castle with 2 monks are supposed to come after you when you dodge the catapults. The 1st two monks are no problem, it's the 2nd set of monks that bug out. They get stuck, one on the crates near where rifle ammo lays. The 2nd monk is stuck on the spiral steps leading to catapults. Ashley also gets stuck in the village section during hide in dumpster areas. In the area where you make a left or right path after luis cabin assault. If you choose left she gets stuck after exiting dumpster keeps running to a wall in a corner unless i approach her.

**Comment by LethalPlacebo** [comment]
@SPARDA-REQUIEM @mrtree3 Yeah, you both just described the exact thing I described in the OP haha.

@emoose Gotcha, I will disable FastMath and do these sections again. Unfortunately I didn't make a save there, but I can probably use the debug menu to get back there. Will let you know how it goes.

**Comment by LethalPlacebo** [comment]
> Ah, probably something up with `EnableFastMath` again... could you try disabling that in the re4_tweaks menu & restart game, and then see if things have improved at all?
> 
> Maybe will have to scale that fix back and make it only affect the cloth functions that it was meant for.

Got some time to test this today. Did it with Fast Math on first to replicate the issue, then made sure to disable Fast Math and restart the game. The issue with Ashley getting stuck on the wall still happens. I haven't tested the cabin yet, but I'm willing to bet Ashley getting stuck on the window sill still happens. I did notice that the Ganado didn't get stuck on the rail anymore regardless of if Fast Math was on or off, but given that other people here have reported issues with other Ganado in the game, I'm willing to bet the problem still persists in some way.

**Comment by albertre4HD** [comment]
The Ashley problem in the Bella Sisters path is caused by the HD project. So that one is 100% my fault.
The 2 zealots in the castle getting stuck in the steps was probably caused by some collision map edits I did, but whatever it caused that, is now fixed too ;D

**Comment by LethalPlacebo** [comment]
> The Ashley problem in the Bella Sisters path is caused by the HD project. So that one is 100% my fault. The 2 zealots in the castle getting stuck in the steps was probably caused by some collision map edits I did, but whatever it caused that, is now fixed too ;D

Hi Albert! I thought this might be the case because of the new room that was added, but don't know enough about the topic so didn't want to bring it up haha. 

Did you also edit the cabin survival map? Ashley has some trouble here with the window sill if you tell her to wait in the cabin, then hop out of the window and tell her to follow, but she's much better about wriggling free from this problem:

https://imgur.com/a/G9oEf8b

Also how did you fix the zealots getting stuck, out of curiosity?

**Comment by albertre4HD** [comment]
Oops! No, I didn't edit that room's path or collision data
But I've just checked it and the problem is there in the original. It seems the collision data and the path data don't match. I'll fix it ;D

About the zealots, I'm not 100% sure about the reason, but I just repacked the collision data and that fixed the problem. I remember that was one of the first areas I adjusted the collision data, and probably I used an older and non-final collision data repacker tool, or I simply did something wrong...

**Comment by LethalPlacebo** [comment]
> Oops! No, I didn't edit that room's path or collision data But I've just checked it and the problem is there in the original. It seems the collision data and the path data don't match. I'll fix it ;D
> 
> About the zealots, I'm not 100% sure about the reason, but I just repacked the collision data and that fixed the problem. I remember that was one of the first areas I adjusted the collision data, and probably I used an older and non-final collision data repacker tool, or I simply did something wrong...

I see! I didn't realize the problem was there in the original, my bad.

Understood, glad the problem was fixed without too much hassle!

**Comment by LethalPlacebo** [comment]
> Ah, so it was something related to the HD project? I also was betting on it being a MathReimpl problem. I'm glad it was fixed.
> 
> I believe we can close this?

Yup, closing! Sorry for the false alarm.

**Comment by nipkownix** [comment]
No worries! I'm glad everything is fine.
