### ISSUE TITLE
Let the old computer play the HD version

### ISSUE THREAD

**Issue by qingsheng8848** [nipkownix/re4_tweaks#239]
### Describe the feature you'd like to see added

I don't know if it is possible.  Is it possible to disable some features to reduce CPU consumption?  For example, we can make the game prohibit the rendering of ambient light, prohibit the game from using reflective effects, and so on.  In my opinion, this game is really demanding on the CPU

**Comment by Scoovy** [comment]
it would be good to have an option if possible to change demand on the CPU over to the GPU but im not sure if the game will be able to handle that stuff
