### ISSUE TITLE
[Feature Request] Reload with single button instead of need to aim then reload

### ISSUE THREAD

**Issue by JagBone** [nipkownix/re4_tweaks#248]
As of right now, to reload players will need to aim and then press the reload button to reload their weapon. I hope to have a feature where the use just press the reload button and the reload animation occurs without the need to aim.

**Comment by nipkownix** [comment]
I believe I know how to do it for Keyboard+Mouse, but AFAIK, the controller's reload button is the same as the run button, isn't it? We'd have to change it, in that case. Hm.

**Comment by Mister-Curious** [comment]
> I believe I know how to do it for Keyboard+Mouse, but AFAIK, the controller's reload button is the same as the run button, isn't it? We'd have to change it, in that case. Hm.
> 
> Edit: Just tested it and it works nicely with KB+M, but the controller does use the same button. Guess I'll try to change controller reload to the shoot button, which is.. uh.. square, apparently? This game's control are weird.

It might be worth having a look at the input.ini to see if RUN and RELOAD use different slots. Most people don't know that we can reassign buttons for controllers for single events this way.

**Comment by nipkownix** [comment]
Could you guys test 576e777?

There should be test builds here soon:
https://github.com/nipkownix/re4_tweaks/actions/runs/2618195586

**Comment by linkthehylian** [comment]
> Could you guys test [576e777](https://github.com/nipkownix/re4_tweaks/commit/576e777777f0eb8359fa756a05ca2ca173f583ac)?
> 
> There should be test builds here soon: https://github.com/nipkownix/re4_tweaks/actions/runs/2618195586

Works like a charm! Thank you dude! 😄

**Comment by JagBone** [comment]
I encountered a weird bug. I'm on the latest version and patch. 

When I press the reload button and then quickly hold the Aim button as the reload animation is playing, I would no longer able to aim the weapon and it would only face forward. 

I could still move the camera but Leon will just remain aiming forward. Then, if I release the Aim button, and aim again, everything is working fine. 

This bug can be seen when you reload then quickly hold the aim button as the reload animation started is occurring. I am using default keys and on MouseKeyboard. Not sure if this bug is present on controller as well. 

See video attached for reference.

https://user-images.githubusercontent.com/50961119/184083210-1acf3218-e79e-4d87-9b03-f3d14daac27a.mp4

**Comment by nipkownix** [comment]
> When I press the reload button and then quickly hold the Aim button as the reload animation is playing, I would no longer able to aim the weapon and it would only face forward.

Fixed, but have yet to release a new version. Should do it soon, though.
