### ISSUE TITLE
Free Camera 

### ISSUE THREAD

**Issue by DarkxVoid-loop** [nipkownix/re4_tweaks#254]
### Describe the feature you'd like to see added

It would be interesting to already have the Free camera option in the Re4 tweaks tool, because the cheet engine is a little complex and also causes problems with the computer

**Comment by mrtree3** [comment]
Agreed, i remember using a camera tool mod with invincibility as an option !

If re4 tweaks could provide a camera option & maybe invincibility too? I hope it's ok to ask & thanks for all this work.

**Comment by FutonGama** [comment]
Perfect

**Comment by nipkownix** [comment]
Free camera (and invincibility) are now in the new "trainer" tab, so I'll close this.
