### ISSUE TITLE
Memory allocation is crashing 

### ISSUE THREAD

**Issue by DarkxVoid-loop** [nipkownix/re4_tweaks#272]
### Validation

- [ ] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [ ] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

When you select the option to allocate memory in Re4 tweaks the game doesn't even start and crashes if you open the inventory with SS from HD Project 1.0

**Comment by emoose** [comment]
Can you try getting a crash dump?

>If your issue is crashing related: please try creating a CrashDumps folder next to your bio4.exe file, and try getting the crash to happen again - after that you should hopefully have a ZIP file inside the CrashDumps folder, please attach that ZIP with your post!

**Comment by DarkxVoid-loop** [comment]
what else happens is to hang on Load to enter r100, the biggest problem of memory allocation happens on r100

**Comment by FutonGama** [comment]
> 
[bio4.exe.20220715180744.zip](https://github.com/nipkownix/re4_tweaks/files/9124069/bio4.exe.20220715180744.zip)

**Comment by emoose** [comment]
Hmm, any chance you could try using 1.1.0 EXE and see if it crashes there? (with crash log too?)

I posted a patch at https://github.com/emoose/re4-research/issues/5 that can change 1.0.6 to 1.1.0, you need to restore original 1.0.6 EXE first though.

**Comment by FutonGama** [comment]
> Hmm, any chance you could try using 1.1.0 EXE and see if it crashes there? (with crash log too?)
> 
> I posted a patch at [emoose/re4-research#5](https://github.com/emoose/re4-research/issues/5) that can change 1.0.6 to 1.1.0, you need to restore original 1.0.6 EXE first though.

oh ok

**Comment by Mister-Curious** [comment]
My god, when are you guys going to give up on r100? This is **NOT** the room to be testing memory allocations on. I have explained probably 30 times that this room is unique in how it handles enemies, stage models and other files and should not be used for tests. There are dozens and dozens of other rooms to mod that don't have these issues, yet people for some reason want fixes to a room that is simply a mess on the backend. 

What you guys are asking is for a custom fix to a problem that will not occur if you aren't modding this room.  Why not allow the RE4Tweaks guys time to work on the things that can't be avoided, and the things we really need?

I see a lot of requests too for things that can already be done with existing tools, but people say "it's too complicated, or too time consuming". Please consider that writing code is is complicated and time consuming too.

**Comment by FutonGama** [comment]
> 

I realised the other maps is happening the same thing

**Comment by DarkxVoid-loop** [comment]
@Mister-Curious our mods are intended for people who play the normal game if you take a classic map they already detonate the mod, we need r100

**Comment by nipkownix** [comment]
I'd like to remind you that re4_tweaks is about _enhancing_ the original game experience, not providing a tool/framework for modders to create custom experiences. We'll do what we can do accommodate everything, as long as it is feasible for us/this project.

**Comment by kTeo-0** [comment]
> I'd like to remind you that re4_tweaks is about _enhancing_ the original game experience, not providing a tool/framework for modders to create custom experiences. We'll do what we can do accommodate everything, as long as it is feasible for us/this project.

I understand. Your dll is already very valuable as it is, it is also awesome for enhancing the gameplay with other mods installed. We'll stop requesting those things then and focus purely on requests for enhancing the original experience, like framerate fixes and such.

I gotta ask though, would it be possible to at least finish the size/speed by .esl? this is crucial for many things in our mods, and not having this nearly finished feature would be a shame.

**Comment by FutonGama** [comment]
> I'd like to remind you that re4_tweaks is about _enhancing_ the original game experience, not providing a tool/framework for modders to create custom experiences. We'll do what we can do accommodate everything, as long as it is feasible for us/this project.

Nipkown desculpa te responder em portugues mas é porque fica mais facil de eu explicar. Ontem o Darth tinha comentado sobre a allocação de memoria e eu falei do r100 e tals, mas realmente cara o alloc de memoria pro inventario do re4 tweaks estava funcionando de uma maneira estranha, uns meses atrás o qingsheng tinha isso incluso na DLL dele e funcionava deboas, depois que ele viu que foi incluso no re4 tweaks ele tirou essa função da dll, em seguida começou a ter problemas com a pasta SS do HD Project, ela parou de funcionar, então ativei o Alloc do RE4 Tweaks, porém, com essa função ela até arruma a maleta mas por algum motivo prejudicava alguns spawns de inimigos nos mods, ok, sei que não é para mods a DLL e entendi isso, porém eu vim pedindo durante alguns meses pro qingsheng voltar com essa opção pra não precisarmos usar a re4 tweaks ja que n estava funcionando pros mods, mas, o qingsheng é Chines e ele tem uma dificuldade imensa de entender o que estamos querendo dizer até mesmo se for algo super simples, hoje ele incluiu de volta a mesma função do re4 tweaks na DLL dele e está funcionando tudo conforme a ideia, aumentar a memoria da interface da maleta, os spawns de inimigos tb 100% ok, por isso q a gente reportou o problema e pareceu que era só pra mods, mas no fim acredito q é um problema mesmo mas eu sou leigo nesse assunto me desculpa, então n sei se é o metodo do qingsheng q é diferente ou é algum problema na funcionalidade, por isso reportei, porém o Curios ele fica irritado quando citamos o r100(que é o primeiro mapa do jogo) porque esse mapa é complicado de editar e no mod dele ele skipou, ai ele achou q tudo q pedimos foi só pros mods mas não, eu to vendo todas funções do tweaks e to testando as coisas que estão sendo adicionadas des do começo, ontem eu nem dormi direito porque pareceu que tavamos enchendo o saco d+ e que era incoveniencia até porque eu me coloco no lugar de vc e o Emoose e é um bixo de 7 cabeças consertar esse jogo. Eu n sei e é mesmo um problema ou a locação dele é algo diferente da de vcs ja q o intuito é focar no jogo base. Vlw pela atenção e desculpa o comentario em portugues, caso queira dps de ler eu apago, é que meu inglês é zoado, uso tradutor sempre pra confirmar o q to falando e o inglês do Darth é bizarro. Vlws pela atenção.
