### ISSUE TITLE
Framerate lag spike

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#274]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Right after fighting Del Lago, Leon ends up going unconscious inside of a house. After that cutscene and the radio interaction with Hunnigan ends, if the player makes a wide turn with the camera to get a better view of what's inside. It creates a very noticeable lag spike that lasts for about a second before the framerate returns to normal. 

I was forced to use the debug menu to reload the level in order to showcase it happening. It doesn't seem to happen if the level is loaded through a save.

https://user-images.githubusercontent.com/20933012/179467545-95696640-6050-47be-a6b9-82e1c168e067.mp4

I'm using the JP 1.0.6 executable for this recording. But I can confirm that it also happens with 1.1.0 as well.

**Comment by emoose** [comment]
Any chance you could check whether `PrecacheModels` makes any difference there? That seems like the same kind of lag-spike that option was added for, didn't think there was anywhere in vanilla/HDProject that could trigger it though.

**Comment by linkthehylian** [comment]
> Any chance you could check whether `PrecacheModels` makes any difference there? That seems like the same kind of lag-spike that option was added for, didn't think there was anywhere in vanilla/HDProject that could trigger it though.

Yep, that fixed it. Thank you! 😄 

I wish I tried that before submitting this issue lmao

**Comment by emoose** [comment]
>I wish I tried that before submitting this issue lmao

No worries, glad to learn that there is somewhere that needs that fix besides heavily modded areas 😅 

Now I guess we need to decide whether this should be on by default or not, looks like the footage is with HDProject installed, so maybe this is worth adding into HDProject's override INI.
Would probably need a lot of testing to make sure nothing breaks with it though... think a new HDProject is due soon already too, but maybe it could be added into the next one after that.
