### ISSUE TITLE
[Feature] Add Quit to Desktop in the Pause Menu

### ISSUE THREAD

**Issue by JagBone** [nipkownix/re4_tweaks#276]
### Describe the feature you'd like to see added

It would be great to add a Quit to Desktop option in the Pause Menu instead of the need to click Retry or Load/Return to Main Menu and then pressing Quit to close the game. It is especially cumbersome when you play the other modes where you have to click out of Extras and then you can close the game. Sure I can use Alt+F4 for a quick close but that just feels too forceful.

**Comment by FutonGama** [comment]
This can make you quit the game unintentionally, i don't think is a good idea.

**Comment by laymonage** [comment]
I think it is a good idea for an optional feature.

**Comment by Scoovy** [comment]
adding this into the tweaks menu would be better so you would have to open it and then press the Quit button so it wont accidentally happen

**Comment by JagBone** [comment]
Just to clarify my request, I'm not intending it to instantly close the game. I was thinking that upon clicking that option, a YES/NO will appear below to confirm. Preventing players from accidentally closing the game. The YES/NO option is already there in the game. I'm not sure if we can use it for anything else. 

Let's be real here, it is cumbersome to close the game. There several menus to click through to just close the game. If this feature request cannot be done, it's fine. I was thinking of ways to improve the quality of life in the game.

**Comment by kTeo-0** [comment]
dude, press alt+f4, i can't see a good reason to add this unless you want to save .2 seconds of your time ._.

**Comment by JagBone** [comment]
Sorry to had bother you.
