### ISSUE TITLE
Sprinting automatically reloads for no reason

### ISSUE THREAD

**Issue by Glitch5970** [nipkownix/re4_tweaks#277]
Using the latest version "Ver 1.7.7" when I press the sprint button (could be any key) my character starts reloading

I tried turning off and on a lot of options especially newer ones in the re4_tweaks menu but nothing seems to fix it, on older re4_tweaks / any other I don't get this issue

Once the reloading is complete I can start sprinting just fine

**Comment by laymonage** [comment]
Likely related to https://github.com/nipkownix/re4_tweaks/issues/248 and https://github.com/nipkownix/re4_tweaks/commit/576e777777f0eb8359fa756a05ca2ca173f583ac.

There is a new `AllowReloadWithoutAiming` option in the KB+M and Controller sections.

Are you using a controller? The warning here might explain it:

https://github.com/nipkownix/re4_tweaks/blob/576e777777f0eb8359fa756a05ca2ca173f583ac/settings/settings_string.h#L134-L140

**Comment by nipkownix** [comment]
If you are using a controller, what kind of controller is it? Dinput or Xinput? Everything seems to work fine on Xinput here.

**Comment by Glitch5970** [comment]
I also tried to rebind the sprint action to other keys and it didn't fix it, it reloads on the rebinded sprint keys aswell

**Comment by Glitch5970** [comment]
I assume my keyboard is being used like it's a controller maybe?

**Comment by nipkownix** [comment]
Hmm, the 1.0.1 HD project doesn't have the latest re4_tweaks, does it? What version shows up when you press F1?

Would be nice to take a better look at this.

**Comment by Glitch5970** [comment]
> QLOC geniuses made the key bind options screen bind the "run" action to _both_ `KEY_B` and `KEY_RUN`, but their own default config doesn't bind KEY_B to anything. This makes my new code mistake this for a controller button press. Grr.
> 
> Thanks for bringing that up to my attention, should be a simple workaround.
> 
> Edit: @Glitch5970 Build with fix will be here soon: https://github.com/nipkownix/re4_tweaks/actions/runs/2692622462
> 
> Thanks again.

Yup I edit all my keybinds usually, probably why

Also I didn't pay attention my bad, I just installed 1.0.1 and replaced the RE4_tweaks with the latest one

But no problem!

Off topic but it would be amazing if one day there was an Emoose's unlimited framerate version with the latest re4_tweaks features, since the recent versions makes aiming with a mouse feel more native/raw and I love it!

Thanks a lot
