### ISSUE TITLE
[Feature Request] Choose Leon and Ashley costume separately instead as a set

### ISSUE THREAD

**Issue by JagBone** [nipkownix/re4_tweaks#286]
### Describe the feature you'd like to see added

The idea of this feature is that player can choose RPD for Leon while choosing Knight for Ashley and vice-versa. I am not sure whether this is possible. I was thinking maybe have an option(s) in the RE4 Tweaks menu to select your own individual costumes for the characters. Hence, when the player go to New Game+ and select Costume 1 or Costume 2, it will just use the costumes selected in the RE4 Tweak Menu.

**Comment by nipkownix** [comment]
That is already a feature in recent versions. It is called ``OverrideCostumes``, in the MISC tab/section.

**Comment by JagBone** [comment]
Oh nice! I will take a look. Thanks.
