### ISSUE TITLE
roominfo.dat override

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#288]
### Describe the feature you'd like to see added

While editing the **roominfo.dat** file (for the purpose of changing the room coordinates for debug teleports), I noticed that my changes were not taking place in game. When conferring with another modder I was told that RE4Tweaks uses its own hardcoded points to make it work with the activated Debug menus. 

So I am wondering at this point if it is possible to set it to read from file, instead of internally? Im asking this because my mod has over 70 rooms, and as a courtesy to players I would like to make it so that they could still Debug teleport without being spawned outside of the areas of my rooms. 

Before knowing that it was possible to edit these waypoints, I made elaborate workarounds using AEV events to teleport players to the right locations, but there are a couple of instances where this method becomes problematic as the default waypoints are somewhere within the room (just not at the area I want). 

If it is  indeed possible to make the debug teleport locations read from file, and you are inclined to make this a toggleable feature, I would be really pleased. As a side note, being able to edit the names would be a bonus. 

Thank you !

**Comment by emoose** [comment]
https://github.com/nipkownix/re4_tweaks/blob/ff1eaba80df46a185b27af665090dfdaf5137e46/dllmain/ToolMenu.cpp#L229 :smile:

**Comment by Mister-Curious** [comment]
Thanks for the speedy reply. I am not sure how I would still go about editing the waypoints though. I just don't understand how to edit the waypoint data if the RE4Tweaks DLL is overriding it.

**Comment by emoose** [comment]
If your edited roominfo.dat is called roominfo_new.dat then it'll be used instead of our data, it worked last time I tried it IIRC.

**Comment by Mister-Curious** [comment]
Thank you. I think I still need one more thing though. Is there any way you could get me the binary version of the updated **[roomInfo.dat*](https://github.com/nipkownix/re4_tweaks/blob/1e9b65c2648a59ae2ae41ddbc7838d2e8a666c70/dllmain/roomInfo.cpp)* file so I can just paste it into my new **roomInfo_new.dat** and work off of that?

**Comment by emoose** [comment]
Sure, this should be it:
[roomInfo.zip](https://github.com/nipkownix/re4_tweaks/files/9193488/roomInfo.zip)

**Comment by Mister-Curious** [comment]
AMAZING.  thank you so much. Zatarita will work on a tool to help us edit this, using this file as the base.

**Comment by Mister-Curious** [comment]
@emoose would it be possible to get this file to reload on room load, instead of just on startup? Making changes take much more time if we have to relaunch the game each time. The file is about 17kb, so not much as far as adding to load times. 

Thoughts?
