### ISSUE TITLE
Debug menu navigation with controller

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#29]
Hey friends. Just want to say great work so far. I am hoping to draw some attention to the Debug Menu when using a controller. It seems the input is EXTREMELY sensitive to controller input (one light press on the D-pad would equate to holding down the arrow button on a keyboard for at least a full second). This results in not being able to navigate the menu with a controller (id love to not have to use my keyboard at all). 

Can anyone confirm this is happening? I am using a DS4 controller that is emulating an XBOX controller with DS4Windows build 3.0.9

Thanks!

**Comment by emoose** [comment]
Does that happen in all menus or just certain ones? Also which game version are you using?

The 1.0.6/1.0.6debug tool menus did have that problem but I added a workaround for it to most menus, so that button presses are only counted if they weren't pressed on the previous frame - that seemed to fix it for me, but maybe DS4Windows does something that alternates button press each frame or something like that.

IIRC 1.1.0 changed how tool menu read buttons so it never had issues with sensitive buttons, maybe worth getting hold of that build if you haven't tried it already.

**Comment by Mister-Curious** [comment]
_"Does that happen in all debug menus or just certain ones? Also which game version are you using?"_
I only tested it on the main landing page, and I am using version 1.0.6 of the game. 

"maybe DS4Windows does something that alternates button press each frame or something like that."
I tried to test this without DS4Windows but could not get the Debug menu to appear (I bound a key to launch an AHK script to press HOME + END as my keyboard doest have these keys) but the menu doesnt appear. While using DS4Windows I have a button mapped to launch the AHK script and it works, so presently I can not do any tests without DS4Windows unless you guys want to allow users to chose their own keyboard combination for toggling the Debug (you could add this to the options page), or even better you could just add a button in the DLL options page to toggle the Debug menu. 

"IIRC 1.1.0 changed how tool menu read buttons so it never had issues with oversensitive buttons, maybe worth getting hold of that build if you haven't tried it already."
The problem with that is that me (and many other users) can not use 1.1.0 as the trainers and DLLs we use will not work with that version of the game. 

Thanks for your reply. I hope you hop on Discord soon (sent you a few messages there)
Cheers!

**Comment by Mister-Curious** [comment]
Also, one suggestion. Could you possibly add a button in the F1 menu to launch the Debug menu? I have to use AHK to send the HOME + END keys and it doesnt work most of the time. Another option would be to use F2 as a way to toggle this as many of us use keyboards that dont have HOME + END keys 

A better option would be to allow users to choose which hotkey they want to bring up the Debug. 

Thanks!

**Comment by emoose** [comment]
Ah hmm, I'll try testing it myself soon, maybe the workaround got broken somehow.

>I just tested this without DS4Windows and the issue persists.

Just to make sure, were you using a different controller for that, or was that testing using keyboard arrow keys? (arrow keys were another thing re4_tweaks added in)
If you haven't tried arrow keys could you check if those also have the problem too?

About changing the debug combo, I didn't realize some people were missing HOME+END, in that case we should probably use something else.
Would prefer something that needs two keys to be pressed though, so less chance of users accidentally opening it up and wondering what just broke their game.
Maybe something like CTRL+F1, I'd guess that most keyboards would include those at least.

Letting user choose the hotkey can be a little hard, would need to parse string from INI into button #s, and handle modifiers like CTRL/ALT/SHIFT etc, don't really think there's any easy way to do that besides parsing it manually, don't think I've seen any Windows API that can do it for us at least.

**Comment by emoose** [comment]
Ah okay, grabbed 1.0.6 to test it out and also happens with me too - hm, I'm sure there was code in place to workaround it, not sure how that would have broken, need to look into it some more.

In the mean time, I made a PR to allow customizing the tool menu key combo, feel free to give it a try: https://github.com/nipkownix/re4_tweaks/pull/30

**Comment by nipkownix** [comment]
Ah, so it was a controller-specific issue, huh? I'd never have found that one. Thanks indeed!

And also thanks for the quick fix, emoose.

**Comment by Mister-Curious** [comment]
Yes, thank you ofr the quick fix. I found that the keyboard keys worked just fine, so I mapped them in DS4Windows for a temp fix. 

May I ask at this point though why my Debug often wont respond to being toggled on? I suspect it might be how the game is receiving AHK input (remember I cant send HOME + END so its something I have to send via AHK), but my script is solid (send input to other windows easy), so I am not sure if this issue of not toggling right away happens normally or if its something else.

**Comment by nipkownix** [comment]
@Mister-Curious I believe everything is fixed now?

**Comment by Mister-Curious** [comment]
@nipkownix I believe so, but havent tested the latest public release. Will do that tonight and report back. Thanks again!

**Comment by Mister-Curious** [comment]
Everything in the latest build (1.7.2) seems compatible with my mod (with the exception of the **RaiseInventoryAlloc**) but Raz0r's DLL has this feature as well, so I can just keep it off and things work just fine. Controller sens is fine too and works fine in the Debug menu. 

Cheers

**Comment by nipkownix** [comment]
Nice! Thank you for testing. I'll go ahead and close this issue.
