### ISSUE TITLE
"DUMMY" instead of proper subtitles for some of the merchant's lines

### ISSUE THREAD

**Issue by Patrxgt** [nipkownix/re4_tweaks#292]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [x] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

As in the title, sometimes instead of subtitles game shows "DUMMY" text in some scenes with merchant. Can be easily, when meeting a merchant in the cave before the cemetery.

**Comment by albertre4HD** [comment]
Hello! Which language and game mode? (main campaign or separate ways)

**Comment by albertre4HD** [comment]
Ok, another user reported this as well. It's during a cutscene. I already corrected it (a missing subtitle file) and sent nipkow the file to include in the next re4_tweaks release.

Can you confirm the cave's Merchant line is the only missing subtitle?

**Comment by nipkownix** [comment]
The Merchant's line was just added in the latest release, btw.

**Comment by Patrxgt** [comment]
> Ok, another user reported this as well. It's during a cutscene. I already corrected it (a missing subtitle file) and sent nipkow the file to include in the next re4_tweaks release. Can you confirm the cave's Merchant line is the only missing subtitle?

Yup, that's the only time I've seen this bug.



> Hello! Which language and game mode? (main campaign or separate ways)

English (because Polish subtitles weren't ported to the Ultimate HD version, for some reason) and main campaign. First playthrough.

**Comment by nipkownix** [comment]
> Yup, that's the only time I've seen this bug.

Cool. Hopefully we didn't miss any other :p
