### ISSUE TITLE
PS4 controller stop working right after "Press any button" screen.

### ISSUE THREAD

**Issue by maurijr97** [nipkownix/re4_tweaks#293]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Hi, for some reason my PS4 controller stops working right after the "Press any button" screen. I can't do anything after this. With the older version that came out with RE4 HD Project 1.0 the PS4 controller worked just fine. Another thing I noticed is that the steam controller config pop up, that shows up right when you're opening the game, just appears the XBOX controller configuration and not the PS4 anymore, is like something is making only my XBOX controller works. 

Thank you in advance.

**Comment by nipkownix** [comment]
>Another thing I noticed is that the steam controller config pop up, that shows up right when you're opening the game, just appears the XBOX controller configuration and not the PS4 anymore

All of this is sounding more like a Steam issue that's not related to re4_tweaks, IMO.
I use a DS4 myself and never had any issues with it.
Are you sure DS4 supported is enabled on Steam?

**Comment by maurijr97** [comment]
I just noticed you're from Brazil (Eai, cara? kkkkkkkk)

Cara, esse problema apareceu justamente depois que atualizei o RE4 HD Project com a nova versão do re4_tweaks. É bem estranho. E sim, as configurações do DS4 estão ativadas na steam, eu jogo a maioria dos jogos com ele e RE4 é um deles. Eu fiz alguns testes, com a versão anterior com o re4_tweaks antigo e a versão 1.1 com a mais recente, dai toda vez que instalo a mais recente isso acontece e a antiga funciona normalmente. O Albert sugeriu que desativasse todas as opções novas de controles, mas infelizmente não resolveu. Eu vou dar uma verificada baixando todo o HD project de novo e vou usar essa nova versão que saiu hoje do re4_tweaks, fazer um fresh install pra ver se resolve.

**Comment by maurijr97** [comment]
> > Another thing I noticed is that the steam controller config pop up, that shows up right when you're opening the game, just appears the XBOX controller configuration and not the PS4 anymore
> 
> All of this is sounding more like a Steam issue that's not related to re4_tweaks, IMO. I use a DS4 myself and never had any issues with it. Are you sure DS4 supported is enabled on Steam?

I just noticed you're from Brazil (Eai, cara? kkkkkkkk)

Cara, esse problema apareceu justamente depois que atualizei o RE4 HD Project com a nova versão do re4_tweaks. É bem estranho. E sim, as configurações do DS4 estão ativadas na steam, eu jogo a maioria dos jogos com ele e RE4 é um deles. Eu fiz alguns testes, com a versão anterior com o re4_tweaks antigo e a versão 1.1 com a mais recente, dai toda vez que instalo a mais recente isso acontece e a antiga funciona normalmente. O Albert sugeriu que desativasse todas as opções novas de controles, mas infelizmente não resolveu. Eu vou dar uma verificada baixando todo o HD project de novo e vou usar essa nova versão que saiu hoje do re4_tweaks, fazer um fresh install pra ver se resolve.

**Comment by nipkownix** [comment]
> I just noticed you're from Brazil
kkkk

Bom, estranho o problema. Tentou reinstalar tudo? Funcionou?
