### ISSUE TITLE
Crash at game startup (Windows 11, Ryzen 5 5600X, Geforce RTX 2070 Super)

### ISSUE THREAD

**Issue by LSMetag** [nipkownix/re4_tweaks#296]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Hello,

I just installed RE4HD 1.1 (with updated RE4_Tweaks) and I have a CTD at start. I just have time to see the message telling to hit F1 to configure. There is no crash anymore if I remove dinput8.dll so I think it's related to re4_tweaks.

I am running the game in French, using a french keyboard (I tested US Keyboard too but same)

I put the dump in attachment.

Hope it will help.

Thanks

[bio4.exe.20220729024709.zip](https://github.com/nipkownix/re4_tweaks/files/9215116/bio4.exe.20220729024709.zip)

**Comment by felipecrs** [comment]
I'm facing the same issue.

**Comment by emoose** [comment]
Seems to be crashing inside `aligned_malloc` memory allocation func, while trying to load one of the texture .pack files, I guess `Hap_AllocMem` is returning 0 for some reason.

Maybe issue with not enough free RAM... could you try making sure everything besides game/Steam is closed and see if the problem persists?

Besides that, maybe worth testing if an earlier re4_tweaks release helps at all, maybe https://github.com/nipkownix/re4_tweaks/releases/tag/1.7.6 would work better (might have some issues with font sizes though)

**Comment by felipecrs** [comment]
Just to you know, I have this issue even with 32GB of RAM (with 70% free before opening the game).

I haven't tested earlier versions yet, although I remember re4_tweaks worked well when I first installed the HD Project 1.0.

**Comment by LSMetag** [comment]
I managed to solve the issue.

Somehow (with ALT-F4 on errors popups + get focus again with the main white window) I managed to get to main menu and I saw I had to install the 4gb patch.

Even with RE4_Tweaks, you have to install the 4gb patch, otherwise game won't start.

N.B : If you let the "Crashdumps" folder; you still get the errors I posted. When removed, no more crashs. There may be a "workaround" in the tool ^^

**Comment by felipecrs** [comment]
Oh, that's true. I haven't installed the 4GB patch indeed.

But I remember in past versions it would prompt me to install it at the first initialization, wasn't it supposed to be like that?

**Comment by nipkownix** [comment]
re4_tweaks is able to install the 4gb patch for you, but the game should be at least stable before the prompt appears. Hmm. Didn't think not having the 4gb patch would cause a crash before even reaching the main menu.

We might have to move the 4gb patch stuff to run before the game does.

**Comment by LSMetag** [comment]
> Oh, that's true. I haven't installed the 4GB patch indeed.
> 
> But I remember in past versions it would prompt me to install it at the first initialization, wasn't it supposed to be like that?

Yes but game crashes before being able to prompt ^^

**Comment by emoose** [comment]
Ah darn, was thinking it could be 4GB related but figured it would have prompted you already, glad you were able to figure it out 😅 

HDProject was at least able to get to main-menu without 4GB before but I guess texture changes in 1.1 are stopping that now, maybe a simple `MessageBox` prompt when the DLL is first loaded in would work better.

**Comment by LSMetag** [comment]
Yeah. A CRC check on the .exe file, and patching if no match (might be updated if the game updates), and then showing a popup or a text giving the info 4gb patch has been installed.
