### ISSUE TITLE
a couple of questions from a seasoned modder

### ISSUE THREAD

**Issue by kalamalka** [nipkownix/re4_tweaks#3]
Greetings. I have just come across your project and am quite interested in a couple of features. I was wondering if you could tell me about two things for now:

**1 - Film grain**
THis effect is present in many rooms, and is often edited by people by simply applying alpha to the 0193.dds inside 07000000.pack file. While this is the easiest way to accomplish the film grain removal, it is also brutal in the sense that it destroys the efficacy of other effects that rely on this texture. This leads me to ask, does your code use the same method of essentially nulling this texture or does it a more robust approach of editing the effect in the EFF file? I would be happy to lend you my expertise to accomplish this in a less destructive way if you are simply nulling the texture. 

**2 - Transparency overlay**
This interests me deeply. You see there is a small texture inside 07000000.pack file (0236.dds) that is used for several overlays, one of which is in the examine window. It essentially blacks out the middle of the screen, while there is another texture used for gradients on either side of the middle. This texture is also used for the black under the numbers in the inventory case (the numbers used to count ammo amounts etc). So my question is, how does your transparency edit work? Does it alter a texture?

Happy Modding!

**Comment by abi-21** [comment]
Sorry to butt in, I would also request if you could check the missing depth of field effect that appears during cutscenes and other events.

**Comment by Th3W0rst** [comment]
My Game Crash For Using HD Project Why I Set Increase FOV

**Comment by Th3W0rst** [comment]
RE4 UHD on Pc Audio Was Still Broken, and less you going to Fix a Broken Audio Using a RE4_Tweaks Need to be Update

**Comment by kalamalka** [comment]
Hey can you people please submit your own tickets please? My thread was totally hijacked here.
