### ISSUE TITLE
game is not starting after applying the tweak!

### ISSUE THREAD

**Issue by tehniclugoj** [nipkownix/re4_tweaks#302]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

well, i started the game (plain from steam install) worked like a charm, except i could not see entire screen on the monitor (res 3840x1600) 21:9 . (also, no subtitles)
after reading a few posts i got here , and i was glad about this patch/fix/tweak of yours, but unfortunately after i copied your files in the game directory game started to " not start " :))) .
i use windows 11 , in english. i attach .zip file crashdump
i know for sure its from your tweak cause after i delete the files and start again,  game works ...
so please, if you have a fix i am ready to try it!
P.S. your installation description about the tweak is fuzzy, you say copy the 2 files , but there is also a directory in your folder, i still don.t know what is it for or where should i copy it! maybe that is the problem, please be more specific, Thank
[bio4.exe.20220731142231.zip](https://github.com/nipkownix/re4_tweaks/files/9228877/bio4.exe.20220731142231.zip)
s

**Comment by nipkownix** [comment]
> P.S. your installation description about the tweak is fuzzy, you say copy the 2 files , but there is also a directory in your folder, i still don.t know what is it for or where should i copy it! maybe that is the problem, please be more specific

Oh, sorry about that! The folder is a recent addition and I totally forgot to update the instructions. 
Please extract the "re4_tweaks" folder to the "Bin32" folder, the same place where "dinput8.dll" is.

Also, please replace dinput8.dll with this one, and upload a new .zip crashdump if it still crashes:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9228919/dinput8.zip)

**Comment by tehniclugoj** [comment]
Hey, thanks for the fast answer, well, it patched my .exe and it works now,
thank you very much!

Is there a way that my A and D keys make strafe command instead of turn?
you know, like normal  (2022) movement.

**Comment by nipkownix** [comment]
Unfortunately, that isn't possible.
I'll go ahead and close this issue. Feel free to open another one if another problem pops up ^^

**Comment by tehniclugoj** [comment]
Awesome, thanks!
