### ISSUE TITLE
Init_AspectRatioTweaks crash with debug build

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#306]
Some reason one of the Init_AspectRatioTweaks hooks is crashing for me, but only when running with a debug build, release build seems fine.

https://github.com/nipkownix/re4_tweaks/blob/9d28562cce5535fce8de6646022e1d55278c830d/dllmain/AspectRatioTweaks.cpp#L122

 is the line that seems to be crashing, VS says

>Exception thrown at 0x53B36B50 (dinput8.dll) in bio4.exe: 0xC0000005: Access violation writing location 0xCCCCCDD8.

EAX seems to be set to 0xcccccccc here for some reason, weird. I guess maybe debug build is overwriting registers before it calls our injector::MakeInline hook.

E:

```C
			uint32_t orig_eax = regs.eax;
			__asm {
				mov eax, [orig_eax]
				fstp dword ptr[eax + 0x10C]
			}
```

Seems to have solved it, maybe there's a better way than that though.

**Comment by nipkownix** [comment]
Ah, I hadn't realized this could be an issue in debug builds.
Your solutions seems good to me. Thanks for having a look.
