### ISSUE TITLE
Issue with the allow reload without aiming feature

### ISSUE THREAD

**Issue by Markie98** [nipkownix/re4_tweaks#314]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [x] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

If you reload without aiming, then hold right click to aim while the reload animation is still happening and keep aiming once it finishes, vertical mouse movement will affect the camera instead of the weapon (whereas horizontal mouse movement will still affect the weapon) and stay like that until you stop aiming.

**Comment by whybm** [comment]
You are very careful. I tried it out. This problem really exists.

**Comment by nipkownix** [comment]
Oh, you're right. Never noticed it before because it requires some timing to trigger.
Will see what I can do.

**Comment by nipkownix** [comment]
@whybm @Markie98 could you check if everything works fine with this build?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9334099/dinput8.zip)

**Comment by Markie98** [comment]
This seems to have fixed the issue, but now there is something else that feels a bit odd: if you move the camera while the reload animation is happening and then also hold right click so that Leon starts aiming as soon as possible once the reload animation finishes, he will aim directly forward in relation to his body, even if the camera was pointing somewhere else during the reload animation, and once you stop aiming the camera will snap back to that position, making it seem like the movement camera and aiming camera have separate states.

**Comment by nipkownix** [comment]
Are you using a controller? For KB/M, there's an option to improve the stuff you mentioned.

**Comment by whybm** [comment]
> The issue seems to be fixed now.
> 
> Now, I have noticed something else that feels a bit odd: The character always starts aiming directly forwards in relation to his body even if the movement camera was pointing higher or lower before, making it seem like the movement camera and aiming camera have separate states. This discrepancy in camera state only applies to vertical movement. In RE5 this doesn't happen, and you start aiming at where you were looking at with the movement camera, maybe just slightly below. This also happens the other way around - when you stop aiming, the movement camera focuses directly forwards even if you were aiming higher or lower before, with this also being a bit different in RE5, where the movement camera only adjusts back to a forward looking position by a bit every time you stop aiming.
> 
> These aren't exactly issues, it's just how the camera in RE4 works I guess, but having it not constantly focus forward everytime you aim or stop aiming would probably make the game feel a bit more modern and less clunky.

 the "CameraImprovements" option has solved this issue

**Comment by whybm** [comment]
> Are you using a controller? For KB/M, there's an option to improve the stuff you mentioned.
> 
> Edit: Seems you mentioned mouse movement in the OP. Hmm.
> 
> Does the "CameraImprovements" option not change the stuff you mentioned?


When will it be officially updated？Can't wait for the new version. :D

**Comment by Markie98** [comment]
@nipkownix I'm using a mouse.

@whybm I didn't realize there was a "CameraImprovements" option added. When I first tried the dinput8.dll uploaded by @nipkownix here the option didn't seem to to anything, not sure if it was disabled but now I have opened the game with it again and it's enabled and working? Anyway, the weirdness I have described in actually fixed now with it enabled.

What I did notice the first time that is that there are two "MouseTurnType" options now: A and B, and B definitely feels like it should be the default option, dragging the Character's horizontal orientation around only when the camera hits a limit sideways feels pretty weird, I immediately set it to option B.

**Comment by nipkownix** [comment]
> dragging the character's horizontal orientation around only when the camera hits a limit sideways feels pretty weird

Not sure what you mean by that. Option A changes the character's orientation when it moves, there is no sideways limit.

**Comment by Markie98** [comment]
You're right, there is no limit, I was under the impression the character would only change orientation beyond a certain amount of turning. Both options change the character's orientation one way or another. This is what I really mean, though: with option A, walking and dragging the camera sideways turns the character to that direction but his body orientation lags behind a bit while following, whereas with option B, dragging the camera sideways moves the character body immediately so that he's always pointing directly at where you're aiming at, his body is tied to mouse movement. Option B feels more natural, to me at least.

**Comment by nipkownix** [comment]
Hmm, I disagree. Option B makes the character turn as fast as your mouse can move, which can look pretty silly.
While I like both options, I think A is the more natural-looking one.

**Comment by Markie98** [comment]
Well, to each their own. I'm glad we have an option :smile:
