### ISSUE TITLE
JP-only camera angles restoration?

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#32]
Not sure how well known it is, but JP version contains alternate fixed camera angles during Ashley's segment: https://www.youtube.com/watch?v=duf2zTBL9_0

TCRF mentions that it's still included in other versions (and there's even a way to [trigger one of the cameras with noclip](https://youtu.be/mC_BOutNv0s?t=49)), wonder if it could be restored with a patch or something like that. Hopefully it might just be something in the EXE changing it, and not anything game-data related.

Haven't found any mentions of existing mods to add this, I guess since it's such a minor thing, but could be neat if we can find some way to add it back.

**Comment by nipkownix** [comment]
Albert mentioned this can be enabled by changing some byte/bytes in the room files for the Ashley section. He said he has plans to provide optional room files patched with this feature for those who want it, but it would be nicer if this could be toggled with re4_tweaks instead. I'll ask him what exactly needs to be changed. It might even be one of the flags we have in the debug menu, who knows :p

**Comment by nipkownix** [comment]
Here's what albert said:

> The bio4.exe calls to different CAM entries depending if it's the Japanese exe or the other exes.
> It seems it call the CAM entries according to a byte this file has. So, I changed that byte.
> 
> Original r20d CAM file:
> 
> ![image](https://user-images.githubusercontent.com/33870163/149521426-e86bb9d4-3b9a-49cb-aa70-2206d64b6ca0.png)
> 
> Edited r20d CAM file:
> 
> ![image](https://user-images.githubusercontent.com/33870163/149521453-e32272df-b367-41d8-adce-bf3aa1c1a4a3.png)
> 
> It seems the Japanese exe calls non 03 FF camera angles, while the other exes call only 03 FF camera angles (there's only one, the regular camera angle)

**Comment by emoose** [comment]
Hmm, so sounds like the CAM file is the same between JP & EN then, and the EXE is responsible for picking which set to use inside it... Do you know if simply replacing EXE with JP version allows the camera to be used?

Had a quick look at r20d related funcs, didn't really see anything to do with CAM file loading in those, my guess is CAM file is probably loaded as part of some generic func that's used in every room, maybe the func that loads it has code to handle 20d specifically or something - tried searching for refs to 20d but couldn't see anything camera related though.

Worst comes to worst, can probably just hook the func that loads in that CAM file and patch it in memory after it's loaded, would be better if we can find what's actually checking it though.

**Comment by emoose** [comment]
Aha, `0x6F5522 -> nop` :)

**Comment by nipkownix** [comment]
Ohhhh, nice!

I wonder if we can enable the Biohazard logo with this. Great find!

**Comment by emoose** [comment]
>Looks like my version of IDA crashes when generating this file for some reason. Meh.
Ah that's too bad, here's a copy I generated in case you want to look into it:
[re4-rip11.zip](https://github.com/nipkownix/re4_tweaks/files/7872933/re4-rip11.zip)

**Comment by nipkownix** [comment]
Sweet, many thanks!
