### ISSUE TITLE
[Feature Request] Display Current Enemy HP

### ISSUE THREAD

**Issue by sambettley** [nipkownix/re4_tweaks#327]
### Describe the feature you'd like to see added

I know this feature can see on EM Manager, but I think it's good too see on like bar HP even in the form of numbers. Maybe how it works we can find out the enemy's current hp when aiming at them. The position can be above or near Leon health bar. This is very helpful when we play mods like Life in Hell or Rising of Evil when the enemy has a fairly large HP.

**Comment by Mister-Curious** [comment]
I think you would need some serious DirectX wizardry to start putting overlays in the game.

**Comment by DarkxVoid-loop** [comment]
Qingsheng has already done this in his dll

**Comment by nipkownix** [comment]
This feature is in the new trainer tab as "ESP" now:

![image](https://user-images.githubusercontent.com/33870163/199733378-996cae26-c156-475c-81b8-08c43d5e23ce.png)
