### ISSUE TITLE
Color bars during resolution setting change + fade during savegame selection

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#339]
Two weird issues I've been having for a while:

Color bars appear when switching through resolutions (without resolution even being changed, just going through the options):

https://user-images.githubusercontent.com/1755499/191581448-fad8c70f-1ea7-4731-8aec-0df343c60b73.mp4

and weird fade/brightness flicker when going through savegames (for some reason it doesn't show much in the recording, but the flicker is happening pretty much every time I change the selection):

https://user-images.githubusercontent.com/1755499/191581667-446e6af2-6bf0-4481-a8dc-042d1608848d.mp4

Thought it might have been something on the trainer branch, but using latest master also seems to cause it too (under both vanilla & HDP1.1) - though issue doesn't appear when using 1.7.7.6...

E: quite a few changes between 1.7.7.6 and master: https://github.com/nipkownix/re4_tweaks/compare/1.7.7.6...master
Tried disabling as much as I could in INI but no improvement, maybe git bisect could help.

E2: ah went through bisect, seems issue might have started in [Added new MouseTurning type and CameraImprovements](https://github.com/nipkownix/re4_tweaks/commit/ccc2c7e173b3a7bddb2e2b25153ef6c0b1a05583)

E3: seems to be something inside `Init_CameraTweaks`, making it return before it hooks stuff (but after it gets the `C_RANGE_1097` etc pointers, else other code crashes) seems to get rid of the issue, not really sure what hook inside there would be interfering though.

**Comment by nipkownix** [comment]
Ah, I was surprised to never have found any issues with those patches until now, honestly.

I only recently noticed the weird flashes. Thought it was caused by something more recent, though. Meh.

**Comment by emoose** [comment]
Seems it might be the `PadReadYreset` hook, looks like both that and `PadReadXreset` are working on the same block of code at 968B4E, one is hooking the `fst` and the other the `fstp`, hooks then reuse the original fst/fstp in the hook block as an __asm.

Think I had issues trying to use fst/fstp inside `MakeInline` hooks before, AFAIK `fstp` is popping something from the x87 ST stack, maybe MakeInline ends up restoring it or something.

**Comment by nipkownix** [comment]
Ah, hmm, the ``fstp`` being inside the if was intentional, though, I think? Don't really remember, but unconditionally writing 0 is the game's vanilla behavior, and I wanted to stop that. I think our probably was the ``p`` part of ``fstp``, as poping the value should happen regardless. Meh.

I've come up with something else that should work though:

![image](https://user-images.githubusercontent.com/33870163/191638690-0c52235d-b9b4-4932-922e-3c6964fea22b.png)

Haven't tested much, been having little free time lately :/

Will test in a sec.
