### ISSUE TITLE
[feature request] option to disable the laser sight

### ISSUE THREAD

**Issue by juuuulian-s** [nipkownix/re4_tweaks#348]
### Describe the feature you'd like to see added

im wondering if theres a way to fully disable the laser sight, mostly just for the extra challenge (ive played this game way too much)
ive had some degree of success by changing the laser colour to black, but that doesnt fully get rid of the laser dot
maybe an opacity slider instead of an outright on/off toggle would be better. i do recognise its a fairly niche request, so i dont mind if it doesnt get much traction.

**Comment by ViperAcidZX** [comment]
Someone has made a separate mod to turn off the laser sight.

• https://www.nexusmods.com/residentevil4/mods/409?tab=files

EDIT: If you're trying to use this with the HD Project, you'll have to edit the `core.udas` file HD Project comes with manually by unpacking it, hex editing the extracted `core_001.EFF`, and then repacking the file with smaller sight. The mod has a Readme and instructions on how to manually edit the `core.udas` file.
