### ISSUE TITLE
4GB-patch indicator

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#35]
Might be a good idea to indicate to user whether they have 4GB patch active or not somehow, like the other DLL does, been a few times now that I've ran an EXE that wasn't patched & had issues because of it >.>

Doesn't seem like there's any way to 4GB patch it at runtime unfortunately - I wonder if we might be able to edit the EXE itself if the user hasn't already patched it though, hmm...

(also the way the other DLL checks for 4GB patch is wrong, seems they're checking for a constant 0x122 Characteristics value, when they should only be checking for the 0x20 bit, if you have the Relocations stripped flag active that adds 0x1 to it, so it's 0x123, making that DLL think it isn't 4GB patched 😆)

E: did a quick experiment, looks like on Windows you can't open the running EXE with fopen for writing, but you can move it!
Probably wouldn't be too hard to just copy the existing EXE + edit the Characteristics flags, then move them around so the patched EXE will be launched by user next time.

I'm not sure if being in Program Files could mess that up at all though, pretty sure I heard Steam sets up permissions on SteamApps dir to allow changes, but not 100% sure about that.

**Comment by emoose** [comment]
Alright, got something working at https://github.com/emoose/re4_tweaks/tree/laa-check:

![20220115041548_1](https://user-images.githubusercontent.com/1755499/149608488-10dab159-242e-40d1-980d-4e244c305ce5.jpg)
![20220115041554_1](https://user-images.githubusercontent.com/1755499/149608489-f2a894cd-b6a8-47cf-b539-68cc800ca5bb.jpg)

Not sure if the way I implemented it is the best though, haven't really worked with ImGui that much before.
The code that handles the EXE patching should be pretty safe, tries restoring original EXE if we can't move the patched one in its place, so user isn't left with a broken install - probably more checks should be added there though.

**Comment by nipkownix** [comment]
>(also the way the other DLL checks for 4GB patch is wrong, seems they're checking for a constant 0x122 Characteristics value, when they should only be checking for the 0x20 bit, if you have the Relocations stripped flag active that adds 0x1 to it, so it's 0x123, making that DLL think it isn't 4GB patched 😆)

Oh Raz0r.. 
If he had, you know, open sourced his DLL, we could have opened a PR with a fix or something 😆

> E: did a quick experiment, looks like on Windows you can't open the running EXE with fopen for writing, but you can move it!

Really? That's pretty interesting. I wonder if this behaviour is the same in previous Windows versions.

But wow, I spent a long time trying to find a way to do it at runtime, thinking that patching the actual .exe wouldn't be possible. Nice work!

> Not sure if the way I implemented it is the best though, haven't really worked with ImGui that much before.

Maybe adding a `ImGui::SameLine()` between the buttons would be a good idea, but that's just my personal preference.
Everything else is looking pretty nice to me, but I'm also somewhat new to ImGui :p

**Comment by emoose** [comment]
From what I can find online there's been a few posts over the years about similar rename/MoveFile tricks with running EXEs, eg. this post from 2006 mentions it working on XP: https://w-shadow.com/blog/2006/09/14/renaming-a-running-exe/

From some other posts I found it seems this might only work when the EXE is being moved on the same drive (https://stackoverflow.com/questions/49015860/windows-api-movefile-not-working-for-running-exe/49016308 answer there seems to explain why), so no big worry for us there, but some other posts mention UAC can be an issue - more than likely for us since most people will probably have the game in Program Files folder too...

Hopefully the error handling there should catch any problem with that though, in my own case it seems to be able to move the EXE fine despite my game being inside Program Files/Steam/SteamApps, game doesn't UAC prompt on launch neither & winmm.ini seems to write fine there too, so maybe Steam does do something to the SteamApps dir.

Anyway I'll try seeing about updating the layout a little and make a PR for it later on.

**Comment by nipkownix** [comment]
@emoose looks like there's a small issue with the 4gb patch that is affecting Chinese users only, for some reason.

The issue makes in-game prompts disappear at random.

![image](https://user-images.githubusercontent.com/33870163/152627375-318e1e7e-7f77-4c98-beed-d7610b3f101a.png)

(second and third pics show the before and after the issue)

I know it is caused by the 4gb patch because albert managed to reproduce the issue himself. If he patches the exe using our dll, the problems occurs. If he uses another patching tool, no issue happens.

He noticed when comparing both exe files that there's a single byte difference:

![image](https://user-images.githubusercontent.com/33870163/152627420-299f9d90-964a-4c5b-8f77-9ae62044f7cd.png)

So, we are doing _something_ wrong, even if just a single byte :p

Now, I don't know much about PE headers, but I'm very curious to understand how a single byte could break in-game prompts for chinese players only. Seems like a oddly specific issue.

**Comment by emoose** [comment]
Looks like that's PEChecksum field:
![image](https://user-images.githubusercontent.com/1755499/152627558-c4d2893b-6622-4233-8fd4-abf51b013a97.png)

Is that comparing ours against NTCore-patched version? I guess NTCore probably fixes the checksum while we don't, never thought it'd be important at all, kinda weird that something would be depending on it.

**Comment by nipkownix** [comment]
Oh, hmm, I see.
Yeah, he did use NTCores's patcher.

But yeah, really weird that this could break the game this way.

Thanks for taking a look.
