### ISSUE TITLE
Reloading without aiming P.R.L. 412 crashes game

### ISSUE THREAD

**Issue by ddubs13** [nipkownix/re4_tweaks#352]
### Validation

- [x] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

When the "reload without aiming first" feature is active, pressing the reload button while the P.R.L. 412 is equipped (without aiming) crashes the game. This does not happen with other weapons that don't reload, such as rocket launchers.

[bio4.exe.20221025114749.zip](https://github.com/nipkownix/re4_tweaks/files/9862336/bio4.exe.20221025114749.zip)

**Comment by albertre4HD** [comment]
Here's a comment in re4hd.com from another user about the same issue:

«
[...] Started a cleared game run on my professional save and got a P.R.L. and Handcannon from the store, except whenever I press R to reload on the P.R.L. the game insta-crashes. [...]
»

«
Tested it some more and it seems to only be a problem when “Allow reload without aiming” is turned on and I press R without aiming.
»

For the record ;D
Thanks!

**Comment by nipkownix** [comment]
Ah, hmm, gotta admit I didn't think about the PRL. No idea why it would just crash though, but I'll take a look soon.

**Comment by nipkownix** [comment]
Seems the crash was already fixed (probably in d6e789bfdb59d8eb2c05b6fc56a6924600367981 ?), but I still ended up making a small improvement.

Can you test this build, please?
https://github.com/nipkownix/re4_tweaks/suites/9090505610/artifacts/421213604

**Comment by ddubs13** [comment]
Works now. Thanks!
