### ISSUE TITLE
[Feature Request] Allow camera to reset after using knife

### ISSUE THREAD

**Issue by ddubs13** [nipkownix/re4_tweaks#356]
### Describe the feature you'd like to see added

Normally, if you aim upwards with the knife to slash a face, letting go resets the camera. With the new camera improvements, this doesn't happen and the camera always stays where it is, which means Leon is left staring at the sky and I have to adjust it every time, which makes it more difficult to follow up with a melee attack and judge how safe it is to do so. The same is true after knifing enemies on the ground: I'd prefer to not have to manually adjust the camera back just so Leon isn't staring at the ground.

It's a minor thing, but it's annoying enough that players who like doing knife-only runs (such as myself) feel more comfortable with the original camera.

**Comment by nipkownix** [comment]
Yeah, you're right, resetting the camera in this case seems to work best. I've added it as an option, enabled by default now. A new release should come soon-ish (hopefully).
Thanks!
