### ISSUE TITLE
P.R.L  I press R to reload on the P.R.L. the game insta-crashes.

### ISSUE THREAD

**Issue by leon861107** [nipkownix/re4_tweaks#360]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

P.R.L  I press R to reload on the P.R.L. the game insta-crashes. I know the gun has infinite ammo and there is no need to even press R, but still the game just instantly crashes if I press R with the P.R.L. equipped. Use other guns like the handgun or TMP or anything and it works fine. Just the P.R.L. does this it seems. Don’t have any other infinite ammo weapons so don’t know if this is a problem with all infinite ammo weapons or just the P.R.

**Comment by laymonage** [comment]
See #352.

**Comment by leon861107** [comment]
Works now. Thanks!
