### ISSUE TITLE
Game stuck at PRESS ANY KEY screen If NeverCheckForUpdates = false and firewall block internet connection

### ISSUE THREAD

**Issue by bursoft-git** [nipkownix/re4_tweaks#374]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

If my firewall block connection for bio4.exe, game stuck at PRESS ANY KEY screen, and  ANY KEY not working)
![Resident Evil 4 06 12 2022 11_28_50](https://user-images.githubusercontent.com/7475720/205860464-b42c1edd-ff87-4b91-836b-42f2ee389401.png)

**Comment by nipkownix** [comment]
Ah, thanks! Turns out I forgot to remove an unused state. Latest commit should fix it.

**Comment by bursoft-git** [comment]
latest commit fixed it, thanks!
