### ISSUE TITLE
Crash logging

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#38]
It might be useful if some kind of crash logging can be added in, just in case some patch might interfere badly with something we haven't tried yet, might also help to track down some CTD issues like the ones reported in the #25 PR which might be caused by something in users config, making it hard for us to trigger on our end.

Windows default for app crashes is pretty bad now too, just ending the program with no indication that there was even any crash (the `x has stopped working` dialog has been disabled since Win10 for some incredibly stupid reason...)

IIRC [SetUnhandledExceptionFilter](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setunhandledexceptionfilter) can be used to set a function that receives info about the exception like exception code/address it happened/etc, was able to use that before in another project to write info about crashes into a log file. 

I wouldn't be surprised if there was some lib somewhere that can handle this for us nicely, maybe even with minidump support, but haven't seen anything like that yet.

**Comment by nipkownix** [comment]
This sounds good. We could probably borrow the one in [TAG's Ultimate ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader).

**Comment by nipkownix** [comment]
Got something that appears to be working fine in https://github.com/nipkownix/re4_tweaks/tree/exception-handler

**Comment by nipkownix** [comment]
up

**Comment by nipkownix** [comment]
Ah, so the problem with `SetUnhandledExceptionFilter` is that something else was calling it after us.
Apparently TAG's ASI loader also ran into the same issue and stubbed out the function so no one else could call it. Seem to fix the issue :p

**Comment by nipkownix** [comment]
Closing this since everything appears to be working fine.
