### ISSUE TITLE
Feature Request - toggle DLL

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#39]
While testing various issues I often have to move or rename the DLL to activate/deactivate it. Would it be possible that you could put a kill switch in the **winmm.ini** with something like:

**[ACTIVATE]
; Use this DLL
UseThisDLL = True**

This way users could simply add true false in Notepad ++ and switch back and forth without having to rename or move any files. 

Thanks!

**Comment by emoose** [comment]
Hmm, in your case (and other modders that need to quickly switch between enabling/disabling it) it might be easier to just use a batch file for it, eg:
```
@echo off
IF EXIST winmm.dll ( move winmm.dll winmm.dll.disable ) ELSE ( move winmm.dll.disable winmm.dll )
```

With that saved as toggle.bat running it should toggle the DLL on/off for you, seems to work on my end at least.

**Comment by nipkownix** [comment]
I agree with emoose here. Here's an alternative batch file using a different approach:

```
@echo off
TITLE winmm.dll Switcher
SETLOCAL EnableDelayedExpansion
IF EXIST winmm.dll (set state=Enabled) ELSE (set state=Disabled)
goto start

:switch
IF EXIST winmm.dll (
move winmm.dll winmm.dll.disable
echo Disabled winmm.dll
set state=Disabled
) ELSE (
move winmm.dll.disable winmm.dll
echo Enabled winmm.dll
set state=Enabled
)
goto start

:start
cls
echo(
echo      Press enter to toggle winmm.dll on/off
echo     ========================================
echo(
echo Current state: %state%
echo(
pause
goto switch
exit
```

![image](https://user-images.githubusercontent.com/33870163/150232218-e3fa340f-7125-4451-a300-0ac59743463d.png)

You can leave that window open and toggle re4_tweaks by pressing enter.

**Comment by Mister-Curious** [comment]
@emoose @nipkownix thank you both for these scripts. I look forward to using this. 

Cheers
