### ISSUE TITLE
Game crashing on startup after using newest RE4 Tweaks(with hd project)

### ISSUE THREAD

**Issue by AlbertFnWesker** [nipkownix/re4_tweaks#393]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

as the title suggests. i even did a completely fresh install of re4 and the 1.1 version of hd project, and the game crashes basically as soon as i try an open it.

**Comment by nipkownix** [comment]
Could you create a folder called "CrashDumps" in ``Bin32``, and try to run the game again? Once the game crashes, a zip file with some info will be created in that new folder that could help us diagnose this.

**Comment by AlbertFnWesker** [comment]
ok heres a crash log 
[bio4.exe.20221225085550.zip](https://github.com/nipkownix/re4_tweaks/files/10300056/bio4.exe.20221225085550.zip)

**Comment by nipkownix** [comment]
Looks like a problem with ReShade, probably because re4_tweaks 1.8 is making the game use a Vulkan renderer by default.

Are you using the latest version of ReShade? Not sure what could cause issues here, since ReShade should support Vulkan just fine.

You should be able to workaround the issue by just disabling ``UseVulkanRenderer`` in dinput8.ini.

**Comment by AlbertFnWesker** [comment]
turning that "usevulkanrenderer" off did the trick, thanks. i wasn't even aware i had any reshade for re4 so i dont know what thats about, i only ever used a reshade for re5 a couple years ago.

**Comment by nipkownix** [comment]
> turning that "usevulkanrenderer" off did the trick, thanks.

Ah, nice, no problem.

> i wasn't even aware i had any reshade for re4 so i dont know what thats about, i only ever used a reshade for re5 a couple years ago.

AFAIK, the Vulkan version of ReShade uses a Vulkan "layer" that's registered in the system, so it loads even if you don't have any ReShade .dll in your game folder. But it shouldn't just load into any games at random.. I think? Maybe that's a weird quirk of an older release of ReShade or something.

**Comment by AlbertFnWesker** [comment]
so i updated reshade to the most current version an now it works with the vulkan renderer ON, i guess the reshade i had was just too out of date, thanks for the help!
