### ISSUE TITLE
[bAllowReloadWithoutAiming_controller] Prioritize action button

### ISSUE THREAD

**Issue by ThirteenAG** [nipkownix/re4_tweaks#394]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Currently it's quite annoying to pick up items and kick enemies with this option, because when on screen prompt appears, reloading happens first, and you can press X to do the action only when the gun is fully reloaded.

Is there a way to check if there's an onscreen prompt, and not reload in that case?

**Comment by nipkownix** [comment]
Huh, gotta admit that situation didn't cross my mind. 
It should be possible to check for an onscreen prompt, I'll take a look soon.

**Comment by ThirteenAG** [comment]
>  @ThirteenAG, does this build work for you? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10300000/dinput8.zip)

Works perfectly, thanks!
