### ISSUE TITLE
winmm.dll sometimes is not loaded properly

### ISSUE THREAD

**Issue by nipkownix** [nipkownix/re4_tweaks#40]
Is there any situation where Windows would ignore winmm completely? Or maybe force it to only load from System32/SysWOW64?

I've seen reports of people saying re4_tweaks would simply not load after placing the files next to the .exe
I've also confirmed with at least one of these people that wrapping dinput8 instead (by just renaming winmm to dinput8) works just fine.
The reason I've initially gone with winmm instead of dinput8 is because that's what raz0r's dll uses, and I didn't want to make people choose between the two. But now that this winmm issue is a thing.. we might have to change the default wrapped dll?

**Comment by emoose** [comment]
Hmm, can't think of a reason winmm.dll wouldn't be loaded, other than maybe antivirus products preventing it. I had same kind of issue with some people reporting my FFVIIHook xinput1_3.dll not getting loaded in, but apparently disabling AV helped some of them.

If dinput8 has better success rate, maybe it's worth adding something to allow chainloading other DLLs too, can usually just LoadLibrary other DLLs to get them working, assuming they do most of their work inside DllMain - could have a section in the INI for users to specify other DLLs, or just add something that tries LoadLibrary("dinput8_extra.dll") or something like that.

**Comment by nipkownix** [comment]
>(E: btw just emailed you about something, might have ended up in your spam though)

Oh, it did end up in the spam folder.
I answered you there, just in case you missed it.

**Comment by emoose** [comment]
BTW, have you heard from any Linux users whether this is working through WINE/Proton/etc?

With FFVII my xinput1_3.dll had an issue being loaded in, seems a DLL override was needed to let it get loaded properly: https://forums.nexusmods.com/index.php?/topic/10858168-ffviihook-ue4-dev-console-unlocker/page-37#entry103505913

Not sure if dinput8.dll might also need something like that too.

**Comment by nipkownix** [comment]
I tested it a couple of releases ago and it worked fine with a winmm.dll override.
Every mod that does this type of dll wrapping stuff requires dll overrides on Wine.
I'll test the current version later today to make sure everything is still working properly.

**Comment by nipkownix** [comment]
Seems to be working fine with the usual override (dinput8 -> native, builtin):

![image](https://user-images.githubusercontent.com/33870163/151407952-a30861d8-ec88-4d81-8387-e64d70e8d574.png)

**Comment by emoose** [comment]
BTW seems a lot of Linux users are reporting issues on the re4hd issues page: https://www.re4hd.com/?page_id=9319#comment-197452

Seems they're using older instructions about winmm overrides (and also copying this into their WINE system32 folder, which seems incorrect to me) - might want to add a section to README about setting it up properly.
