### ISSUE TITLE
[Feature request] Make the "Quit" button close the game immediately

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#404]
For some reason pressing the quit button on the main menu makes the game slowly fade to black (which takes about three total seconds) and then the game actually closes.

Would it be possible to make this immediate instead? It would certainly help in case if you enable or disable tweaks that require you to restart the game.

**Comment by nr1995** [comment]
It's true; it's a little annoying.
I just use AutoHotkey to close all my programs instantly.

^NumpadSub::ProcessClose("bio4.exe")

**Comment by nipkownix** [comment]
Added an option to speed up that crazy long fade in 63f1b88.

Test build:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10325079/dinput8.zip)

I've been using ALT+F4 all this time to quit the game, so I never noticed how long that original screen fade is, lol

**Comment by linkthehylian** [comment]
Thanks dude! I'll be sure to test it asap.

**Comment by linkthehylian** [comment]
Yeah, that is SO much better holy shit haha. Thank you again! @nipkownix. I'll close this now.
