### ISSUE TITLE
This application has requested the Runtime to terminate it in an unusual way.

### ISSUE THREAD

**Issue by InsideCat02** [nipkownix/re4_tweaks#405]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Game Version - 1.1.0

I'm not really sure how to tackle this issue, and even though I think it might be on my end, in case it's important, I'm submitting this here in order to catch it. I just know it has direct relation to the Vulkan Renderer. Disabling it via the ini is what gets around the crash. Turning it back on results in it happening again.

![image](https://user-images.githubusercontent.com/111202797/209626208-2b21afa3-ef12-4dd3-aecf-075e61962754.png)

[I also have the crash via the CrashDump.](https://github.com/nipkownix/re4_tweaks/files/10306540/bio4.exe.20221227020405.zip)

**Comment by nipkownix** [comment]
In dinput8.ini, under the line ``UseVulkanRenderer = true``, please add a new line with ``DXVK_LOG_LEVEL = debug``. This will create a ``dxvk.log`` in the ``re4_tweaks`` folder the next time you run the game. Hopefully there will be some helpful information there.

**Comment by InsideCat02** [comment]
[Sorry for the delay! Here's the dxvk.log](https://github.com/nipkownix/re4_tweaks/files/10312124/dxvk.log)

**Comment by nipkownix** [comment]
> Also, as a side note, a bug/problem I've noticed, setting the speed override hotkey to ' some reason makes the game refuse to launch. I was stuck figuring out why my game kept making refusing to load, and after a lot of repeat reboots and one by one redoing my settings, I narrowed it down to that.

Ah, you're right. I never noticed that before, but it seems to be a problem with the ini reader we're using:
https://github.com/ThirteenAG/IniReader/blob/85c2845b9dda0fa1f36612f8476d432dab1730d7/IniReader.h#L216

It is trying to remove single and double quotes from strings, but that obviously breaks our hotkeys. Hmm.

> Sorry for the delay! Here's the dxvk.log

Thanks, but it looks like there's nothing too helpful there...
What are your specs? Are you using AMD or Nvidia? Is it a laptop?

I improved our d3d9 fallback in this build:
https://github.com/nipkownix/re4_tweaks/suites/10070218481/artifacts/490377396
If you try running with the vulkan renderer again, and it fails, the reason for the failure should now hopefully be in dinput8.log. Could you give it a try?

**Comment by InsideCat02** [comment]
> > Also, as a side note, a bug/problem I've noticed, setting the speed override hotkey to ' some reason makes the game refuse to launch. I was stuck figuring out why my game kept making refusing to load, and after a lot of repeat reboots and one by one redoing my settings, I narrowed it down to that.
> 
> Ah, you're right. I never noticed that before, but it seems to be a problem with the ini reader we're using: https://github.com/ThirteenAG/IniReader/blob/85c2845b9dda0fa1f36612f8476d432dab1730d7/IniReader.h#L216
> 
> It is trying to remove single and double quotes from strings, but that obviously breaks our hotkeys. Hmm.
> 
> > Sorry for the delay! Here's the dxvk.log
> 
> Thanks, but it looks like there's nothing too helpful there... What are your specs? Are you using AMD or Nvidia? Is it a laptop?
> 
> I improved our d3d9 fallback in this build: https://github.com/nipkownix/re4_tweaks/suites/10070218481/artifacts/490377396 If you try running with the vulkan renderer again, and it fails, the reason for the failure should now hopefully be in dinput8.log. Could you give it a try?

Here's some of my specs!

![image](https://user-images.githubusercontent.com/111202797/209884222-78bc9e61-14a4-4d68-afca-bdcc5378db9b.png)

And other details from where I got it from

> 
    AMD Ryzen 7 5800H 3.2GHz Processor
    NVIDIA GeForce RTX 3050 4GB GDDR6
    16GB DDR4-3200 RAM
    512GB Solid State Drive
    Microsoft Windows 11 Home
    10/100/1000 Network
    2x2 802.11ax Wireless
    Bluetooth 5.0
    15.6" FHD IPS LED-backlit Anti-Glare 120Hz Display

And it is a laptop, yes, as well as downgraded from Windows 11 Home to Windows 10 Home.

[As for the new dinput8.log, here you go!](https://github.com/nipkownix/re4_tweaks/files/10316892/dinput8.log)

**Comment by nipkownix** [comment]
```
[18:23:21] [t 43420] hook_Direct3DCreate9 -> DXVK error: DxvkInstance::enumAdapters: Failed to enumerate adapters
[18:23:21] [t 43420] hook_Direct3DCreate9 -> Falling back to D3D9
```
Seems the call to ``vkEnumeratePhysicalDevices`` fails, so this is a problem with your setup. Your GPU should support Vulkan just fine, so I can only imagine there's some issue with your drivers.
At least the improved fallback does let the game use d3d9 if Vulkan fails in this way now.

**Comment by InsideCat02** [comment]
> At least the improved fallback does let the game use d3d9 if Vulkan fails in this way now.

True, in any case, I'm not sure how to deal with the problem, since I keep my drivers up to date whenever possible, so I really have no clue what else I could do other than that to fix the problem. (That being said, I do note that I've just been keeping my Nvidia driver up to date, not the AMD ones, if that some reason makes any difference/explanation?)

**Comment by nipkownix** [comment]
You've mentioned you're using a laptop, right? Is your Nvidia GPU set as the "Preferred graphics processor" in the nvidia control panel?

**Comment by InsideCat02** [comment]
> Is your Nvidia GPU set as the "Preferred graphics processor" in the nvidia control panel?

I've sometimes flopped back and forth between just auto-selecting and setting it to be the preferred GPU, and usually with auto-select, it'll automatically go with the Nvidia GPU for RE4, so yeah, it probably shouldn't matter, it was just an idea (that in hindsight reminded me to update AMD stuff just in case. I WAS pretty outdated regardless.)

![image](https://user-images.githubusercontent.com/111202797/210185054-5268f333-3dff-4bc8-8866-bb5cccac54ad.png)
