### ISSUE TITLE
Leon's jacket

### ISSUE THREAD

**Issue by PaLhAnDs** [nipkownix/re4_tweaks#410]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

hello there. don't know if this has been reported before, very sorry if this is the case. well, seems there's a bug on del lago when activating and then wearing Leon's jacket. ocurred to me after the fight ended, when Leon is cutting the ropes.

i can see Leon jacket sleeves, but the rest is missing. i think is clashing somehow... don't know.

is this just a problem on my end?

**Comment by linkthehylian** [comment]
I believe this is due to the fact that Leon would not still be wearing his jacket by the time he's fighting Del Lago.

The description of the OverrideCostumes tweak also states: "**May cause weird visuals in cutscenes.**"

**Comment by PaLhAnDs** [comment]
oh you are right, there's a description about it... omg how i missed that? well... maybe in the future there will be a fix for this problem. thank you for the reply!

thank you all for this awesome work with RE4. it's been a incredible experience so far.

**Comment by nipkownix** [comment]
Yeah, maybe we'll be able to improve the jacket in cutscenes at some point. At least everything works fine during gameplay :p
Thanks for using our project!
