### ISSUE TITLE
No resolution options when playing through HDMI cable on 4k

### ISSUE THREAD

**Issue by Diegoeo9** [nipkownix/re4_tweaks#411]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Hey!
I'm having a problem after upgrading to 1.8, now when i'm playing with a HDMI cable to my 4k TV, the resolutions available in the video settings just show two 4k options, and I can't choose a lower one as I used to (1080p). When using my 1080p laptop I'm able to choose freely, below that, but when I use the TV It always defaults back to 4k even if I set the display to 1080p or change it in one of the ini. My middle spec PC cant handle 4k :(

**Comment by nipkownix** [comment]
Please try this new build and tell me if it changes anything:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10317243/dinput8.zip)

Also, open  ``dinput8.ini`` and change ``VerboseLog`` to ``true`` before testing, then upload the new ``dinput8.log`` here when you're done.

**Comment by Diegoeo9** [comment]
Yeah thank you, menu options stay the same, still not lower resolutions when on 4k. 
The game renders in 1080p now, though the menu still says 4k, but thats only when setting the tv on 1080, if i  put it on 4k, game does 4k, but never reverts to 1080 even if revert tv setting, it only reverts when playing on pc screen first , setting tv 1080 second, and restart game.  Hope i make myself clear lol.
[dinput8.log](https://github.com/nipkownix/re4_tweaks/files/10317696/dinput8.log)

**Comment by nipkownix** [comment]
Thank you for the log!

According to the log, you have 4 monitors (is that right?) and your primary one when playing is ``\\.\DISPLAY4``, which I assume is the TV. The problem is, it seems your TV's refresh rate options are all lower than 60 Hz in resolutions that are below 4K:

```
+------------+------------+
| D3D9Adapter::CacheModes |
| 640  x 480        23 Hz |
| 640  x 480        24 Hz |
| 640  x 480        25 Hz |
| 640  x 480        29 Hz |
| 640  x 480        30 Hz |
| 720  x 480        23 Hz |
| 720  x 480        24 Hz |
| 720  x 480        25 Hz |
| 720  x 480        29 Hz |
| 720  x 480        30 Hz |
| 720  x 576        23 Hz |
| 720  x 576        24 Hz |
| 720  x 576        25 Hz |
| 720  x 576        29 Hz |
| 720  x 576        30 Hz |
| 800  x 600        23 Hz |
| 800  x 600        24 Hz |
| 800  x 600        25 Hz |
| 800  x 600        29 Hz |
| 800  x 600        30 Hz |
| 1024 x 768        23 Hz |
| 1024 x 768        24 Hz |
| 1024 x 768        25 Hz |
| 1024 x 768        29 Hz |
| 1024 x 768        30 Hz |
| 1152 x 864        23 Hz |
| 1152 x 864        24 Hz |
| 1152 x 864        25 Hz |
| 1152 x 864        29 Hz |
| 1152 x 864        30 Hz |
| 1280 x 720        23 Hz |
| 1280 x 720        24 Hz |
| 1280 x 720        25 Hz |
| 1280 x 720        29 Hz |
| 1280 x 720        30 Hz |
| 1280 x 768        23 Hz |
| 1280 x 768        24 Hz |
| 1280 x 768        25 Hz |
| 1280 x 768        29 Hz |
| 1280 x 768        30 Hz |
| 1280 x 800        23 Hz |
| 1280 x 800        24 Hz |
| 1280 x 800        25 Hz |
| 1280 x 800        29 Hz |
| 1280 x 800        30 Hz |
| 1280 x 960        23 Hz |
| 1280 x 960        24 Hz |
| 1280 x 960        25 Hz |
| 1280 x 960        29 Hz |
| 1280 x 960        30 Hz |
| 1280 x 1024       23 Hz |
| 1280 x 1024       24 Hz |
| 1280 x 1024       25 Hz |
| 1280 x 1024       29 Hz |
| 1280 x 1024       30 Hz |
| 1280 x 1440       23 Hz |
| 1280 x 1440       24 Hz |
| 1280 x 1440       25 Hz |
| 1280 x 1440       29 Hz |
| 1280 x 1440       30 Hz |
| 1360 x 768        23 Hz |
| 1360 x 768        24 Hz |
| 1360 x 768        25 Hz |
| 1360 x 768        29 Hz |
| 1360 x 768        30 Hz |
| 1366 x 768        23 Hz |
| 1366 x 768        24 Hz |
| 1366 x 768        25 Hz |
| 1366 x 768        29 Hz |
| 1366 x 768        30 Hz |
| 1400 x 1050       23 Hz |
| 1400 x 1050       24 Hz |
| 1400 x 1050       25 Hz |
| 1400 x 1050       29 Hz |
| 1400 x 1050       30 Hz |
| 1600 x 900        23 Hz |
| 1600 x 900        24 Hz |
| 1600 x 900        25 Hz |
| 1600 x 900        29 Hz |
| 1600 x 900        30 Hz |
| 1600 x 1024       23 Hz |
| 1600 x 1024       24 Hz |
| 1600 x 1024       25 Hz |
| 1600 x 1024       29 Hz |
| 1600 x 1024       30 Hz |
| 1600 x 1200       23 Hz |
| 1600 x 1200       24 Hz |
| 1600 x 1200       25 Hz |
| 1600 x 1200       29 Hz |
| 1600 x 1200       30 Hz |
| 1680 x 1050       23 Hz |
| 1680 x 1050       24 Hz |
| 1680 x 1050       25 Hz |
| 1680 x 1050       29 Hz |
| 1680 x 1050       30 Hz |
| 1920 x 1080       23 Hz |
| 1920 x 1080       24 Hz |
| 1920 x 1080       25 Hz |
| 1920 x 1080       29 Hz |
| 1920 x 1080       30 Hz |
| 1920 x 1200       23 Hz |
| 1920 x 1200       24 Hz |
| 1920 x 1200       25 Hz |
| 1920 x 1200       29 Hz |
| 1920 x 1200       30 Hz |
| 1920 x 1440       23 Hz |
| 1920 x 1440       24 Hz |
| 1920 x 1440       25 Hz |
| 1920 x 1440       29 Hz |
| 1920 x 1440       30 Hz |
| 2048 x 1536       23 Hz |
| 2048 x 1536       24 Hz |
| 2048 x 1536       25 Hz |
| 2048 x 1536       29 Hz |
| 2048 x 1536       30 Hz |
| 2560 x 1440       23 Hz |
| 2560 x 1440       24 Hz |
| 2560 x 1440       25 Hz |
| 2560 x 1440       29 Hz |
| 2560 x 1440       30 Hz |
| 2560 x 1600       23 Hz |
| 2560 x 1600       24 Hz |
| 2560 x 1600       25 Hz |
| 2560 x 1600       29 Hz |
| 2560 x 1600       30 Hz |
| 3840 x 2160       23 Hz |
| 3840 x 2160       24 Hz |
| 3840 x 2160       25 Hz |
| 3840 x 2160       29 Hz |
| 3840 x 2160       30 Hz |
| 3840 x 2160       50 Hz |
| 3840 x 2160       59 Hz |
| 3840 x 2160       60 Hz |
| 4096 x 2160       23 Hz |
| 4096 x 2160       24 Hz |
| 4096 x 2160       50 Hz |
| 4096 x 2160       59 Hz |
| 4096 x 2160       60 Hz |
+------------+------------+
```

The game ignores all resolutions below 60 Hz, so that's why you're only seeing these two in the options menu. Are you sure this problem only started after upgrading to re4_tweaks 1.8? We haven't touched that code in a while.
Also, please try changing ``UseVulkanRenderer`` in dinput.ini to ``false``, maybe that could change something.

**Comment by Diegoeo9** [comment]
Hmm, no, its just the 1080 laptop screen and the 4k TV, and It does support 60hz below 4k, but now that you mentioned, the game on the TV defaults at 4k at 30hz? for some reason. (feels laggier at same 60fps). Vulkan doesn't seem to do anything.
Well, not really sure if it is because of the upgrade, but yes, last time I played was when the previous update release, and worked normally, I always play like this. But I could just downgrade replacing for the old 1.7 files to check, right?

**Comment by nipkownix** [comment]
> Hmm, no, its just the 1080 laptop screen and the 4k TV, and It does support 60hz below 4k

Hmm, something might be wrong with your setup, then. Windows is reporting 4 different displays, for some reason.
Before opening the game, are you making the TV your primary/main display in Windows settings?

There's sadly not much more I can do here. Only thing that came to mind is making some changes to allow the game to use refresh rates lower than 60 Hz.

I have something working here:
![image](https://user-images.githubusercontent.com/33870163/210030721-26f3f431-9c17-45db-b47c-9ff0ca6411a4.png)

Each resolution in the menu will display its refresh rate now.

Here's a test build with this change:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10322963/dinput8.zip)

``FixDisplayMode`` must be enabled for this to work, by the way.

**Comment by Diegoeo9** [comment]
It´s a really weird issue, i've tried a loot of things, even previous 1.7 version and its the same. Yes it´s primary, and build works fine, now it lets me change resolutions when on 4k to something below, issue for me is, it´s showing me the same refresh rates u posted above, so no 1080 at 60 hz. 
So, it must be an issue with my setup then, since i discover sometimes even Windows hides 60hz for 1080 on tv (though using another hdmi cable fixes this apparently), the game seems to remember last resolution/hz it used (but no always, just the first time?, then defaults 4k next launch), so sometimes i can play on tv just fine (1080 60hz), even if the menu says otherwise (4k). Bu it´s hard to tell when this game is on 4k or not, most times i can see the scaling happen at launch, and sometimes it feels like its running on 4k (30 fps avg), though the fps are not that low (54 avg), like if its rendering on 4k but displaying at 1080p, :S . Middleground for me right now, its play like that, or use small crappy laptop display :(
But thank you anyway, i can only think of a driver change or something, since it worked pretty normal before.

**Comment by nipkownix** [comment]
Meh, odd. Maybe using [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and reinstalling your GPU drivers from scratch could fix the issue, but I'm really not sure about that, sadly.
