### ISSUE TITLE
Text scaling issues (on Linux?)

### ISSUE THREAD

**Issue by FrozenFish24** [nipkownix/re4_tweaks#414]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Love the project but I'm having issues with the "Press Start", Options menu and other bits of text not scaling correctly. I am running the game on Linux through Proton, googling around it looks like this issue is usually the result of not setting WINEDLLOVERIDES correctly but as you can see in the second screenshot, I am able to bring up the UI.

I've tried messing with the various display tweaks to no success.

![1](https://user-images.githubusercontent.com/12547453/209932492-b9e286a7-55e1-45ba-b669-6512c06be719.jpg)
![2](https://user-images.githubusercontent.com/12547453/209932501-8fdc31fa-421a-43ee-b96f-9335f82a1bcf.jpg)
![3](https://user-images.githubusercontent.com/12547453/209932508-0888cd05-7d8b-4050-87b2-b39760075403.jpg)
![4](https://user-images.githubusercontent.com/12547453/209932512-9d777b44-e364-473b-bb56-11079284db79.jpg)

**Comment by nipkownix** [comment]
Looks like you might be missing a file called ``HDProject.ini`` in ``\Resident Evil 4\Bin32\re4_tweaks\setting_overrides``. Could you check if it is there? If not, just creating an empty one should fix this issue.

**Comment by FrozenFish24** [comment]
That solves it, re4hd's installer would have put this file where it needed to be but then I wiped it when I upgraded to v1.8. Everything looks good now, thanks for the help!
