### ISSUE TITLE
latest update messed the buttons UI

### ISSUE THREAD

**Issue by Hans1Poppof** [nipkownix/re4_tweaks#415]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

hello, after installing the latest update, when playing with my xbox controller, the prompt icons for picking up icons, kicking enemies, etc, are of a playstation, but when reading the files, the instructions correctly show xbox buttons (and the prompts change in real time to pc keys if i press any key on my keyboard), the map ui also shows xbox buttons correctly, what's going on?
![20221229095901_1](https://user-images.githubusercontent.com/62479625/209935990-8120efa7-c42a-4b51-a856-1f6dd5187e10.jpg)

**Comment by nipkownix** [comment]
Hmm, the PlayStation button prompts are a texture mod, re4_tweaks doesn't provide anything like that.
Maybe you've installed the button prompts mod from the RE4 HD Project?
