### ISSUE TITLE
Improving Invincibility

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#417]
### Describe the feature you'd like to see added

Greetings friends. I'm wiring in hopes to get the Trainer Invincibility mode to be a little more functional, as presently there are numerous ways to still take damage when Invincibility is turned on. Some things that could be added:

- dog attacks
- novistador attacks 
- Bear traps
- Errand Grenades (thrown from player)
- Exploding ETM objects (barrels, fire extinguishers)
-Type A AEV damage (Fire in r201)

I am sure there are more I haven't thought of, but that's kind of the gist of it. I believe that Raz0r's trainer covers all these bases so perhaps just looking at what is going on while that is turned on might be helpful. 

Thanks

**Comment by DarthxVoid** [comment]
@Mister-Curious I already liked it because I can test the range of my archers and in addition to testing my AEV damage

**Comment by Mister-Curious** [comment]
I'm not sure I understand what you mean @DarthxVoid . Are you saying you like semi-invincibility? If so, maybe there could be an option for semi-protection vs full protection. The name is misleading, as the player is certainly not invincible. LOL

**Comment by DarthxVoid** [comment]
@Mister-Curious it would be interesting to have 2 types anyway, and yes I like semi-immortality to test the positioning of my archers
And it's not total immortality, I noticed that when we take damage from novistadores or wolves the life bar goes down and dps fills up

**Comment by nipkownix** [comment]
@Mister-Curious, here's a build that implements everything I've mentioned above:

[dinput8-Invincibility.zip](https://github.com/nipkownix/re4_tweaks/files/10327877/dinput8-Invincibility.zip)

Please let me know if everything works fine.
I'd appreciate it if you could do some extensive testing, since this touches quite a bit of code.

**Comment by Mister-Curious** [comment]
Wow man, THANK YOU ! THat was fast!

**Comment by nipkownix** [comment]
Ah, right, raz0r's trainer was doing something else that was a bit harder to spot.
Could you check if this fixes it?

[dinput8-inv.zip](https://github.com/nipkownix/re4_tweaks/files/10353196/dinput8-inv.zip)
