### ISSUE TITLE
Assertion failed!

### ISSUE THREAD

**Issue by RoG-Biohazard** [nipkownix/re4_tweaks#430]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Hello I have the following problem I have Resident Evil 4 on Steam the game version is 1.06 the HD Project is also installed and patched to version 1.1

to the problem

I can't use the latest version of re4_tweak, 1.8. As soon as I replace the data in the Bin32 folder, I get the Assertion failed message when I start it! Program steamapps/common/Resident Evil4/Bin32/DINPUT8.dll
File: D/a/re4_tweaks/external/ModUtils/Patterns.h
line 22

https://files.catbox.moe/5kyfps.rar here my Bio4.exe

**Comment by nipkownix** [comment]
Ah, thanks! I'll look into this as soon as I get home.

**Comment by RoG-Biohazard** [comment]
What I wanted to ask was I downloaded the HD Project back when there was only version 1.0, then at some point version 1.1 came out but I didn't want to download everything again and on the HD Project site there is patch 1.01 for people who already have the version 1.0 installed maybe it could be related to that...

Because I didn't want to download everything again from scratch...

I then went to the HD Project page and saw this HD project 1.0 to 1.1 patch ->HERE (Only if you installed the HD project 1.0 previously and you haven't installed any other people mods) It's 10.6 GB. Sorry! A single texture edit entails an entire room texture pack has to be replaced

When I install the HD Project... then I have version 1.0 and then I have the patch and replace the old data with the new one

**Comment by RoG-Biohazard** [comment]
ok in the moment i redownloading the hole hd project maybe then it works

**Comment by nipkownix** [comment]
Th hd project isn't the issue, the issue is your .exe. It is crashing for me as well. Very weird, as your .exe is also v1.0.6, same version as mine, but yours is different somehow. @emoose, apparently there is yet another 1.0.6 being distributed on steam?

@RoG-Biohazard, your .exe is from Steam, right? Just to make sure.

**Comment by RoG-Biohazard** [comment]
yes its from steam my game version is 1.0.6 but i have the german censored Version without the Mercenaries Mode

**Comment by nipkownix** [comment]
Ahhhh, that explains it. I didn't think the German version had a different .exe. I see now.
Thanks for uploading your .exe here, I'll fix support for it soon!

**Comment by RoG-Biohazard** [comment]
ok thank you ^^

**Comment by RoG-Biohazard** [comment]
So can I use the new re4tweak version 1.8 at some point

**Comment by RoG-Biohazard** [comment]
Its still sad that i have this Censored Game Version without the Mercenaries Mode.....

**Comment by nipkownix** [comment]
I'll release an update soon with support for the German 1.0.6.
But you could also just replace your .exe with another version to have access to the stuff you don't have right now.

Try this one:
[bio4.zip](https://github.com/nipkownix/re4_tweaks/files/10361169/bio4.zip)

**Comment by RoG-Biohazard** [comment]
Thanks for your help ^^

**Comment by nipkownix** [comment]
No problem!
This update should now work with your german exe too:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10361273/dinput8.zip)

**Comment by RoG-Biohazard** [comment]
works thank you for the help ^^

**Comment by emoose** [comment]
Huh, I'd heard the german ver was phased out and all the owners got updated to the normal version, @RoG-Biohazard in case you're still around, was your RE4 install downloaded from steam recently, or was it maybe from an older backup or something?

If Steam is still making some users download that ver I guess we should support it too then, good to see it didn't take too much to add it, guess that's another EXE we'll need to check our changes against :P

**Comment by RoG-Biohazard** [comment]
I bought the game when it came out on Steam

**Comment by RoG-Biohazard** [comment]
Many also said something about buying new on Steam

**Comment by RoG-Biohazard** [comment]
But yes, even if I reinstall the game or download it again, the version remains the same as I never got an update

**Comment by nipkownix** [comment]
Ah, its the same problem I have, then. New German owners probably get ver 1.1.0, while original ones are stuck with the censored 1.0.6.
I'm stuck with 1.0.6 too, but the uncensored one instead.

What a mess they made with versioning... ._.

**Comment by RoG-Biohazard** [comment]
My switch version is also weird because I have the mercenary mode but the easy mode doesn't only have normal and pro

**Comment by RoG-Biohazard** [comment]
and on ps4 its like the pc version without the mercernary mode and with easy normal and professional

**Comment by RoG-Biohazard** [comment]
Why are there so many different versions of the game xD

**Comment by RoG-Biohazard** [comment]
I've also played around with the trainer a bit, but unfortunately I had to find out that when I increase the HP of the opponents, the Verdugo in the sewage system is completely bugged, it just runs against the wall and if I shoot it I shoot into the void :D better me leave it with the change from the HP

**Comment by RoG-Biohazard** [comment]
And when I'm invulnerable, there are sound bugs when an opponent throws an ax or scythe at me
