### ISSUE TITLE
[feature request] change the handgun+silencer text

### ISSUE THREAD

**Issue by juuuulian-s** [nipkownix/re4_tweaks#434]
### Describe the feature you'd like to see added

so in the base game, the examine text for the base handgun with the silencer attached describes it as being fully upgraded and having extra critical chance.
it's pretty clear that this was done to communicate to players that wesker's pistol was fully upgraded, the silencer being rather inconsequential in mercenaries.
now with the hd project adding a secret silencer obtainable in the main game, I think it's best if this examine text gets changed to something else so as not to mislead new players and such.

**Comment by Mister-Curious** [comment]
Edit the MDT file for this weapon and you are good to go. 

https://residentevilmodding.boards.net/thread/9792/re4uhd-mdt-tool-tutorial

**Comment by pas-de-2** [comment]
Good call, this description is confusing and makes the silencer seem very overpowered.

**Comment by juuuulian-s** [comment]
apparently they can check for that and keep the original text for the fully upgraded pistol, leaving wesker's handgun examine text untouched. so, best of both worlds :)

**Comment by albertre4HD** [comment]
If that's the case, that would be great! But while I'm writing these lines, something comes to my mind:... We'd need the translation in French, German, Italian, Spanish, Japanese, Chinese simplified and Chinese traditional, oops!!
