### ISSUE TITLE
"Assertion failed" - The game won't start (Latest Steam Version)

### ISSUE THREAD

**Issue by AndreiD196** [nipkownix/re4_tweaks#449]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Error:
![image](https://user-images.githubusercontent.com/80394743/214084881-388086be-b105-40b3-bc7d-cc1fec4ea5fd.png)
Game Version:
![image](https://user-images.githubusercontent.com/80394743/214085143-c3e94210-2226-40bb-a885-9b20814176a2.png)

I set the dinput8.log too be verbose, still didn't find an error in the logs. However it seems that version 1.0.6 should be 1.0.18384.1, while my version is 1.0.18384.2

**Comment by nipkownix** [comment]
Do you happen to have the censored German build of the game?

**Comment by nipkownix** [comment]
That's odd. I don't think there have been any updates.
Can you please zip your bio4.exe and upload it here so I can take a look?

**Comment by nipkownix** [comment]
Looks like you have the German version. You can confirm it by checking if The Mercenaries is missing from the extras:

![image](https://user-images.githubusercontent.com/33870163/214135017-2d505760-1be9-49d2-8121-a5d2a18c6ba2.png)

I've recently fixed compatibility with the German .exe, but I haven't made a new release yet.

This development build should work fine, though:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10483161/dinput8.zip)

Btw, where are you from? Did you buy the game from the Steam store? AFAIK this censored .exe was only distributed with German copies of the game. Hmm.
