### ISSUE TITLE
Binocular zoom has almost no blur when using mousewheel

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#45]
Some reason using mouse scrollwheel to zoom the binoculars only results in very minor blurring, while controller has a much stronger effect, must be something to do with how the mousewheel zoom was implemented - seems mousewheel makes it snap to different zoom levels, while controller stick lets it go smoothly between them.

I guess blurring effect is kept active while controller is going between them until controller stick is released, while with mousewheel maybe it's being treated as "released" as soon as it's snapped to a level, not really sure how much could be done to improve this, if anyone has any ideas please let me know.

**Comment by nipkownix** [comment]
It is the call to `FocusAnimation::move` at the end of `CameraScope::move`.
It is testing for some value to know weather the focus should be happening or not. 
It seems that, with a controller, the value it is testing against gets enabled as soon as you push the stick and stays on for a set period of time, regardless of weather or not you're still holding the analog stick in position.
With the mouse, that value resets as soon as the wheel completes a "cycle", so that's why the focus animation stops quickly and we end up with a softer effect.

Haven't found a clean way to improve this yet. Hmm.

**Comment by nipkownix** [comment]
It is the call to FocusAnimation::move at the end of CameraScope::move.
That section is testing for some value to know whether the focus should be happening or not.
It seems that, with a controller, the value it is testing against gets enabled as soon as you push the stick and stays on for a set period of time, regardless of whether or not you're still holding the analog stick in position.
With the mouse, that value resets as soon as the wheel completes a "cycle", so that's why the focus animation stops quickly and we end up with a softer effect.

Haven't found a clean way to improve this yet. Hmm.

**Comment by emoose** [comment]
Looks like the value being tested in `CameraScope::move` is something time related, at least it seems to do something with `pG->deltaTime` to set it earlier in the func, while the second param to `FocusAnimation::move` is a bool to enable/disable the effect.

Could be that the time value is only being changed when controller is used, letting it countdown & stay active after it's released, while kb/m doesn't update it, so the effect is disabled almost instantly, not sure though.

**Comment by emoose** [comment]
Seems part of the code that used `pG->deltaTime` multiplies something against 0xC63011, that byte seems to be RS Y axis as a signed int8, looks like there's a deadzone there before the value changes and game zooms the screen & applies blur.

The KB+M code also seems to change that 0xC63011 byte, but for some reason the byte only changes when scrollwheel is changed a lot, small changes don't seem to affect the byte, but do still zoom in the screen.

Kinda seems like there might still be some deadzone applying to scrollwheel which makes it so that only large scrollwheel changes actually get used to calculate blur strength, but not sure how zoom still gets applied though.

**Comment by nipkownix** [comment]
Added something that appears to be working pretty nicely in 04400fccd3.

Let me know what you think.

**Comment by emoose** [comment]
Hm, I think there's an improvement there, but it still doesn't seem to apply the blur in some cases, eg. I'd expect 1 click of the mouse-wheel to zoom it in & apply slight blur while it happens, but doesn't seem any blur is applied at all, only seems to apply blur when I move scrollwheel a bunch of clicks at once.

Controller on the other hand seems to apply blur no matter how little you push it, the zoom factor on the side also goes up in smaller steps with controller, maybe related to it somehow:

Here's an example with controller with very light stick movement:

https://user-images.githubusercontent.com/1755499/151244460-df9dfc6e-f388-4a4c-b4dc-be56dec048f4.mp4

and with mouse, trying to move it at around the same speed:

https://user-images.githubusercontent.com/1755499/151244541-019a767f-c07e-445f-8230-f314ce24f40e.mp4

**Comment by nipkownix** [comment]
Hmm, the sniper rifle has smaller zoom steps, so the fix does look better there, but a single scroll of the mouse wheel is indeed not triggering the effect. Hmm.

**Comment by emoose** [comment]
Ohh I just realized your fix is `FixSniperZoom`, but I'm testing with binoculars, looks like binoculars has its own `CameraBinocular::move` function which is similar to `CameraScope::move`, maybe binoculars would also need another hook in place for that func too.

**Comment by nipkownix** [comment]
> E: oh nvm, looks like your hook is for FocusAnimation::move which both binocular & scope make use of.

Yeah, that's right. I assumed the result would end up looking similar for both of them, but the binocular one needs less "scrolls" to move faster. 
Haven't found out excatly why fewer scrolls don't trigger the effect :/

**Comment by emoose** [comment]
Added some extra structs & names around the `CameraBinocular`/`CameraScope`/`FocusAnimation` etc classes to latest IDB, hopefully might help with looking into it: https://github.com/emoose/re4-research/issues/1

**Comment by emoose** [comment]
The code around 0x9692AB seems to be what converts scroll-wheel into RS input, the `push 7F` there is basically setting RS as 0x7F (fully pressed up), while 0x9692D6 sets it as -0x7F (fully down), looks like that value is passed to some min/max function to make sure it's between -0x7F-0x7F (which seems pointless since it's hardcoded...), then stored at 0xC63011 signed byte.

Halving the values it pushes there makes the bino zoom in much smaller steps, but blur doesn't really seem affected... seems this is maybe only converting it to the RS input for a single frame, and maybe blur code wants it to have several frames of input, might explain why scrolling multiple clicks allows blur to be activated too, since those would let the RS input get changed for more than 1 frame.

**Comment by nipkownix** [comment]
>Added some extra structs & names around the CameraBinocular/CameraScope/FocusAnimation etc classes to latest IDB, hopefully might help with looking into it: emoose/re4-research#1 (comment)

Ah, thank you!

Hmm, I think I have an ugly workaround in mind. Let me see if it works properly.

**Comment by emoose** [comment]
Wow that works great, excellent work! Pretty much how I hoped it would be.

I do still wonder about making the wheel->RS work over multiple frames though, instead of snapping to each position, might try looking into that some time, for now I guess this issue is fixed though :)

**Comment by nipkownix** [comment]
I also have another of my _ugly hack_ ideas to smoothen the zoom with the mouse.
I'll let you know if it works decently enough.
