### ISSUE TITLE
Game crashes on launch.

### ISSUE THREAD

**Issue by thehunnicmenace** [nipkownix/re4_tweaks#456]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

The game crashes right after I launch it. I'm playing on steam by the way.

I don't know if this will shed more light into what's going on.. but here are some details:

I had some problems with slowdowns in certain areas (this happened with and without re4 tweaks). I didn't mind initially, since it would rarely happen. But as I continued to play, it would happen more and more before El Gigante (I would fix this in the merchant area located right after the area where you encounter him for the first time).

I figured I expected too much from my PC, but I noticed that it would also happen in deserted areas too (merchant area).

So I tried updating my graphics card drivers (GTX 1050) and that was it (I updated it and then launched the game).
Constant 60. 
I played a lot after that and got to the castle. Saved the game. Turned off my PC. Next day, it would start to crash on launch.

The re4 icon appears for about 1 sec on my toolbar (windows10), but that’s as far as I can get.

I'm playing re4 for the first time and I'm loving it. Thank you for offering us help and just extremely improving my experience.
[bio4.exe.20230125125049.zip](https://github.com/nipkownix/re4_tweaks/files/10503277/bio4.exe.20230125125049.zip)

**Comment by emoose** [comment]
Crash looks vulkan related, not really sure what the cause is though, but maybe see if editing `dinput8.ini` and changing `UseVulkanRenderer = true` to false at the top can let it launch for you.

**Comment by thehunnicmenace** [comment]
Jackpot! It's working again, thanks!
