### ISSUE TITLE
Crack

### ISSUE THREAD

**Issue by Ghosta30** [nipkownix/re4_tweaks#479]
### Describe the feature you'd like to see added

Is re4_tweeks work on re4 uhd crack or no?

**Comment by Ghosta30** [comment]
The game version is v1.06

**Comment by LethalPlacebo** [comment]
It might work, it might not, but if it doesn't the developers do not support the cracked versions, as there are too many different versions of RE4. You can read this in the pinned post on the Issues page.

**Comment by Ghosta30** [comment]
@LethalPlacebo but my version is the supported one and it's not working

**Comment by LethalPlacebo** [comment]
@Ghosta30 It's still a cracked version. Which means that something about the exe must have been changed (aside from the crack) if it's not working. This is why cracked versions aren't supported.

**Comment by ElTioRata** [comment]
If you're talking about The Scene release by PROPHET, nope.

**Comment by Ghosta30** [comment]
@LethalPlacebo the old versions are working but the 1.8 is not

**Comment by nipkownix** [comment]
No support for cracked versions. Besides, if 1.8 isn't working, your issue may be related to Vulkan/DXVK, so disabling the Vulkan renderer might or might not help.
