### ISSUE TITLE
Crash opening options from main menu

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#48]
Using latest 1.7.2 release with the included dinput8.ini & clean 1.1.0 bio4.exe, game crashes when opening options menu - removing dinput8.dll allows it to open it fine though, so don't think it's an issue with my games config.ini or anything.

Log file:
[bio4.exe.20220129221113.log](https://github.com/nipkownix/re4_tweaks/files/7964858/bio4.exe.20220129221113.log)

Seems to be something to do with the resolution chooser again, I used NV control panel to add 90Hz option for my resolution, so I have both 90Hz & 60Hz for the same res, maybe that's something to do with it (my desktop is at 90Hz, but maybe it's only exposing 60Hz to D3D or something weird)

**Comment by nipkownix** [comment]
Oh boy.
I'll see if I can create a virtual display to reproduce the crash. My actual monitor can't handle anything above 63Hz or so :/

But 144Hz did work when I first tried this. Not sure what could be wrong now.

**Comment by emoose** [comment]
Have you tried it with 63Hz in game? If your desktop is running at 63Hz maybe that's enough for it to trigger the crash, if it is an issue with desktop & D3D having a mismatch.

**Comment by nipkownix** [comment]
Hmm, weird. Tried both with 63Hz on my real monitor and with 90Hz on my fake monitor. No crashes here.

**Comment by emoose** [comment]
Probably should have mentioned but I have two monitors connected - unplugged one of them, and the crash went away, weird. Could it be using EnumDisplayModes on the wrong monitor maybe? Only one of them had 90Hz custom resolution added (both are same resolution besides that)

**Comment by nipkownix** [comment]
Ah, two monitors? Time for me to create another virtual display then

**Comment by emoose** [comment]
Wrote a quick app to run EnumAdapterModes, and seems 90Hz modes are missing for adapter 0...

```
#0 - 640x480@59
#1 - 640x480@60
#2 - 720x480@59
#3 - 720x480@60
#4 - 720x576@59
#5 - 720x576@60
#6 - 800x600@59
#7 - 800x600@60
#8 - 1024x768@59
#9 - 1024x768@60
#10 - 1152x864@59
#11 - 1152x864@60
#12 - 1280x720@59
#13 - 1280x720@60
#14 - 1280x768@59
#15 - 1280x768@60
#16 - 1280x800@59
#17 - 1280x800@60
#18 - 1280x960@59
#19 - 1280x960@60
#20 - 1280x1024@59
#21 - 1280x1024@60
#22 - 1360x768@59
#23 - 1360x768@60
#24 - 1366x768@59
#25 - 1366x768@60
#26 - 1600x900@59
#27 - 1600x900@60
#28 - 1600x1024@59
#29 - 1600x1024@60
#30 - 1600x1200@59
#31 - 1600x1200@60
#32 - 1680x1050@59
#33 - 1680x1050@60
#34 - 1920x1080@59
#35 - 1920x1080@60
#36 - 1920x1200@59
#37 - 1920x1200@60
#38 - 1920x1440@59
#39 - 1920x1440@60
#40 - 2560x1440@59
#41 - 2560x1440@60
```

Strangely it seems adapter 0 is actually my 90Hz display though, using adapter 1 it gives portrait resolutions since the non-90Hz screen is in portrait.

No idea why D3D isn't seeing the 90Hz display... I guess this shows there is a chance the desktop refresh rate & the d3d rates could be different though, maybe need to add something to handle that somehow.

**Comment by nipkownix** [comment]
I see.

>No idea why D3D isn't seeing the 90Hz display... 

Could this be due to how nvidia is forcing the non-standard refresh rate? If so, no one with a "normal" setup should face this issue.

>E: hmm.. this doesn't explain why unplugging second monitor stopped it from crashing though, even with it unplugged I get the same modes from EnumAdapterModes... how does the game work with that though? strange.

Could the game be trying to run EnumAdapterModes on the secondary monitor instead of the first one? If so, this would end up making the list empty since it is then looking for resolutions with `g_UserRefreshRate`, and those are only available in the first monitor.

Would explain why some people actually fix the black screen issue by simply plugging in a 60Hz monitor. And we're just doing.. the inverse, I guess.

**Comment by emoose** [comment]
Yeah it seems to be an NV issue... using NV custom resolutions isn't a normal setup, but I know there's a bunch of guides around for using NVCP to overclock to higher refresh rates, so most likely will be others that run into this eventually.

Don't really think the second monitor is related with this, neither adapters seemed to include the 90Hz mode anyway, I guess NV just isn't setting D3D9 modes up properly for it (I do remember some other games having issues with this too).

Only way I can think of for getting around this would be to maybe ignore refresh rate in the func that populates the resolution list - I don't really think refresh rate is that important for that code anyway, seems like they might have only limited it to 60Hz there to prevent duplicates (since some people have both 59 & 60 modes for the same resolutions), could be wrong though.

Would probably need to reimplement that func so it could check for dupe width/height combinations instead though... luckily it's not too complex, maybe will try looking into it soon.

**Comment by emoose** [comment]
Oh wow, the game actually already has code for checking by width/height instead of refresh rate, but it's unused :o

The check at 0x953513 is checking if a2 == true, but none of the calls to that func set that to true, changing that jnz to jmp instead lets it check for dupes properly, with that it seems to work with 90Hz fine!

**Comment by nipkownix** [comment]
Nice find!

>Wonder why they left that unused.

I mean, why even force 60Hz in the first place? Makes no sense at all. I mean, Q-LOC isn't really _incompetent_, but I really don't understand what they were thinking here.
