### ISSUE TITLE
1.8 update issue 

### ISSUE THREAD

**Issue by Ghosta30** [nipkownix/re4_tweaks#481]
### Validation

- [x] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

All old versions it's work on cracked but the new one not working

**Comment by nipkownix** [comment]
No support for cracked versions.
