### ISSUE TITLE
RE4HD crash on launch

### ISSUE THREAD

**Issue by kuhchung** [nipkownix/re4_tweaks#490]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Base game installation, launch crashes.
Installed latest RE4HD from torrent that also pulls RE4_tweaks, crashes. Both with Vulkan = true or false. Attaching crashdumps.
[bio4.exe.20230316101948.zip](https://github.com/nipkownix/re4_tweaks/files/10994529/bio4.exe.20230316101948.zip)
[bio4.exe.20230316101907.zip](https://github.com/nipkownix/re4_tweaks/files/10994530/bio4.exe.20230316101907.zip)

**Comment by emoose** [comment]
Looks like crash is something to do with Intel graphics drivers, do you have a dedicated GPU in your machine? If not then another user did report updating their Intel drivers helped them, maybe see if there's any update available for yours.

**Comment by kuhchung** [comment]
Omg thanks so much. Windows told me it was up to date but the driver was actually two years old. Installing manually from manufacturer fixed it.

Sorry to waste your time on this. Thanks so much for the fantastic work!
