### ISSUE TITLE
1.8 Update - Can't access some features. 

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#494]
_"Note: This update changed some sections of the .ini structure, so you will notice that some of your existing settings will revert to default."_
 
 So I  noticed after installing 1.8 a a few things no longer work and I am at a loss of how to fix them. Here is a list:
 
 - `UseSprintToggle = true` isn't working. I have it set to true in:
\Resident Evil 4\Bin32\re4_tweaks\default_settings\ **settings.ini**
\Resident Evil 4\Bin32\re4_tweaks\setting_overrides \ **REmixTweaks.ini**

- `SkipMenuFades = true` doesn't seem to be working either. I have it set to true in:
\Resident Evil 4\Bin32\re4_tweaks\default_settings\ **settings.ini** 

I'm pretty sure my setting overrides **REmixTweaks.ini** file is working because `SkipIntroLogos = true` is set there, but in the **settings.ini**  it is set to false. 

EDIT - I got the above features to work by activating them in-game menu, but this all leads me to ask. What file is being written to and read from? If I changed these settings in the ini files, and they weren't read, I must have something in the wrong place, or some file is overriding another. I'm not sure how things work now that things have been changed. There is the **xinput1_3.ini** file in the Bin32 folder, but are we supposed to get rid of this now since there is the \Resident Evil 4\Bin32\re4_tweaks\default_settings\ **settings.ini**  file?

Sorry I'm confused ! I disabled the **xinput1_3.ini** file in the Bin32 folder, but that didn't help.

**Comment by emoose** [comment]
The `xinput1_3.ini` in the Bin32 folder is the user settings, the changes you make in the re4_tweaks menu are read/written there, IIRC the `re4_tweaks\default_settings\settings.ini` is just copied over to that when the xinput1_3.ini doesn't exist.

Adding it to `Bin32\re4_tweaks\setting_overrides\REmixTweaks.ini` should override both really, but maybe there's some issue with that somehow, possible only the xinput1_3.ini value is actually being applied & the one from override isn't making any change.

Are you sure the setting in your `REmixTweaks.ini` is named correctly & in the proper section for that tweak? (`UseSprintToggle` should be inside `[GAMEPLAY]`, and `SkipMenuFades` should be in `[MISC]`)

Also does the log file mention that it's reading from REmixTweaks.ini?

**Comment by Mister-Curious** [comment]
@emoose thanks for taking the time to create a roadmap for me. I'm not sure what happened. While I have your attention here, can you confirm that invincibility is working in 1.8. It isn't working for me, and Im not sure if it has to do with these ini files that got messed up.

**Comment by Mister-Curious** [comment]
Ok Im totally confused. Invincibility still isnt working, so I totally reinstalled RE4Tweaks (deleted everything except I kept my REmix.ini). What is going on ?

**Comment by Mister-Curious** [comment]
Sorry for all the confusion, and thanks for all the help. I will mark this as closed as things are ok now.
