### ISSUE TITLE
ShowGameOutput causing crashes

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#496]
Issue with:

`ShowGameOutput= True`

When I set this in the `xinput1_3.ini` file game wont load into some rooms. It works ok if I set it in the in-game display (F1), but otherwise its very unstable. Getting endless messages about:

`cLog::err: Flag: 4, errId: 0, Message: ITEM SET[8] failed: ETC[0] not found`

[bio4.exe.20230319024517.zip](https://github.com/nipkownix/re4_tweaks/files/11010623/bio4.exe.20230319024517.zip)

**Comment by nipkownix** [comment]
Which room causes this log spam? I'm trying to reproduce the issue.

**Comment by Mister-Curious** [comment]
@nipkownix thank you for checking into this. The CrashDump I sent was created while in r109. While running some more tests this morning I couldn't even get CrashDumps to get created. 

I tried to attach an ESL file here for you to use (zipped, but GH wont let me send it). Its just two enemies, so you can create the file with just pasting this in a new file and saving extension as `.esl:`

`01 6B 0C 00 00 00 00 00 F4 01 00 01 4C 16 EA 00 07 01 00 00 52 21 00 00 09 01 00 00 00 00 00 00 01 B6 0C 00 00 00 00 00 F4 01 00 01 58 16 EA 00 5B 00 00 00 FF 1F 00 00 09 01 00 00 00 00 00 00` (you could always just paste this into an existing file as well). 

1-  Open Tweaks and make sure `ShowGameOutout` is enabled
2 - Sideload the ESL file, or just edit your ESL to have the same enemy combination seen in my ESL.
3 - Start new game then debug jump to r109
4 - Go to where the two enemies are spawned and created save.
5 - Exit game, restart, and load save. 

What's interesting here is that:
- this will not crash if we use different ESL IDs like 12 00, or 13 00
- this will not crash (using the provided ESL IDs) if `ShowGameOutout` is disabled. 
- this will not crash (using the provided ESL IDs) if `ShowGameOutout` is enabled, but we don't load from save. 

So you can see there are a variety of ways to make this work, BUT determining the actual culprit seems weird considering there are different was to make it work. 

Thank you.

**Comment by Mister-Curious** [comment]
ok finally got things a little more stable here, but I cant really test this because the `ShowGameOutput` setting wont save, and I need it on before I load the room. ANyways, I was investigating some of the logs after turning it on in-game, and finally got a crash log that I am sure will show something about the `ShowGameOutput` . (see attached)

In the room I am testing in (r109),. I am getting endless messages in the console about:

**cLog::err: Flag: 4, errId: 0, Message: ITEM SET[-34] failed: ETC[60] not found**

There are so many of these messages that I can't read the rest of the log as the stream is so fast. Ive nulled the ITM, ITA, ETM, ETS and ESL just to see , but its persistent


[bio4.exe.20230320230857.zip](https://github.com/nipkownix/re4_tweaks/files/11025399/bio4.exe.20230320230857.zip)
