### ISSUE TITLE
Game screen turns green 

### ISSUE THREAD

**Issue by MetalGearAlex1** [nipkownix/re4_tweaks#51]
![20220201_192109](https://user-images.githubusercontent.com/60905632/152076686-b6f06d52-3064-4cab-b220-d0d957db9efa.jpg)

My screen turns green after following directions. It was normal before doing it. I have an msi 65 stealth with a 2070 graphics card i9 i believe. Please help. Conment on my twitter so i can see the response. Thanku

https://twitter.com/UnMetalAlex/status/1488669301464834048?t=Td8X-hUn7ilUOWiQJ1L-Ug&s=19

**Comment by MetalGearAlex1** [comment]
![20220201_201645](https://user-images.githubusercontent.com/60905632/152078293-08b12853-9256-4218-ad72-32b82a17b959.jpg)
![20220201_201648](https://user-images.githubusercontent.com/60905632/152078307-592ccafb-737c-4a5f-973c-fe95dad1e1d6.jpg)
I even self patch the 4gigs to see if that would fix it and changed my nvidia settings back to balanced. Plz help

**Comment by MetalGearAlex1** [comment]
![20220201_203223](https://user-images.githubusercontent.com/60905632/152079468-bbb74c63-cb81-419b-9497-09f799ccf5a4.jpg)

Showing that it is normal before i do all the changes. And that i did download ur 1.0 version 18 part rar and opened successfully with password. 
![20220201_203442](https://user-images.githubusercontent.com/60905632/152079695-794b253e-f63c-47c8-9603-5c4dc0da0f2a.jpg)

**Comment by nipkownix** [comment]
Can you try replacing "dinput8.dll" with this new one?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/7983011/dinput8.zip)

This one has the config menu turned off, just in case ImGui is the issue. That's the only possible cause I can think of :/

**Comment by MetalGearAlex1** [comment]
> Can you try replacing "dinput8.dll" with this new one? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/7983011/dinput8.zip)
> 
> This one has the config menu turned off, just in case ImGui is the issue. That's the only possible cause I can think of :/

Ok. I will try and report back. Thank you.

**Comment by MetalGearAlex1** [comment]
> Can you try replacing "dinput8.dll" with this new one? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/7983011/dinput8.zip)
> 
> This one has the config menu turned off, just in case ImGui is the issue. That's the only possible cause I can think of :/

Unfortunately it still turns green. I delete bio4 before putting in new one. I copy/paste into the bin32 thingy before doing the bio4. Even had to exclude Norton from deleting the dll8 thing. Plz help. I think i have a pretty good gaming laptop

**Comment by nipkownix** [comment]
If you delete dinput8.dll and open the game, is it still green?

**Comment by MetalGearAlex1** [comment]
> If you delete dinput8.dll and open the game, is it still green?

Yes. No longer green. Thank you. What does dinput8 dll supposed to do? Id like to know. Thanku

**Comment by nipkownix** [comment]
Deleting it isn't a solution, sadly. The HD project needs it to fix a bunch of limitations of the original game.

**Comment by MetalGearAlex1** [comment]
New issue. Plz dont close. Now when i press start to play. New game. I picked Easy. It just closes out! Whole game stops

**Comment by nipkownix** [comment]
Yeah, that's because you need dinput8 for the game to work :/

Can you see if this version works?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/7983072/dinput8.zip)

**Comment by MetalGearAlex1** [comment]
> Yeah, that's because you need dinput8 for the game to work :/
> 
> Can you see if this version works? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/7983072/dinput8.zip)

Unfortunately not. Still nice and green. I dont want to play Matrix Evil 4. I am very patient. I did wait 8 years after all for this. I am so close i can taste it. Should i delete dinput8.ini and only keep ur dinput8.dll ? Is it a possible conflict with nvidia gsync?

**Comment by MetalGearAlex1** [comment]
Wait a second. On my computer screen its normal. But not on my lg cx . I just checked. I have the latest in hd cord 2.1 4k. So idk.

**Comment by laymonage** [comment]
I'd suggest turning off each setting in the .ini one by one (especially the ones that are related to display) and retry the game every time you disable a setting. Might help to locate which tweak caused the issue.

**Comment by nipkownix** [comment]
> Should i delete dinput8.ini and only keep ur dinput8.dll

No, you should have both.

>Wait a second. On my computer screen its normal. But not on my lg cx . I just checked. I have the latest in hd cord 2.1 4k. So idk.

hmm, try changing "FixDisplayMode" to "false" in the .ini file.

**Comment by MetalGearAlex1** [comment]
Ok. That worked. I even did it with the original dinput8.ini using Notepad+

**Comment by MetalGearAlex1** [comment]
What does turning it false do?

**Comment by MetalGearAlex1** [comment]
One more question. I forgot how to quit game without shift tabbing force quit

**Comment by nipkownix** [comment]
>Ok. That worked. I even did it with the original dinput8.ini using Notepad+

Oh, nice. If you use the original dinput8.dll file from the HD project, with "FixDisplayMode" set to false, it still works, right?

That option makes the game run on non-60Hz mointors. Not sure why it would cause the game to be green for some reason. Maybe the game is picking up some display mode that doesn't work correctly with your TV or something like that?

>One more question. I forgot how to quit game without shift tabbing force quit

You press ESC when in-game, then click on "retry or load". There will be an option to return to the main menu. From there, you can quit the game.

**Comment by MetalGearAlex1** [comment]
Ok. I can also redo everything from start just to verify all this. So give me a second. Thankyou. And i am happy now. Im glad to have been the oddball in the situation cause im pretty tech handy.

**Comment by MetalGearAlex1** [comment]
Alright. New update. If i only have my computer display off and tv display 2 on. Then i dont need to change anything. Very odd.  But if i use  both displays (not extended) i have to turn that option to False in notepad+

**Comment by nipkownix** [comment]
I see. Well, at least we have a workaround untill we can figure out why that happens.

Thank you for reporting the issue!

**Comment by MetalGearAlex1** [comment]
> 

Thankyou greatly for ur work. U know this game hd redo is good when it looks exactly like the original (but better)

**Comment by emoose** [comment]
>Maybe the game is picking up some display mode that doesn't work correctly with your TV or something like that?

That's the only thing I can think of too - one of my worries with the FixDisplayModes patches was something like that could happen, didn't think we'd see it so soon though.

@MetalGearAlex1 if you're still around (or if anyone else has an issue like this), could you try running this EXE while connected to your TV, and then open the modes.txt file it creates & copy contents here?

[D3D9Adapters.zip](https://github.com/nipkownix/re4_tweaks/files/7987297/D3D9Adapters.zip)

**Comment by MetalGearAlex1** [comment]
> 

Ok. I will give it a try. I will go to 1/2 display setting and do what u said. I just left it display 2 only to avoid the green screen. I will let u know in about an hour or sooner if thats ok.

**Comment by MetalGearAlex1** [comment]
Im gonna go do it now. But what is ironic about all this is i opened up a github account to find fixes for the pcsx2 regarding Resident Evil 4 many years ago. I feel honored to be the test subject again.

**Comment by MetalGearAlex1** [comment]
> > Maybe the game is picking up some display mode that doesn't work correctly with your TV or something like that?
> 
> That's the only thing I can think of too - one of my worries with the FixDisplayModes patches was something like that could happen, didn't think we'd see it so soon though.
> 
> @MetalGearAlex1 if you're still around (or if anyone else has an issue like this), could you try running this EXE while connected to your TV, and then open the modes.txt file it creates & copy contents here?
> 
> [D3D9Adapters.zip](https://github.com/nipkownix/re4_tweaks/files/7987297/D3D9Adapters.zip)

couldn't click on exe while ingame. don't know how to minimize but this is what text shows normally before.

#0 - 640x480@120
#1 - 640x480@59
#2 - 640x480@60
#3 - 640x480@119
#4 - 640x480@100
#5 - 720x480@120
#6 - 720x480@60
#7 - 720x480@59
#8 - 720x480@100
#9 - 720x480@119
#10 - 800x600@120
#11 - 800x600@60
#12 - 800x600@119
#13 - 800x600@100
#14 - 1024x768@120
#15 - 1024x768@60
#16 - 1024x768@119
#17 - 1024x768@100
#18 - 1152x864@120
#19 - 1152x864@60
#20 - 1152x864@119
#21 - 1152x864@100
#22 - 1176x664@50
#23 - 1176x664@60
#24 - 1176x664@59
#25 - 1280x720@120
#26 - 1280x720@60
#27 - 1280x720@59
#28 - 1280x720@50
#29 - 1280x720@100
#30 - 1280x720@119
#31 - 1280x800@120
#32 - 1280x800@60
#33 - 1280x800@119
#34 - 1280x800@100
#35 - 1280x960@120
#36 - 1280x960@60
#37 - 1280x960@119
#38 - 1280x960@100
#39 - 1280x1024@120
#40 - 1280x1024@60
#41 - 1280x1024@119
#42 - 1280x1024@100
#43 - 1366x768@120
#44 - 1366x768@60
#45 - 1366x768@59
#46 - 1366x768@50
#47 - 1366x768@24
#48 - 1366x768@23
#49 - 1366x768@25
#50 - 1366x768@30
#51 - 1366x768@29
#52 - 1366x768@119
#53 - 1366x768@100
#54 - 1600x1024@120
#55 - 1600x1024@60
#56 - 1600x1024@59
#57 - 1600x1024@50
#58 - 1600x1024@24
#59 - 1600x1024@23
#60 - 1600x1024@25
#61 - 1600x1024@30
#62 - 1600x1024@29
#63 - 1600x1024@119
#64 - 1600x1024@100
#65 - 1680x1050@120
#66 - 1680x1050@60
#67 - 1680x1050@59
#68 - 1680x1050@50
#69 - 1680x1050@24
#70 - 1680x1050@23
#71 - 1680x1050@25
#72 - 1680x1050@30
#73 - 1680x1050@29
#74 - 1680x1050@119
#75 - 1680x1050@100
#76 - 1920x1080@120
#77 - 1920x1080@60
#78 - 1920x1080@59
#79 - 1920x1080@50
#80 - 1920x1080@24
#81 - 1920x1080@23
#82 - 1920x1080@25
#83 - 1920x1080@30
#84 - 1920x1080@29
#85 - 1920x1080@119
#86 - 1920x1080@100
#87 - 3840x2160@60
#88 - 720x576@120
#89 - 720x576@50
#90 - 720x576@100
#91 - 720x576@119
#92 - 320x200@60
#93 - 320x200@144
#94 - 320x240@60
#95 - 320x240@144
#96 - 400x300@60
#97 - 400x300@144
#98 - 512x384@60
#99 - 512x384@144
#100 - 640x400@60
#101 - 640x400@144
#102 - 640x480@144
#103 - 800x600@144
#104 - 1024x768@144
#105 - 1152x864@144
#106 - 1280x600@60
#107 - 1280x600@144
#108 - 1280x720@144
#109 - 1280x768@60
#110 - 1280x768@144
#111 - 1280x800@144
#112 - 1280x960@144
#113 - 1280x1024@144
#114 - 1360x768@60
#115 - 1360x768@144
#116 - 1366x768@144
#117 - 1400x1050@60
#118 - 1400x1050@144
#119 - 1440x900@60
#120 - 1440x900@144
#121 - 1600x900@60
#122 - 1600x900@144
#123 - 1680x1050@144
#124 - 1920x1080@144

**Comment by MetalGearAlex1** [comment]
this is when it's on tv only display 2.. when it doesn't turn green.

#0 - 640x480@120
#1 - 640x480@59
#2 - 640x480@60
#3 - 640x480@119
#4 - 640x480@100
#5 - 720x480@120
#6 - 720x480@60
#7 - 720x480@59
#8 - 720x480@100
#9 - 720x480@119
#10 - 800x600@120
#11 - 800x600@60
#12 - 800x600@119
#13 - 800x600@100
#14 - 1024x768@120
#15 - 1024x768@60
#16 - 1024x768@119
#17 - 1024x768@100
#18 - 1152x864@120
#19 - 1152x864@60
#20 - 1152x864@119
#21 - 1152x864@100
#22 - 1176x664@50
#23 - 1176x664@60
#24 - 1176x664@59
#25 - 1280x720@120
#26 - 1280x720@60
#27 - 1280x720@59
#28 - 1280x720@50
#29 - 1280x720@100
#30 - 1280x720@119
#31 - 1280x800@120
#32 - 1280x800@60
#33 - 1280x800@119
#34 - 1280x800@100
#35 - 1280x960@120
#36 - 1280x960@60
#37 - 1280x960@119
#38 - 1280x960@100
#39 - 1280x1024@120
#40 - 1280x1024@60
#41 - 1280x1024@119
#42 - 1280x1024@100
#43 - 1366x768@120
#44 - 1366x768@60
#45 - 1366x768@59
#46 - 1366x768@50
#47 - 1366x768@24
#48 - 1366x768@23
#49 - 1366x768@25
#50 - 1366x768@30
#51 - 1366x768@29
#52 - 1366x768@119
#53 - 1366x768@100
#54 - 1600x1024@120
#55 - 1600x1024@60
#56 - 1600x1024@59
#57 - 1600x1024@50
#58 - 1600x1024@24
#59 - 1600x1024@23
#60 - 1600x1024@25
#61 - 1600x1024@30
#62 - 1600x1024@29
#63 - 1600x1024@119
#64 - 1600x1024@100
#65 - 1600x1200@120
#66 - 1680x1050@120
#67 - 1680x1050@60
#68 - 1680x1050@59
#69 - 1680x1050@50
#70 - 1680x1050@24
#71 - 1680x1050@23
#72 - 1680x1050@25
#73 - 1680x1050@30
#74 - 1680x1050@29
#75 - 1680x1050@119
#76 - 1680x1050@100
#77 - 1920x1080@120
#78 - 1920x1080@60
#79 - 1920x1080@59
#80 - 1920x1080@50
#81 - 1920x1080@24
#82 - 1920x1080@23
#83 - 1920x1080@25
#84 - 1920x1080@30
#85 - 1920x1080@29
#86 - 1920x1080@119
#87 - 1920x1080@100
#88 - 1920x1200@120
#89 - 1920x1440@120
#90 - 2048x1536@60
#91 - 2048x1536@59
#92 - 2048x1536@50
#93 - 2048x1536@24
#94 - 2048x1536@23
#95 - 2048x1536@25
#96 - 2048x1536@30
#97 - 2048x1536@29
#98 - 2560x1440@120
#99 - 2560x1600@60
#100 - 2560x1600@59
#101 - 2560x1600@50
#102 - 2560x1600@24
#103 - 2560x1600@23
#104 - 2560x1600@25
#105 - 2560x1600@30
#106 - 2560x1600@29
#107 - 3840x2160@60
#108 - 3840x2160@59
#109 - 3840x2160@50
#110 - 3840x2160@120
#111 - 3840x2160@119
#112 - 3840x2160@100
#113 - 3840x2160@24
#114 - 3840x2160@23
#115 - 3840x2160@25
#116 - 3840x2160@30
#117 - 3840x2160@29
#118 - 4096x2160@60
#119 - 4096x2160@59
#120 - 4096x2160@50
#121 - 4096x2160@120
#122 - 4096x2160@119
#123 - 4096x2160@100
#124 - 4096x2160@24
#125 - 4096x2160@23
#126 - 4096x2160@25
#127 - 4096x2160@30
#128 - 4096x2160@29
#129 - 720x576@120
#130 - 720x576@50
#131 - 720x576@100
#132 - 720x576@119

**Comment by MetalGearAlex1** [comment]
> Thanks, it's interesting that your screen shows so many modes, even strange ones like 25/29Hz etc. I think issue is our patch only sees the first instance of each resolution, so if the list has eg. 1920x1080@25Hz followed by 1920x1080@60Hz, the game only ends up seeing the 25Hz one, good chance your screen is probably exposing something like a 25Hz mode but doesn't actually support it properly, turning it green instead.
> 
> Also didn't realize you had two displays connected, game seems to have really poor support for that, wouldn't be surprised if that is related somehow (eg. it seems to always check adapter 0 even if you edit INI to use other adapters)
> 
> Might try reimplementing the display-mode related funcs soon instead of just patching, so we could probably add stuff to only allow modes with same refresh rate as desktop.

i agree with you. seems like a hopefully easy fix for I'm sure there are people that may have this issue especially with laptops maybe.  thank you very much. just respond to me if you need me to try more things.

**Comment by MetalGearAlex1** [comment]
another note. i only edit ini to FALSE when on 1/2 displays.  but on tv only display to fix green screen. i do not have to edit the ini to FALSE.

**Comment by nipkownix** [comment]
>I think issue is our patch only sees the first instance of each resolution, so if the list has eg. 1920x1080@25Hz followed by 1920x1080@60Hz, the game only ends up seeing the 25Hz one

So.. that is probably the reason they used the 60Hz check for the resolution list instead of comparing height+width. Hm.

**Comment by MetalGearAlex1** [comment]
> New question. I got leon stuck looking up while using xbox controller while running. Happemed after i tried the f1 tweaks i think. But on mouse/keyboard he is fine while im running. Even switched out the xbox controller. Is there a way to reset the original re4 steam file settings? I think this is seperate from the patch itself.

I'm not sure why this is happening but I just came across that issue right now and what worked was plugging in the controller via USB to my PC and it fixes the issue, I can then unplug it and works fine. When i restart though i have to do it again because it resets back to the buggy mess it is. hope this helps.

update:
OK, so I think I found a fix. The problem is the game is recognize multiple controller profiles and it gets confused. What I did was go to Steam - Settings - Controller - General Controller Settings and ticked the following boxes: Guide Button Focuses Steam, Xbox Configuration Support and Generic Game-pad Configuration Support.

**Comment by emoose** [comment]
@MetalGearAlex1 any chance you can try this build out, and see if you can get green screen to occur?

[re4_tweaks1.7.4-refreshRateCheck.zip](https://github.com/nipkownix/re4_tweaks/files/7990251/re4_tweaks1.7.4-refreshRateCheck.zip)

This one should filter the display modes so only ones that are 59Hz+ can be chosen, but I'm not sure if it'll actually help since the function we patch here (second EnumAdapterModes func) only seems to be ran when you open options menu, so not sure if that func is actually causing it, could be the first func we patch instead somehow.

**Comment by MetalGearAlex1** [comment]
Yes. I will give that a try.

**Comment by MetalGearAlex1** [comment]
![16438406510407619320154671463310](https://user-images.githubusercontent.com/60905632/152247680-fe58c836-e383-417e-be19-535dc2977cc4.jpg)
Nope. Still green when 2 displays with those files i put in. 
But on tv only display. Not green

**Comment by emoose** [comment]
Ahh too bad, but figured that'd probably be the case, I guess it must be something to do with our first patch that uses `g_UserRefreshRate` then - weird because that should be using refresh rate of desktop - but then again you are using two displays, so maybe it's picking refresh rate on the wrong one?

**Comment by MetalGearAlex1** [comment]
I will have to check it out in about 3 or 4 hours at the latest if thats ok. Im glad to help. It is fun to be part of the problem :) and the solution. I have been playing re4 repeatedly since ps2 days.

**Comment by MetalGearAlex1** [comment]
![20220202_214603](https://user-images.githubusercontent.com/60905632/152273040-b4b6976f-c31d-4cf2-b332-1161fe22e592.jpg)

**Comment by emoose** [comment]
Thanks, so I guess that display is being forced to 120 but doesn't like it (I think it must be exposing 120 for game to try setting it though)

Could you try editing dinput8.ini, and change `CustomRefreshRate` to 60, and see if green screen appears at all with that?

Also could you try this build out: [re4_tweaks1.7.4-EnumDisplayDevices.zip](https://github.com/nipkownix/re4_tweaks/files/7991635/re4_tweaks1.7.4-EnumDisplayDevices.zip) and see if green screen happens at all.
(make sure `CustomRefreshRate` is set back to -1 with that build)

**Comment by MetalGearAlex1** [comment]
I will try it. Fighting a gigante right now. I was also testing different resolutions in game. And discovered it turns green at a few them. One of them being the 4k option i think. Which is odd since i have a 4k lg cx. But no big deal. I will see what happens to ur tests.

**Comment by MetalGearAlex1** [comment]
Ok. I tried both things. Also did them both on 2 display and single display. No green screen at any resolution now. Seems it does not like 120. Forcing it to stay at 60 seems to be the answer.

**Comment by emoose** [comment]
Ahh nice, so the ZIP I posted also worked too? You had `CustomRefreshRate` set to -1 for that as well?

**Comment by MetalGearAlex1** [comment]
Yes. It was back to -1. And first test to 60 worked both ways. 2nd test with ur build worked being at -1 again. I dont know what u did. But i didnt have any more issues. Thank you. :)

**Comment by emoose** [comment]
Awesome! Glad to hear it helped, thanks for letting us know of the issue and all the testing too! Will hopefully have this merged in soon.

**Comment by MetalGearAlex1** [comment]
I have donated 60 $ to the cause because this is defibitely an HD rerelease i would pay for in store at a high... price. Stranger. Thanku.

**Comment by Mister-Curious** [comment]
OMG every open issue was tagged because of the formatting of # xx in [this post](https://github.com/nipkownix/re4_tweaks/issues/51#issuecomment-1028034189). Is there a way to fix that?

**Comment by nipkownix** [comment]
lol
I tried removing the # xx in the post, but it looks like the mentions dont go away. Oh well. Not a big deal, we just have to remember to avoid something like this again in the future, I guess.

**Comment by MetalGearAlex1** [comment]
Sho7ld be fixed now. I will come back to finish and celebrate this post when u get to 100 issues. Thanku
