### ISSUE TITLE
RE4 Tweaks resetting everytime the game is restarted

### ISSUE THREAD

**Issue by EonianDaemonia** [nipkownix/re4_tweaks#55]
The problem is shown on the first minute of the video, it's happening with it's integrated version on the Resident Evil 4 HD Project 1.0.

https://drive.google.com/file/d/1NPzDqE6N1-Bxjs9n7RHvoDyAwRw4H6DE/view?usp=sharing

**Comment by nipkownix** [comment]
Hmm, thanks for the report. I'm not sure, maybe albert marked the file as read-only before uploading it. I'll ask him.
