### ISSUE TITLE
Incorrect water rendering at ultrawide and superwide resolutions

### ISSUE THREAD

**Issue by RiasatSalminSami** [nipkownix/re4_tweaks#57]
Water rendering is bugged with 21:9 and 32:9 aspect ratios.

Here is comparison video with the 1.0 build of Hd project mod and without mod:

https://www.youtube.com/watch?v=I0FfWEVc60E

In both cases, the FOV fix using RE4 Tweak mod has been applied.
It seems like the problem only appears after installing the HD project mod.

**Comment by RiasatSalminSami** [comment]
Don't know if I should make a separate thread for this, but few particular blur filters are broken on ultrawide [or basically anything beyond 16:9] aspect ratios. Here are some example screenshots:

https://cdn.discordapp.com/attachments/663406242085077022/938551332250464346/unknown.png
https://cdn.discordapp.com/attachments/663406242085077022/938551532432015400/unknown.png

The issues in the attached screenshots are not tied to HD project mod. This happens regardless it being installed or not.

**Comment by emoose** [comment]
@RiasatSalminSami could you check if disabling `EnableGCBlur` in dinput8.ini gets rid of that blur issue? Good chance it's that effect which causes it, unfortunately.

**Comment by nipkownix** [comment]
There's no issue if re4_tweaks is used without the HD project, then? I'm a bit confused.

**Comment by RiasatSalminSami** [comment]
> @RiasatSalminSami could you check if disabling `EnableGCBlur` in dinput8.ini gets rid of that blur issue? Good chance it's that effect which causes it, unfortunately.

Yeah, it was already disabled. The examples screenshots were taken with GCblur disabled.

**Comment by RiasatSalminSami** [comment]
> There's no issue if re4_tweaks is used without the HD project, then? I'm a bit confused.

Yeah the water reflection bug is tied to HD mod as seen in the comparison video.

The blur effect bug [as shown in my 2nd comment] is there even without the HD mod. 


I think I should just make a separate issue for the 2nd post here since that doesn't seem to be related to the water bug.

**Comment by Cipherix02** [comment]
Something about reflections got broken when using a 21:9 with the HD project 1.0

![Broken blur](https://user-images.githubusercontent.com/65146928/152249698-57bc181b-12b0-4f06-8a77-dc00622243d1.jpeg)


![Brokenblur p2](https://user-images.githubusercontent.com/65146928/152249706-6e10973a-6575-44f7-9de4-f293f2c3eefb.jpeg)
