### ISSUE TITLE
Modded ss_pzzl crash

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#6]
Seems modded ss_pzzl can still cause a crash when a note/file item is being read, not sure if it's all note items, but the one in Salazar Castle just outside the knight room loading door seems to always crash for me.

Original ss_pzzl works fine, so it's probably not related to buffer being relocated, guess it's probably overloading something else.

E: strange, this only seems to happen when launched through steam, running Bio4.exe itself (eg. through IDA's debugger) seems to stop it crashing, weird.

**Comment by nipkownix** [comment]
> E: strange, this only seems to happen when launched through steam, running Bio4.exe itself (eg. through IDA's debugger) seems to stop it crashing, weird.

Wouldn't be the first instance I see of a game not crashing when using a debugger, sadly. 

Also, albert mentioned he hit a polygon limit with the model in ss_pzzl.dat. Apparently the game crashes if any model has more than 3000 polygons or so. I asked him to send me a sample so we can take a looks. Maybe it is a similar issue to the FOV one?

**Comment by emoose** [comment]
Seems there's a temp buffer allocated at 0x974964 (1.1.0), normally 0x4000 bytes, but the func that crashes tries accessing something like 0x35400 into it.

Tried changing to 0x40000 & 0x100000 but still crashes, but 0x400000 seems to stop it.

Even though it's only 4MB that's a pretty big increase over the original... could be that whatever it's using to generate that 0x35400 offset is messing up in some way, and changing to 0x400000 is just a band-aid that happens to stop it crashing, not sure though.

**Comment by emoose** [comment]
Ahh looks like it's caused by memory corruption, mem_alloc @ 0x6590E8 tries allocing an addr from our g_MemPool_SubScreen2 buffer/heap, but that returns an addr which is already in use by other data, making that func overwrite some of it.

Seems one of the commented-out lines in my post for the pzzl fix fixes it though:

```C
SafeWrite(GameAddress + 0x374E1E + 2, (uint32_t)(sizeof(g_MemPool_SubScreen) - 0x2000000));
```

I guess this is changing how many bytes at the start of the heap are reserved for the pzzl stuff, should split it so one half is reserved for pzzl & the other for any pzzl-related mem_allocs

**Comment by nipkownix** [comment]
Nice finds.

I'm not at home, so I can't see if that fixes the issue albert is having:

>I did the test with that 4MB ss_pzzl and it all was ok when I started a new round (So, you first enter the Merchant shop and then you start the game) Then I openend the inventory and all was OK. But if you load a savegame in a middle point of the game and open your inventory the game crashes :/

Here's the 4MB ss_pzzl he sent me:
[ss_pzzl.zip](https://github.com/nipkownix/re4_tweaks/files/7454062/ss_pzzl.zip)

**Comment by emoose** [comment]
Looks like the patch in my prev post stops it crashing, but the items are all corrupt, maybe because I don't have the textures for it? (https://residentevilmodding.boards.net/thread/7384/item-mods-modding-inventory-items mentions 3b000001 inside ImagePackHD being the texture for the ss_pzzl models)

After that fix above I think ss_pzzl might still need some extra patches, to get rid of the 0x1CB5400 offset being applied to it (if mem_alloc starts allocing from 0x2000000, that means ss_pzzl only has 0x2000000 - 0x1CB5400 = 0x34AC00 bytes space, which is exactly what it originally had... not really sure why it's working with just the single patch above)

**Comment by nipkownix** [comment]
> Looks like the patch in my prev post stops it crashing, but the items are all corrupt, maybe because I don't have the textures for it? 

Ah, this is happening, because albert replaced a bunch of models with a high-poly matilda model for testing the limits :p

> This should remove that offset from everything:

Nice! I'll see if I can get some sigs for those.

**Comment by nipkownix** [comment]
Done. As of the latest commit, everything should work across all main 3 EXEs.
