### ISSUE TITLE
WindowBorderless causes cursor to freeze when opening certain programs

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#612]
I thought that this was a very bizarre Windows 10 issue but it looks like it happens whenever I decide to play RE4 with WindowBorderless enabled (with fullscreen also turned off).

I also noticed that the WindowBorderless setting seems to apply in a way that looks similar to when fullscreen is enabled. On older versions the setting never did this afaik.

**Comment by ViperAcidZX** [comment]
> I also noticed that the WindowBorderless setting seems to apply in a way that looks similar to when fullscreen is enabled. On older versions the setting never did this afaik.

I think this might be a DXVK issue because other games I tried that has its own borderless fullscreen function suddenly turns it into exclusive fullscreen for whatever reason.

**Comment by linkthehylian** [comment]
> I think this might be a DXVK issue because other games I tried that has its own borderless fullscreen function suddenly turns it into exclusive fullscreen for whatever reason.

Yep, DXVK being enabled was it. Thank you so much!
