### ISSUE TITLE
Allow savegame transfers

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#67]
Game seems to check for SteamID inside savegame00.sav file, and refuses to load if it's different... Seems to have an ID at 0x1E40, and I guess there's a checksum/hash somewhere that it checks too since editing that ID doesn't seem to work.

Probably wouldn't be too hard to remove SteamID check.

E: seems to be two checks inside `CRCVerifyCRC`, 0x83DB95 & 0x83DBA4, with those two nopped it seems to load saves from other people fine.

**Comment by MetalGearAlex1** [comment]
Can you pleasssssseee tell me if i can now use other save games? Ive seen that savegame00 file. What can i do now once thats patched. Just replace it with any bodys save?

**Comment by nipkownix** [comment]
Yeah, you should be able to just replace the file and load the game without problems. There's isn't a build with that change available for now.. and I'm not at home tonight, so I won't be able to provide you one for testing until tomorrow. If emoose doesn't best me to it, I'll upload you a build tomorrow.

**Comment by MetalGearAlex1** [comment]
Great. Id love to test a 100% complete save. If you can give me a build. To adjust the savegame00

**Comment by emoose** [comment]
@MetalGearAlex1 posted a build at https://github.com/nipkownix/re4_tweaks/pull/87#issuecomment-1030532371 which has the savegame transfer fix.

Might want to backup your original savegame00 file, also one thing to watch out for: game seems to use steam cloud save stuff pretty heavily (spent like 30 minutes trying to make it accept a new savegame00, before I had transfer fix working game deleted it since it was from different account, and also deleted from cloud save - when I tried copying my original save back in, it refused to see it because cloud had no save file, had to create a new save & then overwrite it instead)

**Comment by MetalGearAlex1** [comment]
Yes. How do i get in the cloud to delete original savegame is the next question. I will mess around with it all. Thanku. I will report back when i get a chance :)

**Comment by nipkownix** [comment]
Here's an easy way to do it:

Open the game, and as soon as the capcom logo shows up, ALT+TAB and leave it minimized.
Then you put your new save in the folder as usual, and go back to the game.
The game will only load your save after you've pressed "any key" on the title screen. As long as you switch your save before doing that, you should be fine, and steam cloud shouldn't interfere.

**Comment by MetalGearAlex1** [comment]
Nice. Thank you very much. I heard saves were tied to steam id but im guessing thats part of the fix. I also, while im here, FOUND one minor mistake in target practice room on a paper on the wall next to seller. Check my twitter https://twitter.com/UnMetalAlex/status/1489779195576258561?t=7fcx3iBdJhDSepb1_OpBTw&s=19

Plz let albert know. Thanku.

**Comment by nipkownix** [comment]
Oh, I'll let albert know. Thanks for the report!

**Comment by MetalGearAlex1** [comment]
> Here's an easy way to do it:
> 
> Open the game, and as soon as the capcom logo shows up, ALT+TAB and leave it minimized. Then you put your new save in the folder as usual, and go back to the game. The game will only load your save after you've pressed "any key" on the title screen. As long as you switch your save before doing that, you should be fine, and steam cloud shouldn't interfere.

i couldn't get it to work. sorry. any ideas?

**Comment by emoose** [comment]
It might be pulling old save down from cloud when load menu is shown (seems to do a lot of stuff with SteamRemoteStorage anyway), maybe try what nipkow suggested but close down the game right after you copied the new save file in (without opening load screen), after game is closed Steam should then upload the new save to cloud, and hopefully a game relaunch might get it to start using it.

**Comment by MetalGearAlex1** [comment]
> @MetalGearAlex1 posted a build at [#87 (comment)](https://github.com/nipkownix/re4_tweaks/pull/87#issuecomment-1030532371) which has the savegame transfer fix.
> 
> Might want to backup your original savegame00 file, also one thing to watch out for: game seems to use steam cloud save stuff pretty heavily (spent like 30 minutes trying to make it accept a new savegame00, before I had transfer fix working game deleted it since it was from different account, and also deleted from cloud save - when I tried copying my original save back in, it refused to see it because cloud had no save file, had to create a new save & then overwrite it instead)

Ok. I screwed myself over. Now i lost my original save and cant use the 100% save file. Can you walk me through how to find the cloud save place and etc?

**Comment by emoose** [comment]
`C:\Program Files (x86)\Steam\userdata\52890896\254700\remote\` is where savegame00.dat is kept for me, if you don't have one there you might need to run game again and let it create a new one first.

**Comment by MetalGearAlex1** [comment]
Yes. I got that far before commenting and put in the build 87 dinput8.dll and ini. Tried tge alt tab thingy. Wouldnt work. So im trying to find how to find the cloud itself and punch the cloud :)

**Comment by MetalGearAlex1** [comment]
Alright. Couldnt get it to work. That is ok. For now... i will just have to start over and be sad :(

**Comment by MetalGearAlex1** [comment]
Any chance you can edit the ini to include a 100% completed option only accessible by going to ini and typing True?

**Comment by MetalGearAlex1** [comment]
Good news. I just debug menued area jumped to proper checkpoints. Pickibg up Ashley first of course. And going to chapter save screens. And then beat the final boss to get the boat key and was able to beat it that way. Now i can replay entire game properly ;)
