### ISSUE TITLE
Game will not start with the DLLs installed

### ISSUE THREAD

**Issue by Eromano2001** [nipkownix/re4_tweaks#81]
I recently installed the HD project for the game, alongside the RE4 Tweaks. The game only started WITHOUT the tweak's DLLs. Then, I unninstaled everything and, instead of using the HD project, I installed only the DLLs. And to my surprise, the game didn't open. Even the base game, without any mods, still does not open. I have the 1.1.0 version, Steam release of the game, so I really need some help here, as the tweaks themselves don't work, even without the HD project installed.

Also, yes, I tried to change the DLL's names, as seen in a previous post of someone whom had a similar issue to mine. That did not work either.

**Comment by emoose** [comment]
Hmm, could you try running the game through Steam with the [latest re4_tweaks release](https://github.com/nipkownix/re4_tweaks/releases), and then open up Event Viewer (WinKey+R, type in `eventvwr.msc` and press enter), then go to `Windows Logs -> Application`, and see if any of the entries near the top mention bio4.exe at all?

**Comment by nipkownix** [comment]
Just a correction: the folder name should be "CrashDumps" instead.

**Comment by Eromano2001** [comment]
Tried that. Nothing appears in the event viewer, not a message at all. Nothing appears in the CrashDumps folder I have created inside Bin32 either. I'll send screenshots and videos.

**Comment by Eromano2001** [comment]
https://youtu.be/cUiILusY890

I recorded my screen to further illustrate what I'm dealing with.

**Comment by emoose** [comment]
Strange... could you try enabling file extensions (https://vtcri.kayako.com/article/296-view-file-extensions-windows-10), and then take a screenshot of the folder (press PrintScreen, then click on textbox here and press CTRL+V and it should upload)

Also I noticed you're in non-English locale, looks like Portugal right? Maybe try seeing if changing to English helps at all.

**Comment by Eromano2001** [comment]
This does not make any sense. The game works fine without the tweaks, but not with them. I enabled file extensions.

![image](https://user-images.githubusercontent.com/98999330/152709317-8ee093f1-355d-40b7-a799-fdc0c9287ce7.png)

**Comment by Eromano2001** [comment]
No, the game was not manually patched.

**Comment by Eromano2001** [comment]
Forget it. I'll have to play without the fixes and without HD Project. I followed EXACTLY the instructions, downloaded the game four times and the HD Project other two times. I give up.
