### ISSUE TITLE
[Feature request]  Modifier key to switch off new mouse controls

### ISSUE THREAD

**Issue by RiasatSalminSami** [nipkownix/re4_tweaks#83]
The idea is very simple. Say if I hold the modifier key and move the mouse, then the camera will rotate around Leon like it usually does in the default game. But when I release the key, then moving the mouse will just rotate Leon.

This can be applicable in both ways:

-If new mouse controls are enabled: Then the modifier key will switch the mouse controls to default vanilla controls.
-If new mouse controls are disabled: Then the modifier key will switch the mouse controls to new one.

**Comment by abi-21** [comment]
Sounds like a good idea, similar like in Arma games where you hold ALT key.

**Comment by emoose** [comment]
Good idea, I think for this it'd probably be good if we could support mouse buttons as well, don't think we have anything for them right now though.

**Comment by RiasatSalminSami** [comment]
> Good idea, I think for this it'd probably be good if we could support mouse buttons as well, don't think we have anything for them right now though.

Yeah, instead of modifier key, we should be able to use the side mouse buttons or the scroll wheel button as modifier if possible.

**Comment by emoose** [comment]
Had a try at implementing this here: https://github.com/emoose/re4_tweaks/tree/mouseturn-modifier

Seems to work, but camera acts strange after releasing modifier, somehow it stays locked at the position you move it to with modifier held, and doesn't center or anything when mouse-turning, is that something to do with the mouse-turn impl?

Here's a build if anyone wants to try it:
[re4_tweaks1.7.4-MouseTurningModifier.zip](https://github.com/nipkownix/re4_tweaks/files/8005886/re4_tweaks1.7.4-MouseTurningModifier.zip)

You should be able to edit the MouseTurnModifier key to mouse buttons too, MOUSE1 to MOUSE5 (or LMOUSE/MMOUSE/RMOUSE)

**Comment by RiasatSalminSami** [comment]
> Had a try at implementing this here: https://github.com/emoose/re4_tweaks/tree/mouseturn-modifier
> 
> Seems to work, but camera acts strange after releasing modifier, somehow it stays locked at the position you move it to with modifier held, and doesn't center or anything when mouse-turning, is that something to do with the mouse-turn impl? I guess mouse-turning probably assumes camera is centered at all times.
> 
> Here's a build if anyone wants to try it (modifier set to ALT, you can edit it in dinput8.ini) [re4_tweaks1.7.4-MouseTurningModifier.zip](https://github.com/nipkownix/re4_tweaks/files/8005886/re4_tweaks1.7.4-MouseTurningModifier.zip)
> 
> You should be able to edit the MouseTurnModifier key to mouse buttons too, MOUSE1 to MOUSE5 (or LMOUSE/MMOUSE/RMOUSE), not sure if MOUSE4 & MOUSE5 actually work though since my mouse doesn't use them.
> 
> All those GetAsyncKeyState calls is probably inefficient though... would be nicer if we could hook somewhere near start of frame, and then could cache GetAsyncKeyState results for all the keys we support, maybe something to look into later on.

I'm gonna test it.

As for the camera not being centered, yeah thats how it has been even with the current mouse panning feature. You can recreate this by going in game, disabling the mouse panning [via the f1 menu] looking around Leon and then enabling the mouse panning option again.

Camera will now be stuck with whatever position it was in.

**Comment by RiasatSalminSami** [comment]
Just finished testing, yeah the camera behaves weirdly.

It has two problems.

1. Like you mentioned, the camera doesn't automatically centers itself after releasing the modifier key.
2. say if you turned Leon to right using mouse and then pressed the modifier key, the camera would instantly pan right to Leon, which makes it unusable at the moment.

**Comment by emoose** [comment]
Hmm, I guess because mouse position is changed while mouse-turning, when modifier is pressed game finally sees the new mouse position & then updates camera to rotate toward it, hmm...

For centering, could probably just add code that detects if mouse-turn state changed (changed in F1, or modifier pressed/released), and center camera if so, not really sure what best way to change camera is atm though.

**Comment by nipkownix** [comment]
Yeah, I struggled with camera moviment when doing the MouseTurning patches.

Maybe you should open a PR with that current branch. Then I'll push some fixes tomorrow if I managed to improve the camera stuff.

>All those GetAsyncKeyState calls is probably inefficient though... would be nicer if we could hook somewhere near start of frame, and then could cache GetAsyncKeyState results for all the keys we support, maybe something to look into later on.

Can't we use the WndProcHook to get key events for this case?
