### ISSUE TITLE
Sudden half second freeze on cutscene, causing cutscene desync issue

### ISSUE THREAD

**Issue by shiiironyanpan** [nipkownix/re4_tweaks#90]
Hi, I've discovered something that might probably be useful for troubleshooting. I already reported this to Albert and I think it would be a great idea to actually inform about it here as well. I'll talk about how the bug happens and how to reproduce it

`In this case I'm using Rivatuner Statistic Server (aka RTSS) to demonstrate the issue to make things clearer to see`

> -  This issue happens on some cutscenes (mostly noticable on first cutscene on Chapter 1-2 and first encounter with Saddler in the Church on Chapter 2-1)
> - The sudden freeze happens when you load a save and a starting cutscene is being played. Chapter 1-2 is the most noticable one in this case. This issue will be reproduced everytime you load the save as if the game hasn't done loading assets for the cutscene. It also always will reproduce on a reload since the game decided to reload all assets.
> - It can also produce on Movie Browser but the issue is "kinda solved" when the cutscene is being played *more than once* on Movie Browser (second time playing cutscene). It will reproduce everytime after you exit the Movie Browser.
> - On the statistic graph from RTSS, the FPS counter, the graph, and the game froze when the cutscene audio starts to play. After that, the game proceed to continue, like how the shaders are being complied on most of console emulator with Async + shader compiler method. This caused a huge desync
> - The graph shows huge spike which occurs to every cutscene, except it froze before the graph continues.

Hopefully this will be useful for some debugging and fixing, thanks for all of you guys' hard work and cheers!

**Comment by Mister-Curious** [comment]
I would be interested to see if your game would stutter with the original EVD files in place (you might need to also use the original pack files for these). I suspect the modified BIN files for characters and enemies in the EVD files may have something to do with this (been speaking to Albert about this), and I believe this could be related to #43. 

I would be willing to help if you want to test this. I could tell you which files to put back etc.

**Comment by shiiironyanpan** [comment]
> I would be interested to see if your game would stutter with the original EVD files in place (you might need to also use the original pack files for these). I suspect the modified BIN files for characters and enemies in the EVD files may have something to do with this (been speaking to Albert about this), and I believe this could be related to #43.
> 
> I would be willing to help if you want to test this. I could tell you which files to put back etc.

I just tried to use original game files, reinstalling game and using patch and then it just works fine with no issue, what is the case here?

**Comment by Mister-Curious** [comment]
> I just tried to use original game files, reinstalling game and using patch and then it just works fine with no issue, what is the case here?
I imagine it has something to do with bone weights. Albert said that even the slightest edit to the EVD BIN models can cause all kinds of issues. It might be something with the way the tools we have are repacking the files, but I think Albert said he did painstaking manual edits to these models so its hard to say. I am awaiting a response from him on this matter, but it could be a while as he is inundated with lots of stuff since this release came out.

I will provide any pertinent info here after I speak with him again. Its my hope we can identify what is going on and perhaps the RE4 Tweaks can fix it.

**Comment by shiiironyanpan** [comment]
> > I just tried to use original game files, reinstalling game and using patch and then it just works fine with no issue, what is the case here?
> > I imagine it has something to do with bone weights. Albert said that even the slightest edit to the EVD BIN models can cause all kinds of issues. It might be something with the way the tools we have are repacking the files, but I think Albert said he did painstaking manual edits to these models so its hard to say. I am awaiting a response from him on this matter, but it could be a while as he is inundated with lots of stuff since this release came out.
> 
> I will provide any pertinent info here after I speak with him again. Its my hope we can identify what is going on and perhaps the RE4 Tweaks can fix it.

The latest hotfix oatch (1.0.1) fixed the issue, dunno what you guys did there but thanks to the developer, Albert and you :D

**Comment by Mister-Curious** [comment]
@shiiironyanpan was the patch you downloaded for RE4 HD Project or RE4 Tweaks?

**Comment by shiiironyanpan** [comment]
> @shiiironyanpan was the patch you downloaded for RE4 HD Project or RE4 Tweaks?

HD Project, obviously
