### ISSUE TITLE
Passing 64-bit long to WriteMemory<int>

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#99]
VS gives some warnings about these:
https://github.com/nipkownix/re4_tweaks/blob/139e550c594afa22d1e34507fbdda9dc770f90d3/dllmain/HandleLimits.cpp#L160-L177

I think removing the 0x68 part from it should be fine, that's probably what ends up happening anyway. Maybe better to just replace them with the decimal value to match comments.

E: oh didn't realize this was actually same file as RaiseInventoryAlloc, guess I can fix those in that PR. (E: added)

**Comment by nipkownix** [comment]
Cool. Gotta admit I was too lazy to fix those. Thanks for doing it.

**Comment by emoose** [comment]
Ah thought I'd replied to this sooner, sorry about that - changes look fine to me, wasn't sure about changing `PRICE_INFO` to unsigned but seems code does treat the price part as unsigned at least, so should be fine.
